### ISSUE TITLE
Pass data from parent to router view children

### ISSUE THREAD

**Issue by DevEclipse** [vuejs/vue-router#1007]
Is this implemented?

so that i can reuse the data rather declaring it multiple times

**Comment by LinusBorg** [comment]
Hello @DevEclipse 

Thank your for your interest in this project.

However, your issue is a usage/support question, and the issue tracker is reserved exclusively for bug reports and feature requests (as outlined in our [Contributing Guide](https://github.com/vuejs/vue/blob/dev/.github/CONTRIBUTING.md)).

We encourage you to ask it on the [forum ](http://forum.vuejs.org) , [Stack Overflow](http://stackoverflow.com/questions/tagged/vue.js) or on [gitter](http://gitter.im/vuejs/vue) and are happy to help you out there.

If you want to create a feature request, please be more specific in your description of the desired behaviour, e.g. with a code example.
