### ISSUE TITLE
lazy load 3rd party library like leaflet

### ISSUE THREAD

**Issue by goldalworming** [vuejs/vue-router#1008]
how do I lazy load another library like leaflet in one page of router url?
how do I define it?
is it possible?

const routes = [
  {
    path: '/',
    name: 'root',
    component: {template: '<div>Root Path</div>'},
    meta: { bcLinkText: 'Default Page'},
  },
  {
    path: '/map',
    name: 'map',
    component: {template: '<div>Leaflet Map</div>'},
    meta: { bcLinkText: 'Map Page'},
  },
]

**Comment by LinusBorg** [comment]
Hello @goldalworming 

Thank your for your interest in this project.

However, your issue is a usage/support question, and the issue tracker is reserved exclusively for bug reports and feature requests (as outlined in our [Contributing Guide](https://github.com/vuejs/vue/blob/dev/.github/CONTRIBUTING.md)).

We encourage you to ask it on the [forum ](http://forum.vuejs.org) , [Stack Overflow](http://stackoverflow.com/questions/tagged/vue.js) or on [gitter](http://gitter.im/vuejs/vue) and are happy to help you out there.

**Comment by goldalworming** [comment]
my registration is not allowed from my ip

**Comment by LinusBorg** [comment]
Then we probably received spam from this IP and blocked it for this reason. 

Are you on a corporate, university or school network?

What is the exact error you see?

**Comment by goldalworming** [comment]
![image](https://cloud.githubusercontent.com/assets/440256/21215037/3f90cce6-c2d1-11e6-9d8c-e96e15fd3729.png)
I didn't get any email even in spam
