### ISSUE TITLE
Add an example how to use typings/typescript and vue-router

### ISSUE THREAD

**Issue by kkamkou** [vuejs/vue-router#1019]
As soon as `vue-router.d.ts` is [outdated](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/vue-router/index.d.ts), please add an example how to use typings/typescript and vue-router having the `basic` version.

Thank you.

**Comment by fnlctrl** [comment]
Hi, thanks for filling this issue. Types are currently [managed in the package](https://github.com/vuejs/vue-router/tree/dev/types), so you can simply import them without using DefinitelyTyped.

**Comment by kkamkou** [comment]
An issue might be in a lack of documentation, what you did is an adorable way to manage them. `typings install` and `import Vue = require('vue'); import VueRouter = require('vue-router')` produces errors in my case.

**Comment by ktsn** [comment]
You should not use typings to use vue-router types because it will install the old version (for v0.7) declaration file. You can use v2.0 types by just doing `npm install vue-router`

**Comment by kkamkou** [comment]
`typings` can install it from the source (`github`). That is what I do. The commit is: 4561ecf58581b8ed852a3f9a33d3dbaf2f7f4a45.

**Comment by ktsn** [comment]
Ah, I see. But I think you can just install and use the `types` directory by `typings i -S github:vuejs/vue-router/types#4561ecf`

**Comment by kkamkou** [comment]
that was exactly what I did, could you paste basic example?

**Comment by kkamkou** [comment]
https://github.com/vuejs/vue-router/blob/dev/examples/basic/app.js

**Comment by ktsn** [comment]
OK, do you mean there is an error on passing a router object to a Vue instance, don't you?
Hmm, looks like the module augmentation of vue-router is failed if we use vue-router d.ts with typings. The cause seems following:

1. Directory structures of declaration files are different between npm and typings
    A vue-router's declaration augments vue's declaration [by specifying its file path](https://github.com/vuejs/vue-router/blob/dev/types/vue.d.ts#L16). But if we install them by typings, the path is incorrect - it should be `vue/options` rather than `vue/types/options` since `types` will be the root directory.

2. Module name will be changed by typings
    Looks like typings prefixes each module names with `~` (e.g. `~vue/types/options`). This prevent us to augment vue's declaration.

We can solve 1. easily if we move each typings.json to the project root. But I have no idea how we can solve 2. 😞 

@HerringtonDarkholme @kaorun343
Do you have any idea to solve this?

**Comment by kkamkou** [comment]
I hope you consider this ticket as:
1. a lack of documentation;
2. I hope the ticket would be re-opened (what you did is just a shame).

Personally, my contribution here is complete.

**Comment by ktsn** [comment]
I think this is not the problem of documentation, just the problem of the declaration file setting.
btw, I don't have the permission to reopen the issue.

**Comment by HerringtonDarkholme** [comment]
Thanks for trying out vue-router with TypeScript.  

We do have a test on how to use vue router with TS.  https://github.com/vuejs/vue-router/tree/dev/types/test. You can refer it as an example. Yet I don't see much value to put it in doc, because `npm install` + `import Vue = require('vue')`.  is all you have to do. Everything should work out of box.

Fairly, no more can we tell you to do. In-package types are the reason why we can directly import vue without declaration.

If you install vue-router from `typings`, as @ktsn has pointed out, the declaration does not work because of how typings works. That is, _we **cannot** provide a working example for typing_ because typing is broken. Sorry 😞 .

I'm sorry that I'm not familiar with typing. However, I wonder how much value can supporting typing bring to users. Since vue-router should have already been working out of box.

**Comment by yyx990803** [comment]
2.x type declarations are implemented assuming the users use them the way TypeScript 2.x officially recommends: via `npm` packages. I don't think it's our fault for not documenting how to use it with an outdated setup.

I think the maintainers' explanations are patient and reasonable, your remark on it "being a shame" is unnecessary. Please avoid projecting your own frustration onto people who are trying to help you.
