### ISSUE TITLE
The transition is not effective for child route

### ISSUE THREAD

**Issue by 623023808** [vuejs/vue-router#1024]
The transition is not effective for child route

**Comment by LinusBorg** [comment]
Hello ...,

thank you for your filing this issue.

Please follow the [guidelines](https://github.com/vuejs/vue/blob/dev/.github/CONTRIBUTING.md) on how to report an issue. In particular, provide an example on www.jsfiddle.net (or a similar service) that reproduces the problem. If nessessary, create a repository for us to clone with a minimal reproduction. repositories of actual projects will generally not be accepted .

Otherwise, this issue will be closed.

Thank you.

**Comment by 623023808** [comment]
I have found the cause problems, All routing can only have one transition

**Comment by LinusBorg** [comment]
Sorry, I don't completely understand. Doe that mean you found out what your problem was and I can close this issue?

Otherwise, I repeat: Please provide a reproduction.

**Comment by LinusBorg** [comment]
Closed for lack of repro
