### ISSUE TITLE
Global mixin props didn't work

### ISSUE THREAD

**Issue by wotermelon** [vuejs/vue-router#1042]
### 1. vue / vue-router
2.1.6 / 2.1.1

### 2. happen

I used a ```global mixin props``` at all the components,it's normal if I didn't use the ```vue-router```.

[without vue-router JS Fiddle](https://jsfiddle.net/u4o35xw0/)

When I add the ```vue-router``` like this [with vue-router JS Fiddle](http://jsfiddle.net/xgrjzsup/778/), the prop didn't work as same as  ```without vue-router``` unless add props as options at the specific component.

Does it normal or it's a bug?

**Comment by fnlctrl** [comment]
This is because the global mixin also works for vue-router, and it made `somedata` a prop of `<router-view>` too. So `<router-view>` received the prop, instead of your component. So I think it's working as intended - though indeed a little confusing.

This is a relatively rare usecase and I can't really think of an elegant fix. However, there is a hacky way to prevent the mixin from being applied to vue-router, by calling `Vue = Vue.extend()` before using the mixin:

http://jsfiddle.net/pfqzpLdc/

**Comment by posva** [comment]
Also, a global prop is probably a bad idea. You can inject it where you need it

**Comment by trunda** [comment]
@posva Can you please give me a hint how to inject a prop lets say based on some $options?

**Comment by posva** [comment]
Sorry it wasn't clear: you can inject the mixin in every component that needs it instead of making the mixin global.
If you have more questions, please use the [forum](http://forum.vuejs.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js) instead, thanks!

**Comment by guibarscevicius** [comment]
Local mixins don't work either.
