### ISSUE TITLE
Preventing routing on argument change

### ISSUE THREAD

**Issue by unirgy** [vuejs/vue-router#1070]
Vue.js: 2.1.8 / 
vue-router: 2.1.1

Hello, I'm not sure if it's a bug or a feature.

I'm trying to confirm leaving not saved form route, and if user declines, to cancel changing the route.

It mostly works with `beforeRouteLeave: function (to, from, next) { if (!confirm('Leaving form')) next(false); }` 

The problem is with route arguments, like `#/form-path?id=5` - changing the `id` argument does not trigger `beforeRouteLeave`. Which hook can I use to prevent navigation on argument hange?

Thank you.

**Comment by posva** [comment]
Changing params or queries doesn't change the route, that's why those hooks are never triggered. In order to react to those changes, watch on the `$route.params` and `$route.query` properties.

~~We're getting this question too often but I cannot find a section mentioning it in the docs. I'll add it in the _Navigation Guards_ section~~

Actually there's a section here: https://router.vuejs.org/en/essentials/dynamic-matching.html#reacting-to-params-changes
I think it's worth mentioning it again in the navigation guards section
