### ISSUE TITLE
Remove beforeEach hooks

### ISSUE THREAD

**Issue by chenweiqun** [vuejs/vue-router#1106]
Whether the router can add a dynamic removal beforeEach function?

example:
```javascript
//add
let eachFnId =  router.beforeEach(...)
//remove sometime
router.removeBeforeEach(eachFnId)
```

**Comment by posva** [comment]
Why do you need to remove hooks? Usually, you add a hook that do checks inside to skip any unecessary work.
Keep in mind you can already remove hooks since it's just an array: `router.beforeHooks` and `router.afterHooks`

**Comment by chenweiqun** [comment]
Because I need not in the router-view components to intercept jumps,so I can only use **this. $ router.beforeEach (...)** to deal with,then I also need to destroy the component before the removal of this beforeEach

I think that should be done 😃

```javascript
VueRouter.prototype.beforeEach = function(fn) {
  this.beforeHooks.push(fn)
  return function(){
    _.pullAt(this.beforeHooks,fn);
  }
};

//usage:
let cancelFn = this.$router.beforeEach(...);

//sometime
cancelFn()
```

**Comment by yyx990803** [comment]
Sounds weird to modify global route hooks from inside a component - why not use `beforeRouteEnter`?

If you are not using `beforeRouteEnter` only because it doesn't trigger on params change, then what you want is probably what is suggested in #938.

Either way, I don't think it should be solved by adding the ability to remove global hooks...

**Comment by NoraGithub** [comment]
@yyx990803  There would be  such a situation that when I first access , because of SSR , I register a beforeEach Hook to sync cookie message into store.state. After `route.onReady()`, I don't need this global behavior because between client side visits, except login/logout, I would not manipulate cookie but store.state.

Any suggestion?
