### ISSUE TITLE
How add delimiter "/" in params with <router-link>?

### ISSUE THREAD

**Issue by nghiepdev** [vuejs/vue-router#1140]
Hi all,

I want to add params with delimiter "/":
```
<router-link :to="{name: 'abc', params: {slug: 'test1/test2'}}"></router-link>
```
or `router.push`
But It render `/test1%2Ftest2` not `test1/test2`

Please help me force it.

**Comment by posva** [comment]
You cannot use `/` as a delimiter inside a param because it's already used by URLs, so vue-router encodes it. You should use something else  like `-`, `_`, etc or split up the params in the route definition: `path: '/route/:param1/:param2'` so you can then do `params: { param1: 'test1', param2: 'test2' }`

---

Please, next time ask questions on the [forum](http://forum.vuejs.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js).

**Comment by nghiepdev** [comment]
Thanks very much.

I solved with `params: {slug: ['test1', 'test2']`.
