### ISSUE TITLE
Relative path does not work in default subroute

### ISSUE THREAD

**Issue by nkovacs** [vuejs/vue-router#115]
http://jsfiddle.net/nkovacs/9sx6vy04/

If you go to `/foo/bar`, then click the "go to baz" link inside foo, it works. But if you go to `/foo`, it doesn't work.

**Comment by nkovacs** [comment]
It works if the "Go to foo" link has a trailing slash: http://jsfiddle.net/nkovacs/9sx6vy04/1/, but I think it should work without the trailing slash too.
Also, the relative link doesn't get an active or active-exact class.

**Comment by yyx990803** [comment]
That's working as intended as far as I can tell: if you are at `/foo` and navigate to a relative link `baz`, you end up at `/baz`. If it assumes a trailing slash, when you go from `/foo/bar`, you'd end up at `/foo/bar/baz` instead of `/foo/baz`.

That's why you probably should avoid relative links when you can.

**Comment by nkovacs** [comment]
I wanted to use relative links so that I don't have to hard-code the base url within the subcomponents' templates. That way I can easily reuse the component or change its base url.
Basically what I'd need is:

* child link: a way to link to `/foo/bar` inside Foo's template
* sibling link: a way to link to `/foo/baz` inside Bar's template

in both cases without knowing that Foo is mapped to '/foo'. It could even be '/user/:id', so I'd need the dynamic segments inserted into the full url.

**Comment by yyx990803** [comment]
Take a look at named routes in 0.6.0: http://router.vuejs.org/en/named.html
