### ISSUE TITLE
Problem with router.beforeEach

### ISSUE THREAD

**Issue by jrpikong** [vuejs/vue-router#1253]
> I use Laravel 5.4 and vue.js 2
> for authorization page dhasboar I use route.beforeEach : http://router.vuejs.org/en/advanced/navigation-guards.html
> this may code 

app.js
===================
`import router from './routes.js';
require('./bootstrap');

const app = new Vue({
    el: '#app',
    router,
});

router.beforeEach((to,from,next) => {
    if(to.meta.requiresAuth){
        const authUser = JSON.parse(window.localStorage.getItem('authUser'))
        if(authUser && authUser.access_token){
            next()
        }else{
            next({
                path: '/login',
                query: { redirect: to.fullPath }
            })
        }
    }
    next()
})

`

my problem if I'm delete Localstorage in browser and refresh page not run to else codition, but  authUser.access_token not found

my full code in here please help me
https://github.com/jrpikong/wingding/blob/master/resources/assets/js/app.js

**Comment by posva** [comment]
Thank you for your interest in this project.

However, your issue is a usage/support question, and the issue tracker is reserved exclusively for bug reports and feature requests (as outlined in our [Contributing Guide](https://github.com/vuejs/vue/blob/dev/.github/CONTRIBUTING.md)).

We encourage you to ask it on the [forum ](http://forum.vuejs.org), [Stack Overflow](http://stackoverflow.com/questions/tagged/vue.js) or on [gitter](http://gitter.im/vuejs/vue) and are happy to help you out there. Come back open a new issue if you find out there's a real issue

**Comment by jrpikong** [comment]
Hello i have a problem in laravel vue 5.4 and 2, my problem if I press F5 in my browser
beforeEach not trigger on a full page reload.
but not if you navigate between pages via a router to link this is a job
can you help me
http://stackoverflow.com/questions/42818058/outer-beforeeach-in-laravel-5-4/42819437#42819437
