### ISSUE TITLE
About http://router.vuejs.org

### ISSUE THREAD

**Issue by bigZ-again** [vuejs/vue-router#1334]
### What problem does this feature solve?
I am learning router, I want to programmatic navigation from a path(components) to other path.
Because call router.push() in components isn't valid. I must emit a event to parent. 
I just add @jump="myjump" at router-view tag, everything is OK.
But I can't find any description about it in http://router.vuejs.org.

### What does the proposed API look like?
The vue's document is simple, clear, effective for me. I hope it would be better, so I suggest to add a little description about how to emit a event from components to parent, and how to capture components' event.
Just a little.
Thanks.

**Comment by LinusBorg** [comment]
> Because call router.push() in components isn't valid.

Of course that is valid.

> I just add @jump="myjump" at router-view tag, everything is OK. But I can't find any description about it in http://router.vuejs.org.

That's probably because we already explain that all components in vue-router are *normal Vue components*, so everything works the same.

Personally, I understand that very broad and well explained documentation is very helpul for beginners, but at the same time, documentation should be limited to the topic of the lib it is describing, or else the same things are repeated in multiple places and will create more work or possibilities for future mismatches when things change.

> I hope it would be better, so I suggest to add a little description about how to emit a event from components to parent, and how to capture components' event.

For the above reason, I don't think that we should explain in detail how Vue components work the same in the vue-router docs. But we could add a small mentioning [here](http://router.vuejs.org/en/api/router-view.html):

> ## Behaviour
> Any non-name props **and any`v-on` event bindings** will be passed along to the rendered component, however most of the time the per-route data is contained in the route's params.

**Comment by bigZ-again** [comment]
@LinusBorg Thank for your very detail explanation, and I agree with your opinion.
I should make some mistakes before. "router" is global,  router.push() can be called in anything. so $emit is complicated.
Maybe someone like this:
`let vm = new Vue({ router: new VueRouter({routes}) })`
In this case, $emit is necessary.

**Comment by LinusBorg** [comment]
Did you miss the fact that you can access the router from any component through `this.$router`

**Comment by posva** [comment]
This should be more clear with https://github.com/vuejs/vue-router/pull/1304
We should just deploy the docs again

Basically, you can do `$router.push` in templates 🙂
