### ISSUE TITLE
beforeRouteUpdate next() fires too early when re-visiting routes within "out-in" transition

### ISSUE THREAD

**Issue by henwen** [vuejs/vue-router#1372]
### Version
2.5.2

### Reproduction link
[https://jsfiddle.net/hwdearborn/y9xqgz1c/4/](https://jsfiddle.net/hwdearborn/y9xqgz1c/4/)

### Steps to reproduce
1. Click "to /", you will see "This is A"
2. Click 'to B", you will see "This is B"
3. Click 'to /" or use Back Button, you will see "This is"

Also note the console logs, which show how the order of the `next()` callback is different on the return visit (Step 3 above)  

### What is expected?
Without the "out-in" option on the `transition`, `beforeRouteEnter`'s `next()` callback is fired after Component A is mounted, and its `data` is properly set.

### What is actually happening?
*With* the "out-in" option on the `transition`, `beforeRouteEnter`'s `next()` callback is fired *before* Component A's `beforeCreate` event, causing the `data` to get overriden with its default (empty) value 

---
I came across this issue while trying to add an `out-in` transition to the [Fetching Before Navigation](https://router.vuejs.org/en/advanced/data-fetching.html)
example from the docs.

**Comment by kilobyte2007** [comment]
I have the same issue, any updates on it? I would consider it a bug, in 2.2.0 it was working perfectly.
Here is my fiddle: http://jsfiddle.net/2rwvw17L/3/
Steps to reproduce: Go to /home, then go to /e/1, then again to /home, then again to /e/1. 
We see there is not data set the seconds time because the vm object in the next callback is actually the old view.
