### ISSUE TITLE
Notify: false

### ISSUE THREAD

**Issue by krasevych** [vuejs/vue-router#1415]
### What problem does this feature solve?
I created landing page and when I scroll down to some section, the url should be changed without re-rendering the view or executing any router-event, when I use angular.js router, there I used some `notify:false`. like: `this.$state.go(this.currentTab, {}, {notify: false})`
How can I do the same with vue-router?

### What does the proposed API look like?
add some options: this.$router.push('#about', {notify: false});

**Comment by posva** [comment]
You can use regular links (those will always work and are the best solution). To programmatically navigate to an anchor, you can do that with js: http://stackoverflow.com/questions/13735912/anchor-jumping-by-using-javascript

if you want to use `router.push` you need to add an `afterEach` hook because when the URL changes the view hasn't updated yet and therefore the browser cannot scroll because the element doesn't exist yet. You can look up the solution in this example: http://jsfiddle.net/posva/sjo7n6bd/

A more natural solution will be using `scrollBehaviour` (which only works in history mode): http://jsfiddle.net/posva/bsr9qb3b/

Hope it helps 🙂

**Comment by krasevych** [comment]
no. I want to change url like this: `location.href = "#"+h;`  but I don't want that the router execute any callback like beforeEnter, afterEnter...
Only change url inside my location bar and no nothing, how can I do it?

**Comment by posva** [comment]
Look at the stackoverflow answer

**Comment by krasevych** [comment]
I wrote stackoverflow answer and tried to use the solutions: 
1)
```
function jump(h){
    var url = location.href;               //Save down the URL without hash.
    location.href = "#"+h;                 //Go to the target element.
    history.replaceState(null,null,url);   //Don't like hashes. Changing it back.
}​
```
2)
```
window.location = (""+window.location).replace(/#[A-Za-z0-9_]*$/,'')+"#myAnchor"
```

but it doesn't work. what do i wrondg

**Comment by krasevych** [comment]
I created small example https://jsfiddle.net/k2mw2j52/
method `updateUrlA` - should update location.href to '#hey' and scroll down to the element.
method `updateUrlB` - should update location.href to '#hey' BUT DOESN'T scroll down to the element.
how can I do it?
