### ISSUE TITLE
x

### ISSUE THREAD

**Issue by ghost** [vuejs/vue-router#1416]
x

**Comment by posva** [comment]
> When the user is found load their data into the page, but if the response is a 404, there is no clear and standard way of how to show the 404 component.

Yes, there's a ton of ways to handle, from a UI/UX point of view, a not found/error. You can display a modal, an error box, redirect, an in-page error adapted to the page. So, this is intentional, to make that possible.
About the API you proposed, you can already do something like that by providing a star path (`path: '*'`). You can give it a name and replace or push the route on error. You can also store at an application level the error state and display an error component instead of the `router-view` component
related #977
