### ISSUE TITLE
router.back do not work in HUAWEI glory 6

### ISSUE THREAD

**Issue by gxlfc** [vuejs/vue-router#1469]
version number：
 
"vue": "~2.0.0",
"vue-router": "~2.0.0"

router.push() work well，router.back()  no。

**Comment by posva** [comment]
Hi!
Please make sure to follow the [Issue Reporting Guidelines](https://github.com/vuejs/vue/blob/dev/.github/CONTRIBUTING.md#issue-reporting-guidelines) before opening an issue.
Thanks!

I imagine you're talking about huawei honor 6. You also need to provide a minimal repro when reporting a bug and specify the browser and os version. Although, it should work out of the box since it ships with android 4.4. So, I encourage you to check you're not using a proprietary browser that is quite outdated
