### ISSUE TITLE
beforeRouteEnter `next` callback does not fire before Server Side Rendering occurs

### ISSUE THREAD

**Issue by caleblloyd** [vuejs/vue-router#1489]
### What problem does this feature solve?
The `beforeRouteEnter`'s `next` callback does not resolve when using `vue-server-renderer`'s `renderToString` until after the server side rendering has occurred.

Since there is no `vue` instance data in `beforeRouteEnter`, there is no easy way to map the data that is loaded to an instance of an application.  Instance data is first introduced in the `next(vm: Vue)` callback, but at this point it is too late for Server Side Rendering since the app has already rendered.

This leads to the case where I (and potentially others) are having to use dirty hacks to map initial data.  In my case, the only solution I have found that works is:

1. Create a global map holding initial data with a key of `Route` [code](https://github.com/caleblloyd/dotnet-core-boilerplate/blob/61a4d4420757e1f2445d95fe02e97f5cbfcc153f/ui/src/dotvue/DotvueApp.ts#L5)
2. Save the initial data to this map in `beforeRouteEnter` [code](https://github.com/caleblloyd/dotnet-core-boilerplate/blob/61a4d4420757e1f2445d95fe02e97f5cbfcc153f/ui/src/controllers/PostsController.ts#L44)
3. Associate the initial data with an application instance in a `router.beforeResolve` callback [code](https://github.com/caleblloyd/dotnet-core-boilerplate/blob/61a4d4420757e1f2445d95fe02e97f5cbfcc153f/ui/src/dotvue/DotvueApp.ts#L29-L36)
4. Retrieve the initial data from the root application instance in the component's `created` lifecycle hook [code](https://github.com/caleblloyd/dotnet-core-boilerplate/blob/61a4d4420757e1f2445d95fe02e97f5cbfcc153f/ui/src/controllers/PostsController.ts#L54)

This is quite a lengthy process that would be unnecessary if `beforeRouteEnter`'s `next(vm: Vue)` callback resolved before Server Side Rendering took place.

### What does the proposed API look like?
Maybe the `next(vm: Vue)` callback could be adapted to run as part of a component's `created` lifecycle hook.

**Comment by LinusBorg** [comment]
The strategies to get asynchronous data are a bit different when doing SSR. Have you read this chapter in our (recently re-written) SSR guide about this topuic? 

https://ssr.vuejs.org/en/data.html

If so, can you describe the situation that requires you to use beforeRouteEnter instead of the strategies outlined in the above link?

**Comment by caleblloyd** [comment]
Yes I did start with that guide but encountered issues. When I run:

`Promise.all(matchedComponents.map(Component => {...` the variable `Component` is a Vue Configuration object, not a Vue Component instance. Therefore I cannot access any instance members since the component has not been instantiated.

I am using typescript with https://github.com/vuejs/vue-class-component so maybe that's why there is a difference​ in the guide and the result I'm getting

**Comment by LinusBorg** [comment]
That's not the point. It's totally correct that what you get is a Component Config object, because the whole exercise is meant to get async data *before* the app is rendered (and consequently, before the component instances are created).

The difference is that the guide shows how to do that with Vuex, while you try to do that for local state.

I haven't actually attempted this, but think you have a rocky road ahead. 

The problem isn't so much getting the async data into the local state on the server - I think that can be done.

The problem is that you have to send that state to the client *inside of the HTML page* somehow, and make the component read that information into its local state on the client again synchronously.

Otherwise, the received DOM from the server will not match the virtualDOM rendered ion the client, and hydration will fail.

Thhat's why the guide I linked to explains how to extract your state into a central Vuex store -  taking care of all async state through Vuex makes that whole exercise much easier.

**Comment by caleblloyd** [comment]
I've figured all of that other stuff out.  The only problem I'm having is I can't get a reference from the `beforeRouteEnter` function back to the Component Instance or Application Instance before server side rendering completes.

I've tried many things:

1. `next(vm: Vue)` resolves after server side rendering completes, so that cannot be used
2. The example on the [SSR page](https://ssr.vuejs.org/en/data.html) returns a Component Config object with no way to get to the Component Instance or Applicaiton Instance
3. The `to: Route` parameter in `beforeRouteEnter` does not hold a reference back to it's router, so even if I save a reference to the Application in the router, I can't get back to that object

**Comment by LinusBorg** [comment]
Question: Is there a particular reason that you don't want to use Vuex?

Idea: Replace the Component Option's data fuction with one that refers to the async result via a closure ...

**Comment by caleblloyd** [comment]
The issue is much more fundamental than this.  Regardless of whether I use Vuex or not, I cannot access the Application Instance or the Component Instance before Server Side Rendering has completed, so there is no way to put the data into Vuex or some other variable associated with the Application/Component before Server Side Rendering has completed.

Maybe this will help:

```
beforeRouteEnter completes in Component's Module
no way to reach Component Instance (this is expected, it has not been instantiated)
no way to reach Application Instance since Component and Application are in separate modules
             ↓
router.OnReady fires in Application's Module
all matched components are still Configurations
no way to call a method on a component; they have not been instantiated
             ↓
Server Side Rendering completes
             ↓
beforeRouteEnter callback next(vm: Vue) is called
finally have access to Component Instance
can access Application Instance through component.$root
too late because Server Side Rendering has already completed
```

**Comment by LinusBorg** [comment]
> Regardless of whether I use Vuex or not, I cannot access the Application Instance or the Component Instance before Server Side Rendering has completed, so there is no way to put the data into Vuex or some other variable associated with the Application/Component before Server Side Rendering has completed.

Now I'm confused. 

The whole point of vuex is that the data does not have to be added to the component's local state, but the component fetches what it needs from the vuex store. We don't *need* to access the component instance.

That's what's being described in the link that I provided and that you said you already read, and that's what you can see in action in the vue-hackernews demo project.

So I really don't understand why you would feel that you have to access the component instance. What *exactly* is not working for you with the vuex approach described in out documentation that makes you think you need access to the component instance?

**Comment by caleblloyd** [comment]
I can't access the application instance either, so I can't load any data from `beforeRouteEnter` into Vuex. I know other projects like Vue Hackernews do. I haven't  read  the source for that  but I'll  take  a look. In my project the vue component is in a different module than the application, so maybe that's the difference.

I think it's important for Vue Router to provide a way to access the Component Instance, which will in turn allow access to the $root application instance before server side rendering completes. It allows for powerful code design patterns such as isomorphic MVC.

**Comment by LinusBorg** [comment]
> I can't access the application instance either, so I can't load any data from `beforeRouteEnter` into Vuex. 

I'll ask a third time: Why would you think you need to use this way?

> I think it's important for Vue Router to provide a way to access the Component Instance, which will in turn allow access to the $root application instance before server side rendering completes. 

This would require for server-side rendering to evaluate the application render process asynchonously, which would be much less efficient, and make streaming the result impossible, so that probably won't happen.

> It allows for powerful code design patterns such as isomorphic MVC.

I don't understand this one. Vue doesn't have a contcept of a controller to begin with, and using MVC on the client is largely considered to be an antipattern - even Ember is dropping it.

**Comment by caleblloyd** [comment]
> I'll ask a third time: Why would you think you need to use this way?

Here is the scenario.  `beforeRouteEnter` gets called in a separate module.  [Here is the code](https://github.com/caleblloyd/dotnet-core-boilerplate/blob/61a4d4420757e1f2445d95fe02e97f5cbfcc153f/ui/src/controllers/PostsController.ts).  This data needs to get saved somewhere and eventually needs to end up back in the Component.

The `next` callback resolves after Server Side Rendering completes, so the data cannot be associated with the component in the `next` callback.  I am proposing that the `next` callback get called earlier, before server side rendering is complete.

> This would require for server-side rendering to evaluate the application render process asynchonously, which would be much less efficient, and make streaming the result impossible, so that probably won't happen.

I'm aware that access to the Application or Component cannot happen in `beforeRouteEnter`.  That's why it would be great if the `next` callback worked before Server Side Rendering completed.

> I don't understand this one. Vue doesn't have a contcept of a controller to begin with, and using MVC on the client is largely considered to be an antipattern - even Ember is dropping it.

In my case I am considering a `Controller` to be a component that is routed to.

If you have the time, it'd be great to review my project and process.  I think it'll make the problem with getting Server Side Rendering data mapped in a routed component much clearer.  Here's the main files:

- [New Application](https://github.com/caleblloyd/dotnet-core-boilerplate/blob/61a4d4420757e1f2445d95fe02e97f5cbfcc153f/ui/src/dotvue/DotvueApp.ts)
- [Routes](https://github.com/caleblloyd/dotnet-core-boilerplate/blob/61a4d4420757e1f2445d95fe02e97f5cbfcc153f/ui/src/config/Routes.ts)
- [Components that are loaded by Router](https://github.com/caleblloyd/dotnet-core-boilerplate/blob/61a4d4420757e1f2445d95fe02e97f5cbfcc153f/ui/src/controllers/PostsController.ts) (I call these Controllers)
- [Server Side Renderer](https://github.com/caleblloyd/dotnet-core-boilerplate/blob/61a4d4420757e1f2445d95fe02e97f5cbfcc153f/ui/server.ts)

As you'll see, there is no easy way to get the data from`beforeRouteEnter` into the Components in `PostController.ts`.  I'm open to any solution, but I've scoured documentation and code and have been unable to find an obvious one.

**Comment by LinusBorg** [comment]
> I'm aware that access to the Application or Component cannot happen in `beforeRouteEnter`. That's why it would be great if the next callback worked before Server Side Rendering completed.

As I explained, that would require an asynchronous  rendering process, which, in all likelihood, will not happen.

Skimming over your code as best I can (not a typescript-user - yet), I don't see anything that could not be solved with vuex-centic patterns explained in the documentation. Please review the SSR documentation as well as the hackernews demo.

Instead of loading posts in the beforeRouteEnter, you would add an `asyncData` hook, dispatch an action in that hook to get the data, and only rtender the whole app afer all those hooks have been resolved.

Then each route component ("controller") can get ita data synchronously from the store, so the whole app can be rendered synchonously and streamed to the client.

**Comment by caleblloyd** [comment]
> Instead of loading posts in the beforeRouteEnter, you would add an asyncData hook, dispatch an action in that hook to get the data, and only rtender the whole app afer all those hooks have been resolved.

Unfortunately this just doesn't work with TypeScript.  Components are classes, not objects.  So even though I add a `asyncData` method to my component, here's what I get:

```
router.onReady(async () => {
                const matchedComponents = router.getMatchedComponents()
                if (!matchedComponents.length) {
                    reject({ code: 404 })
                }

                matchedComponents.map(Component => {
                    console.log(Component)
                    if ((Component as any).asyncData) {
                        (Component as any).asyncData()
                    }
                })

                resolve()
            })
```

Logs:

```
function VueComponent(options) {
      this._init(options);
}
```

There is no access to the `asyncData` method of the component in `router.onReady`

**Comment by caleblloyd** [comment]
Here is a solution that may work.  What if we add a navigation property from `Route` back to the `Router` that instantiated it?

Presently in `beforeRouteEnter`, `to` holds the `Route` that we are navigating to.  If I could call `to.Router`, I could save a reference to the VueX store in the `Router`.  So I could save the data into VueX by calling `to.Router.Store` or something like that.

**Comment by LinusBorg** [comment]
> Unfortunately this just doesn't work with TypeScript. Components are classes, not objects. 

Yes and no. It seems you have your own decorators to map the class methods etc into a  `Vue.extend()`? `vue-class-component` does somethign similar. In any way, the result is an extended Vue instance with the component options as defaults.

> There is no access to the asyncData method of the component in router.onReady

The options of a Vue constructor *are* accessible via `Constructor.options`:

https://jsfiddle.net/Linusborg/uwtsL71r/

So nothing's keeping your from following the pattern described in the docs.

>  If I could call to.Router, I could save a reference to the VueX store in the Router. So I could save the data into VueX by calling to.Router.Store or something like that.

That would not help you, as it would still rely on `beforeRouteEnter` executing an async operation, which would happen after the app has started up but we have to do all of this *before* it starts so that the first render is synchronous and can be streamed.

**Comment by caleblloyd** [comment]
> The options of a Vue constructor are accessible via Constructor.options

Wow, I was totally unaware.  I will use this approach.

Also, thanks for sharing all of the design aspects of `vue-router` and why they make `beforeRouteEnter` a bad choice for async app data in Server Side Rendering.  It was unclear to me at first why you wouldn't want to do this, but I've learned a lot in this thread 😄
