### ISSUE TITLE
Pass down route props to $attrs

### ISSUE THREAD

**Issue by posva** [vuejs/vue-router#1695]
### Version
2.7.0

### Reproduction link
[https://www.webpackbin.com/bins/-Ks8plb2Lsqpt8Po3Rxg](https://www.webpackbin.com/bins/-Ks8plb2Lsqpt8Po3Rxg)

### Steps to reproduce
Click on the different links

### What is expected?
Passing props in the route object:

```js
{ path: '/', component: Hello, props: { name: 'world' }},
```

should appear in `$attrs` as long as `name` is not declared as a prop in `Hello.vue`

### What is actually happening?
no prop

---
moved from https://github.com/vuejs/vue/issues/6426

**Comment by posva** [comment]
I haven't dived in already but it may be at this line: https://github.com/vuejs/vue-router/blob/dev/src/components/view.js#L71

**Comment by lbogdan** [comment]
I did some debugging and found that the issue is in the `<router-view>` component: it takes the `params` in the route and sends them to the route component verbatim, in `props`, without checking if they are defined or not on the component (which was normal behavior before the introduction of `$attrs` in vue 2.4.0).
What it should do instead is passing the defined props in `props`, and the rest in `attrs`.
