### ISSUE TITLE
When a prop passed to router-view updates, the prop function of the route record is called again (but the route didn't change)

### ISSUE THREAD

**Issue by eqxs** [vuejs/vue-router#1707]
### Version
2.7.0

### Reproduction link
[https://jsfiddle.net/eQxs/xjcm1yf2/](https://jsfiddle.net/eQxs/xjcm1yf2/)

### Steps to reproduce
In the example, we have two components. From the parent to the child, two properties are passed ('person', 'message'). And also in the constructor 'VueRouter' the third property 'query' is passed using the 'props' function. 
When the property 'message' is changed in the parent component, the 'props' function of the 'VueRouter' constructor is executed for the child component. Because of this, the 'watch' function for the 'query' property is called in the child component. But at the same time, for the 'person' property, the 'watch' function is not executed.

You can see this in the example. Just go to the link 'Go to Foo' and wait two seconds

### What is expected?
the 'query' property should not be updated when the 'message' property is updated

### What is actually happening?
the 'query' property is updated when the 'message' property updated

**Comment by LinusBorg** [comment]
Techincally, that's expected. We have to call that props function on every re-render because something might have changed.

Since you return an object for the `query` prop, you always end up with a fresh object which fails the component's old/new value comparison and hence, triggers the watcher.

I don't think we can cache the result of the props function reliably, because we can't tell for sure during the re-render weither or not the props function would certainly return the same result.

This problem does not exist for props that use native plain types (String, Number etc ...), so your easy solution would be to make the `query` object's content available as individual props instead.

**Comment by aleksei-a-savitski** [comment]
@LinusBorg thanks for the explanation. 
As a work around we use a 'deep-equal' comparison of old and new values in property watcher. 
Do you know a reason to recalculate route props with each re-render? Docs say the function is "only evaluated on route changes" because it's stateless. So there is no obvious need to recalculate props on re-render.

**Comment by LinusBorg** [comment]
Well, the docs are a bit inaccurate regarding this. The function is re-evaluated whenever the `<router-view>` is updated - which *generally* only happens when the route atually changes.

I assume that the possibility of router-view updating because of a prop *on the` router-view`* being changed was not taken into account when this was written.

As to why it's evaluated evertime the `router-view` is updated: It's  functional component without state of its own, so that was the simplest thing to do, in particular if done under the assumption explained in my previous paragraph.

Now, caching the value is certaily achievable one way or another, we would have to look into that.

But right now, I'm not sure if this should be considered a bug or an improvement.

**Comment by aleksei-a-savitski** [comment]
It would be a nice feature. No need to reevaluate a function if its arguments didn't change.

There is a router-view cache in parent component may be it could be used. 
A tricky part could be understanding if a route or component props changed.

**Comment by garethellis36** [comment]
I've just spent 2-3 hours debugging a problem related to this same issue. I was not expecting router-view to be updated just because a prop changed in the child component, and it was causing me some real issues. I solved it by not returning a fresh object out of the props function. It would be really nice to implement the caching improvement mentioned above, and at the very least improve the documentation to make it clear that this is what happens. :)

**Comment by posva** [comment]
I changed to title to something more accurate. This will probably be a wont fix for current version of vue-router since router-view is a functional component and there is no way to create a computed property out of the currentRoute property. As @LinusBorg explained, a new object query is returned everytime, triggering the watcher everytime anything makes the router-view re render, in this case, the `message` prop
For your use case, watch directly the property you want inside of the query object `('query.page' (page) {/* your watcher code */ }`, or use the `$watch` method with a function as the first argument (Vue.js docs)
