### ISSUE TITLE
children route guard blocking parent render

### ISSUE THREAD

**Issue by zsobral** [vuejs/vue-router#1718]
### Version
2.7.0

### Reproduction link
[https://jsfiddle.net/p3zsdtfp/](https://jsfiddle.net/p3zsdtfp/)

### Steps to reproduce
On jsfiddle

* click on router-link to /users

when navigate from route A to route B with children route B1 and B1 has some delay inside beforeRouteEnter guard, route B component is not rendering until beforeRouteEnter guard from B1 has ended

### What is expected?
expecting beforeRouteEnter guard from children routes do not block parent rendering

### What is actually happening?
parent route component is only rendering after children route beforeRouteEnter next() call

**Comment by posva** [comment]
Unfortunately, that's working as expected because the child route is another path. Thus, navigating to it and waiting, will delay the rendering of both `router-view`s because the URL isn't changing until the call to `next` is made.
If you want to display the parent route, you may want to navigate first to the parent and then, go to users: https://jsfiddle.net/220oz3hv/

Otherwise, this would lead to weird situations like displaying the parent view for a moment and then navigating somewhere else if the user is not meant to be there
