### ISSUE TITLE
Vue-Router breaks when reloading page

### ISSUE THREAD

**Issue by Juli0GT** [vuejs/vue-router#1735]
### Version
2.7.0

### Reproduction link
[https://codepen.io/Juli0GT/pen/veEEpr](https://codepen.io/Juli0GT/pen/veEEpr)

### Steps to reproduce
Before reloading page thats my $route component:

$route:Object
fullPath:"/dashboard/customer-service?subnav=dashboard&activeClass=active"
meta:Object (empty)
name:“csDashboard"
params:Object (empty)
path:”/dashboard/customer-service"
query:Object

### What is expected?
Having same $route component after reload

### What is actually happening?
If I refresh the page my router doesn’t recognise anymore my route, and my $route object looks like this:

$route:Object
fullPath:"/“
meta:Object (empty)
params:Object (empty)
path:”/"
query:Object (empty)

**Comment by morficus** [comment]
when you reload the page and lose your router object... what is the URL in your browser?
is it still `/dashboard/customer-service` or is it just your base domain?

**Comment by posva** [comment]
Hi, thanks for your interest but Github issues are for bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/), [gitter](https://gitter.im/vuejs/vue) or [StackOverflow](http://stackoverflow.com/tags/vue.js).

**Comment by davidsielert** [comment]
I think this really is an issue, I've just encountered this as-well reloading a page from within a route redirects to the root path after page load.

**Comment by posva** [comment]
If it's an issue, please provide a boiled down repro

**Comment by MatteoGabriele** [comment]
@posva I actually have the same error and has been reported as a bug to my plugin [vue-analytics](https://github.com/MatteoGabriele/vue-analytics).

What I do is grabbing the route and automatically start tracking pages with Google Analytics, but when a component has been lazy loaded there's a moment when the `currentRoute` object has empty properties: like the one described in this ticket.

If you need some sort of reproduction you could check the one done in the issue reported to me (https://github.com/MatteoGabriele/vue-analytics/issues/149). The issue in vue-analytics is that I need a `name` property in the `currentRoute` when tracking, but the root route sometimes doesn't have it.

Let me know if it's all clear otherwise I'll try myself to create a better reproduction for here.

Thanks for your time

**Comment by posva** [comment]
Yeah, I would need a repro I can play with (jsfiddle, codesandbox) without vue-analytics. Thanks 🙂

**Comment by MatteoGabriele** [comment]
@posva I've crated a codesanbox for you https://codesandbox.io/s/742n0wow51

in the `router.js` file there are two kinds of imports: one with lazy loading and a normal one.

The one with lazy loading will render in the html an "empty" route object with no name etc..

the second one will render a route object with a name property as is expected.

Thanks a lot for your time and I hope will be enough otherwise I'll try something else

**Comment by posva** [comment]
@MatteoGabriele I think you shared the wrong codesandbox

**Comment by MatteoGabriele** [comment]
@posva Did I?

**Comment by posva** [comment]
it renders the route before navigation. keep in mind $route is not serializable and therefore cannot be displayed inside HTML as well

**Comment by MatteoGabriele** [comment]
but well the point tho is that for a "second" the $route object is empty, compared to the not lazy loaded and it is visible in this example.

I hoped that the concept was clear but I can think about something else even tho the main point is that the route on lazy loading has null values on the start and it breaks code that reads those values.

**Comment by NoraGithub** [comment]
@posva  would you please answer the question of @MatteoGabriele  ?

**Comment by posva** [comment]
mmh, but the route is empty while we wait for the component because navigation is completed once the component is fetched, and that's also when the `$route` object is updated
what question?

**Comment by helariL** [comment]
I had the same issue. On hard reload $route is empty on initial mount but being updated later on. Quick workaround was to set $route as a computed property and just watch the computed property change and based on that update necessary data in my component.

**Comment by Naveen95** [comment]
you can do this. Add this line to the route file

Route::get('/{vue_capture?}', function () { return view('welcome'); })->where('vue_capture', '[\/\w\.-]*');

**Comment by chaijinsong** [comment]
> I think this really is an issue, I've just encountered this as-well reloading a page from within a route redirects to the root path after page load.

Is this problem solved? How did it work out? please

**Comment by Sakthi002** [comment]
i am facing the same problem.... how to resolve this.. help me

**Comment by Sakthi002** [comment]
https://drive.google.com/file/d/1sft5EsESSWJxG-PGhKhDeazY1V9PpMXU/view

**Comment by sohailkhann05** [comment]
I am facing same issue did you solve?

**Comment by ghost** [comment]
Is there an update to this issue? I am facing the same problem.

**Comment by StrangeWill** [comment]
Same problem here, seems to be some sort of race condition, I can hit the same link and like 20% of the time `this.$route.name` returns `null`, which obviously causes some issues when the app is supposed to preserve the route under some conditions for specific routes.

**Comment by theorange7** [comment]
I have a similar case happening. Posted here with some code https://stackoverflow.com/questions/56382623/vue-router-does-not-stay-on-same-page-after-a-page-refresh?noredirect=1#comment99367061_56382623

I have a `/user/:uid` route that shows a list of itinerary for a given user. Using router-link I'll route users to the detailed itinerary view which is on route `/itinerary/:itnerary_id`. Once I'm there, if I do a page refresh/f5/reload, I'll get routed back to the `/user/:uid` (browser address bar shows this). Checking vue-devtools, the router section does not show a "navigation" but shows `/user/:uid`.

**Comment by ankush981** [comment]
@theorange7 Same problem here! Been struggling with it for a long time!

**Comment by mpbarlow** [comment]
I'm also running into the same issue. If I try to query anything about the current route during a created/mounted hook, I get empty route objects if the component specified in the route is dynamically imported. This happens regardless of which descendent component I attempt to access this.$router from (i.e. it can be five levels of statically imported components down from the dynamically imported page component, and will still happen).

If I use a statically imported component for the page, the issue goes away. If I wait for an arbitrary amount of time (500-1000ms) with something like setTimeout, it (mostly) goes away. Neither of these is a particularly workable solution though.

**Comment by rognstad** [comment]
I'm experiencing this as well on routes with lazy-loaded components. It seems likes since all the routes and their paths are defined ahead of time, it ought to be possible for $route.name to resolve to the correct route immediately.

I was able to use this to work around the problem in my app:

```
watch: {
  $route(to, from) {
    if (to.name && from.name === null) {
      // do stuff
    }
  }
}
```

**Comment by lokielse** [comment]
After adding a `name` prop to route, It works for me.
```js
 {path: '/store', component: Store, meta: {title: 'Store'}},
 {path: '/store', name: 'store', component: Store, meta: {title: 'Store'}},
```

> P.S. I use [vue-navigation](https://github.com/zack24q/vue-navigation) with vue-router together

**Comment by mpbarlow** [comment]
Not sure if this will solve other people's issues but I just wrapped the code that was checking the current route in a call to [this.$router.onReady()](https://router.vuejs.org/api/#router-onready).

So, for example something like:
```
export default {
  ...,
  created () {
    this.$router.onReady(() => {
      if (this.$route.name === 'whatever') {
        this.doAThing()
      }
    }
  }
}
```

This will give a chance for async components to resolve and everything to get in order...I probably should have read the documentation more closely as it's all quite clearly explained 😅

**Comment by xxRockOnxx** [comment]
didn't know vue-router has a hook, that's awesome!
`onReady` seems to be the best place to do things that relies on route/url stuff. thanks @mpbarlow for mentioning it

**Comment by otabekoff** [comment]
Doesn't it worked yet? When we'll be able to get id even page is refreshed?

**Comment by guizoxxv** [comment]
After reloading the page from any path defined in the router, if I tried to access `this.$route` inside the `mounted` hook of the component, if returned `path: /` and `name: undefined`. With a computed property I was able to get the current route `path` and `name` correctly.

```js
computed: {
  routeName() {
    return this.$route.name;
  },
},
```

**Comment by WilliamLAS** [comment]
Welp after some hours i found a solution. And its fixing this issue by using Hash Mode in Vue Router without any other things.

Vue router got different modes for history saving. One of them is Hash mode. 
At your **index.js** in router folder,

```
import { createRouter, createWebHashHistory } from "vue-router";
import { publicPath } from '../../vue.config'
/*...*/
const router = createRouter({
  history: createWebHashHistory(),
  base: publicPath,
};
```

Other modes are well listed in here: https://router.vuejs.org/guide/essentials/history-mode.html
Shorty, 

- **Hash mode(createWebHashHistory):** 
It uses a hash character (#) before the actual URL that is internally passed. Because this section of the URL is never sent to the server, it doesn't require any special treatment on the server level. **It does however have a bad impact in SEO. If that's a concern for you, use the HTML5 history mode.**

- **HTML5 mode(createWebHistory):** 
When using createWebHistory(), the URL will look "normal," e.g. https://example.com/user/id. Beautiful!
Here comes a problem, though: Since our app is a single page client side app, without a proper server configuration, **#` the users will get a 404 error if they access https://example.com/user/id directly in their browser. Now that's ugly.`**
Not to worry: To fix the issue, all you need to do is add a simple catch-all fallback route to your server. If the URL doesn't match any static assets, it should serve the same index.html page that your app lives in. Beautiful, again! **but it wont work in github LOL**

- **Memory mode(createMemoryHistory)**
The memory history mode doesn't assume a browser environment and therefore doesn't interact with the URL nor automatically triggers the initial navigation. This makes it perfect for Node environment and SSR. It is created with createMemoryHistory() and requires you to push the initial navigation after calling app.use(router).
While it's not recommended, you can use this mode inside Browser applications but note there will be no history, **_`meaning you won't be able to go back or forward.`_**

**Comment by svinosvin** [comment]
Route::get('/{pathName?}', function(){
    return view('main');
})->where('pathName', ".*");
