### ISSUE TITLE
How to build routes params dynamic from api?

### ISSUE THREAD

**Issue by kwronski** [vuejs/vue-router#175]
Hi,

I need to build routes params dynamically - before vue app start i want to make a call to rest api and retrieve route table.
In previous version of vue-router there was possibility to set component as string:
```javascript
'/foo': { component: 'contact-component' }
```
so my api could return some json to set router:
```javascript
router.map(jsonData)
```

In current version it is not supported.
How can i set router using dynamic data from api ?

**Comment by yyx990803** [comment]
For now you'll need to create an id-component map object, then walk the configuration and convert these strings to actual objects. It's a bit of work but not that complicated.

I'll consider support string ids for global components.

**Comment by neronmoon** [comment]
Hi, 

@yyx990803 Can u provide simple example?

**Comment by LinusBorg** [comment]
Thank your for your interest in this project.

However, your issue is a usage/support question, and the issue tracker is reserved exclusively for bug reports and feature requests (as outlined in our [Contributing Guide](https://github.com/vuejs/vue/blob/dev/.github/CONTRIBUTING.md)).

We encourage you to ask it on the [forum ](http://forum.vuejs.org) , [Stack Overflow](http://stackoverflow.com/questions/tagged/vue.js) or on [gitter](http://gitter.im/vuejs/vue) and are happy to help you out there.

**Comment by posva** [comment]
The issue was for 0.7 anyway. As @LinusBorg you should ask it in the forums and give details about your use case. Using `addRoutes` may be enough for you: https://github.com/vuejs/vue-router/releases/tag/v2.2.0
