### ISSUE TITLE
Navigating between child routes causes parent route to re-render

### ISSUE THREAD

**Issue by viktorhunko** [vuejs/vue-router#1838]
### Version
3.0.1

### Reproduction link
[http://jsfiddle.net/yyx990803/L7hscd8h/](http://jsfiddle.net/yyx990803/L7hscd8h/)

### Steps to reproduce
Hi there!

In my app i have multiple nested routes:
```
- root
-- groups
--- all
--- group-details
---- group-posts
---- group-events
---- group-members
```
etc.
Based on this example: http://jsfiddle.net/yyx990803/L7hscd8h/ in my case `User` component re-rendered when i'm navigating between child routes

### What is expected?
when i'm navigating between child routes parent should't be re-rendered

### What is actually happening?
When i'm navigating between, let's say, `group-posts` and `group-events` parent route `group-details` also re-render.

**Comment by LinusBorg** [comment]
This is expected behaviour because `<router-view>` is a functional component which will make the parent re-render whenever one of its dependencies (i.e.: $route from the parent) will change.

If you don't want this because your `User` component has quite expensive renders, wrap router-view in a small child component.

**Comment by viktorhunko** [comment]
@LinusBorg thanks for quick reply!
> If you don't want this because your User component has quite expensive renders, wrap router-view in a small child component.

Didn't get what you mean by that. 
My parent component looks like:
```
<div class="User__main-container">
    <user-header></user-header>
    <router-view name="userContent"></router-view>
</div>
```

and as you said user-header is quite expensive renders, so i don't wanna reload it, but wanna reload only components in 'userContent' router-view
If you mean that i can wrap 'userContent' router-view, so my parent component will be: 
```
<div class="User__main-container">
    <user-header></user-header>
    <user-content></user-content>
 </div>
```
And `user-conent` component:
```
<div class="User__content">
    The truth is out there
      <router-view name="userContent"></router-view>
</div>
```
Tried, but my `user-header` is still re-rendered when i'm navigating between child routes

**Comment by LinusBorg** [comment]
Check this out: http://jsfiddle.net/atut5kpg/1/

The `updated()` hook never logs, because the router-view is wrapped in a "real" component, and the User component itself does not depend on any data from the router, since I removed the ``$router.params.id` call from the template.

So in this situation, my proposed fix works. My suspicion is that your parent component still depends on data from the router, i.e. anything from `$route` somewhere (in a computed prop or something, maybe?), which triggers the re-render.

Sidenote: `$route` is immutable, so it is replaced with a new object on every navigation. All components that use it will re-render, even if their route path is the same (query could have changed etc.)

You can use [props](https://router.vuejs.org/en/essentials/passing-props.html) instead of $route to optimize that. Also better for unit testing those components:

http://jsfiddle.net/atut5kpg/2/

**Comment by viktorhunko** [comment]
@LinusBorg you're totally right! my parent component depend on `$route` params (loads data using id param). Parent component stops to re-render once i removed this dependency.
Thanks a lot!
