### ISSUE TITLE
[feature] Is there any way to judge addRoutes oncomplete ？

### ISSUE THREAD

**Issue by PanJiaChen** [vuejs/vue-router#1926]
### What problem does this feature solve?
when use `router.addRoutes`  l have no idea about whether it is completed or not
like:
```js
router.beforeEach((to, from, next) => {
  ... 
  //once login
   router.addRoutes(routers)
  ...
})
```
l must ensure router.addRoutes is completed then l can `next()` move on to next hook ,  otherwise l will get a blank page, because the page is not ready.

### What does the proposed API look like?
maybe return a promise is better like this
```js
 router.addRoutes(routers).then(()=>{
  //do some thing
})
```

**Comment by posva** [comment]
routes are added synchronously, there is nothing to wait for. On a side note, adding routes that way doesn't add any extra security if that's what you're searching for. It's better to add them upfront and implement the corresponding guards to have a nice user experience.

---

Please, next time consider using the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js) for questions first. But feel free to come back and open an issue if it turns out to be a bug 🙂

**Comment by reuwi** [comment]
@posva I came cross the same problem, But as you said "routes are added synchronously", blew codes won't work:
`
router.addRoutes(excessRoutes)
            next()
`
I have to use next(to) ro reenter the router guards
