### ISSUE TITLE
页面返回时不触发组件的destroyed

### ISSUE THREAD

**Issue by fangsj** [vuejs/vue-router#1930]
### Version
3.0.1

### Reproduction link
[http://weixin.chinayltx.com](http://weixin.chinayltx.com)

### Steps to reproduce
有3个页面：Home>Page1>Page2，在支付宝浏览器（UC技术支持）里，第一次按照页面顺序进入，再返回没有问题，第二次再按顺序进入然后点击一次”返回键“返回Page2不触发“destroyed”，当再点击一次“返回键”才会触发“destroyed”，这时页面已经返回到首页了，并没有进入到Page1

### What is expected?
第二次按Home>Page1>Page2进入后返回，第一次按“返回键”就应该触发“destroyed”

### What is actually happening?
第二次按Home>Page1>Page2进入后返回，点击2次“返回键”才触发Page2的“destroyed”，页面已经返回到Home

---
因为我的业务代码可能比较复杂，我的提供一下网站地址为：http://weixin.chinayltx.com。后面如果有必要我提供一下代码重现

**Comment by fangsj** [comment]
对了我使用的android机型，支付宝内的浏览器貌似使用的是UC浏览器的技术支持

**Comment by posva** [comment]
Hi, thanks for your interest but Github issues are for bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/), [gitter](https://gitter.im/vuejs/vue) or [StackOverflow](http://stackoverflow.com/tags/vue.js). If it turns out to be a bug, come back and open an issue with a proper repro 🙂
