### ISSUE TITLE
微信中右上角游览器打开

### ISSUE THREAD

**Issue by zoro-r** [vuejs/vue-router#1940]
### Version
3.0.1

### Reproduction link
[https://jdfdcc.github.io/vue-mobile-mint/index.html#/baseHome](https://jdfdcc.github.io/vue-mobile-mint/index.html#/baseHome)

### Steps to reproduce
在IOS微信中打开点击推荐商品列表进入商品详情页面然后点击右上角在safary中打开

### What is expected?
应该打开商品详情页

### What is actually happening?
打开的依然是商品列表页面

**Comment by posva** [comment]
Sorry, but that's not a valid reproduction

Please, next time consider using the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js) for questions first. But feel free to come back and open an issue if it turns out to be a bug 🙂

**Comment by zoro-r** [comment]
Thank you!!

**Comment by inmWang** [comment]
@jdfdcc  请问你这个问题解决了吗？
