### ISSUE TITLE
Why not redirect automatically but add a extra param manually in the last redirec?

### ISSUE THREAD

**Issue by wangyi7099** [vuejs/vue-router#1942]
### What problem does this feature solve?
At , [#1938](https://github.com/vuejs/vue-router/issues/1938) ,I said the router can't redirect to the page I want . and @posva  said I should add a param in the last redirect as well. I tried it , and succeed But I want to say , I  did assign the params "bigCata" in the pre redirect , why not redirect automatically but add a extra param manually in the last redirect?

### What does the proposed API look like?
Automatically redirect to the page I want.

**Comment by wangyi7099** [comment]
I'm sorry, I lost a 't' in the ending of the tittle...

**Comment by posva** [comment]
If params were added implicitly that would be difficult to reason about and would have to be removed most of the time.

Please, next time consider using the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js) for questions first. But feel free to come back and open an issue if it turns out to be a bug 🙂
