### ISSUE TITLE
微信路由切换url哈希值不正确

### ISSUE THREAD

**Issue by zoutong123** [vuejs/vue-router#1949]
### Version
2.5.3

### Reproduction link
[http://app.whipo.net/Html/webSignUp/index.html](http://app.whipo.net/Html/webSignUp/index.html)

### Steps to reproduce
微信中路由可以正常切换，但是通过复制链接发现实际上的URL是不包含哈希值的，这样一来在微信中选择“在浏览器中打开”，打开的实际上是入口页面。

### What is expected?
在浏览器中打开正确的子页面#/agreement

### What is actually happening?
实际上还是入口页面#/

**Comment by posva** [comment]
Sorry but that's not a valid repro
Please, next time consider using the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js) for questions first. But feel free to come back and open an issue if it turns out to be a bug 🙂
