### ISSUE TITLE
How Do I Watch The Routes Added By Method addroutes() ?

### ISSUE THREAD

**Issue by xiaoweijiayou** [vuejs/vue-router#1955]
### What problem does this feature solve?
when l add routes by addRoutes , I can not watch them by $router.options.routes, so where can I
get their value? Thank you for answer!

### What does the proposed API look like?
It is simple but convenient！

**Comment by posva** [comment]
You don't need to need to watch them as they never change.
Since you know when you add routes you can plug in your code there

Please, next time consider using the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js) for questions first. But feel free to come back and open an issue if it turns out to be a bug 🙂

**Comment by fayt81** [comment]
Hi @posva, it looks like you are closing all the different issues related to this problem. Possibly, it is due to the formulation of the issue. I think that the issue should be reformulated as a feature request because we need a convenient way to get all the routes (both those passed as options and those added at runtime with addRoutes API). At present, to verify if there is a particular route, I have to keep an array of my added routes in the store (and eventually merge it with the one in options). Since the information about all the routes is already present somewhere (because it is used by the router), I think that many of us just would like a convenient API to get it.

**Comment by josx** [comment]
I think that the router needs to handle all the routes, including the addRoutes routes. 
It is ugly to mantain a separated structure to keep this type of routes.
