### ISSUE TITLE
Programmatic navigation to the same named component with different params does not work

### ISSUE THREAD

**Issue by ardoramor** [vuejs/vue-router#1964]
### Version
2.7.0

### Reproduction link
[https://jsfiddle.net/L7hscd8h/3388/](https://jsfiddle.net/L7hscd8h/3388/)

### Steps to reproduce
After fiddle is executed, note the initial output, click `foo`, click `bar`

### What is expected?
Initially, the executed fiddle will print the following:

```
clicks: 0
foo
bar
```

Clicking `foo`, the output will update to:

```
clicks: 1
foo
bar

name = 'foo'
$route.params.name = 'foo'
changeCount = 0
```

Clicking `bar`, only the `clicks` will be updated:

```
clicks: 2
foo
bar

name = 'bar'
$route.params.name = 'bar'
changeCount = 1
```

### What is actually happening?
Initially, the executed fiddle will print the following:

```
clicks: 0
foo
bar
```

Clicking `foo`, the output will update to:

```
clicks: 1
foo
bar

name = 'foo'
$route.params.name = 'foo'
changeCount = 0
```

Clicking `bar`, only the `clicks` will be updated:

```
clicks: 2
foo
bar

name = 'foo'
$route.params.name = 'foo'
changeCount = 0
```

---
It seems that programmatic navigation to the same component with different params does not trigger guard or watcher on the route.

**Comment by posva** [comment]
There's no `name` param in your route `/detail`, it should be `/detail/:name`

Please, next time consider using the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js) for questions first. But feel free to come back and open an issue if it turns out to be a bug 🙂
