### ISSUE TITLE
"'0' is not a valid attribute name" when navigating to a wildcard route with "props: true"

### ISSUE THREAD

**Issue by KaelWD** [vuejs/vue-router#1994]
### Version
3.0.1

### Reproduction link
[https://codesandbox.io/s/oo6x710k39](https://codesandbox.io/s/oo6x710k39)

### Steps to reproduce
 - click 'foo'
 - click 'bar'
 - observe the error
 - click 'home'
 - note that the page title no longer updates

### What is expected?
Either give a console warning, or silently ignore the numeric props

### What is actually happening?
The following error is thrown, breaking the whole page
![image](https://user-images.githubusercontent.com/16421948/34916630-896d7062-f98f-11e7-8e1e-1495d8493605.png)

---
In the actual app everything is wrapped in another dynamic route, which is what has `props: true`

**Comment by posva** [comment]
It looks like the regex generated adds a param named `0`, and therefore vue-router tries to pass that as a prop, but since there's no prop named 0, it passes it as an attribute. Resulting on the error you see. A workaround would be using a function for props and manually stripping that off. I'm currently on a fix for this
