### ISSUE TITLE
Props for named views are not passed from router to named component

### ISSUE THREAD

**Issue by rmuchall** [vuejs/vue-router#2007]
### Version
3.0.1

### Reproduction link
[https://codepen.io/rmuchall/pen/NXEjWb](https://codepen.io/rmuchall/pen/NXEjWb)

### Steps to reproduce
Click on "Foo Link 1" and "Foo Link 2"

### What is expected?
The values of the props should be displayed:
propA: dynamicValueA
propB: dynamicValueB

### What is actually happening?
The query string parameters are not passed as props to the named view Vue component

**Comment by rmuchall** [comment]
Function mode appears to work correctly e.g.
```
props: {
  content: myFunc // Working
}
```

Boolean mode appears broken
```
props: {
  content: true // Broken
}
```

**Comment by posva** [comment]
If you use `props: true` the params are passed as props, so `<router-link to="/foo/dynamicValueA/dynamicValueB">Foo Link 1</router-link>` would render the result you want with the following path `/foo/:propA/:propB`. You were using a query to pass information

Please, next time consider using the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js) for questions first. But feel free to come back and open an issue if it turns out to be a bug 🙂

**Comment by rmuchall** [comment]
Many thanks for your swift response. My apologies for the inconvenience.
May I ask - Is there any method whereby query params can be automatically passed down as component props similar to the boolean mode for params?
Or is the best practice solution to use function mode e.g.
```
props: {
  content: myFunc
}
```

**Comment by posva** [comment]
no, there is not, you need to use a function for that
