### ISSUE TITLE
How to get path from route instance?

### ISSUE THREAD

**Issue by zjxpcyc** [vuejs/vue-router#2045]
### What problem does this feature solve?

Route config
```javascript
{ path: '/user/:id', component: User }
```

i change param someplace

```javascript
this.$route.params({ id: 'foo' });
```

in hash mode, i can get path  ```  /#/user/foo ```
in history mode, get ```  /user/foo ```

### What does the proposed API look like?
```javascript
this.$route.toPath()
```

**Comment by LinusBorg** [comment]
Hello @zjxpcyc 

Thank your for your interest in this project.

However, your issue is a usage/support question, and the issue tracker is reserved exclusively for bug reports and feature requests (as outlined in our [Contributing Guide](https://github.com/vuejs/vue/blob/dev/.github/CONTRIBUTING.md)).

We encourage you to ask it on the [forum ](http://forum.vuejs.org) , [Stack Overflow](http://stackoverflow.com/questions/tagged/vue.js) or on our [Discord chat](http://chat.vuejs.org) and are happy to help you out there.
