### ISSUE TITLE
Setting custom fallback for each route group

### ISSUE THREAD

**Issue by Quadriphobs1** [vuejs/vue-router#2046]
### What problem does this feature solve?
Is it possible to set a custom fallback(404 error page) to separate route group which will be different from the global 404 of the vue-router, If it is please how can I achieve this I am trying to build something like that?

### What does the proposed API look like?
I have used something like that in laravel which server as a fallback if the requested route is not found within a certain route group for example if i am the route group like setting, it might have account setting, image setting, so if for example there is an error, easily it can display like a custom 404 page for that route group

```
Route::fallback(function(){
    return 'whatever you want to show';
});
```

**Comment by posva** [comment]
You can use the `*` path for that or if you really need something very specific, a `beforeEach`

---

Please, next time consider using the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js) for questions first. But feel free to come back and open an issue if it turns out to be a bug or a feature request others may also be interested in 🙂
