### ISSUE TITLE
`beforeRouteLeave` invoked twice when redirecting inside of beforeRouteEnter

### ISSUE THREAD

**Issue by gzzhanghao** [vuejs/vue-router#2102]
### Version
3.0.0

### Reproduction link
[https://jsfiddle.net/Jason_Daurus/vv79u55j/](https://jsfiddle.net/Jason_Daurus/vv79u55j/)

### Steps to reproduce
Click at "link-b" in the fiddle, you'll have "A:beforeRouteLeave" logged twice in browser's console.

### What is expected?
A:beforeRouteLeave should not be invoked after B:beforeRouteEnter

### What is actually happening?
it does :-(

**Comment by cxyao** [comment]
I meet the same issue.
I'm using redirect to fixed the twice invoke.
I think it's a bug of VueRoute
If you are chinese, i hope this link will be helpful https://www.cnblogs.com/Amar/p/9154452.html

**Comment by posva** [comment]
I'm taking a second look at this, the problem is that when we redirect we are triggering a new navigation, so it makes sense to invoke the guard once again with a different `to` parameter.
What I think would help here is being able to know if the navigation is a redirection to bypass the guard which you can follow at #1822
