### ISSUE TITLE
Web browser back button doesn't go back to scroll position when content is created with beforeRouteEnter.

### ISSUE THREAD

**Issue by ambrt** [vuejs/vue-router#2138]
### Version
3.0.1

### Reproduction link
[https://jsfiddle.net/qjrf9zyu/15/](https://jsfiddle.net/qjrf9zyu/15/)

### Steps to reproduce
Wait for page to load.<br>
Scroll to bottom.<br>
Click about.<br>
Right click menu->Back or browser Back.<br>

### What is expected?
The browser window should scroll to bottom (last position)

### What is actually happening?
Browser scrolls to top.

**Comment by ambrt** [comment]
In the fiddle above the
`setTimeout(function(){next(vm => {vm.gray = true}) }, 1000);` simulates call to REST server.

**Comment by posva** [comment]
This is because what you do inside of the next callback changes the size of the page and the scroll behaviour is, by default, triggered as soon as possible -> when the component renders. In your case, you will need to use the promise api for scrollBehaviour and connect both somehow (bus event, listeners + factory). The other (easier) solution is creating placeholders so the page has a larger height on first render.

In the future we may support returning a promise in the hooks so we know about waiting before triggering the scrollBehaviour method

Documenting patterns with scrollBehaviour is on the roadmap as we know it is difficult to understand at first

**Comment by ambrt** [comment]
Ok, thanks for reply. I made placeholders.

**Comment by steveDL** [comment]
Hey I have pretty much the same problem, I am getting the view components inside of beforeRouteEnter and as with the above issue the page has no height until the components load, my problem is compounded by the fact that I am also using lazy load, could you point me in the right direction of how I can utilise the scrollBehaviour promise to wait until the elements have loaded please

**Comment by steveDL** [comment]
ah I have found it actually thanks 

```
scrollBehavior (to, from, savedPosition) {
        return new Promise((resolve, reject) => {
          setTimeout(() => {
            if(savedPosition) {
                resolve(savedPosition)
            } else {
                resolve({ x: 0, y: 0 })
            }
          }, 500)
        })
      }
```

seems to work
