### ISSUE TITLE
<router-link target=“_blank”> 中params只能传递一个值？

### ISSUE THREAD

**Issue by LonHon** [vuejs/vue-router#2148]
### Version
3.0.1

### Reproduction link
[http://null.null.null](http://null.null.null)

### Steps to reproduce
```  javascript
// 不能获取startTime
<router-link :to="{ name: 'Detail', params: { uuid: scope.row.equipmentId, startTime: scope.row.createTime}}" target="_blank">

// 能够获取startTime
<router-link :to="{ name: 'Detail', params: { uuid: scope.row.equipmentId, startTime: scope.row.createTime}}">
```

### What is expected?
在target=“_blank”下，获取到 params 中的所有值

### What is actually happening?
在target=“_blank”下，只能获取params中部分值

---
现已通过query来获取到startTime，但是很好奇为什么会出现这种情况。

**Comment by posva** [comment]
This should rather be posted on the forums or the discord channel.
`target` is ignored by the link because it attaches a click listener and if you need to open in a new tab/window, you can simply use an anchor tag. That being said, it's something that may be added in the future (I think there is already an opened issue for that).
params must be on the `path` too
