### ISSUE TITLE
Creating query parameters with indexed arrays encodes array[] brackets incorrectly

### ISSUE THREAD

**Issue by jaketoolson** [vuejs/vue-router#2156]
### Version
3.0.1

### Reproduction link
[https://jsfiddle.net/zxnsmyz9/7/](https://jsfiddle.net/zxnsmyz9/7/)

### Steps to reproduce
```
let data = {
  'filter[galaxy_id]': '1,2,3',
  'filter[name]': 'abc',
  'filter[amenities]': '4,5,6'
};
```
```this.$router.push({to: '/', query: data});```

### What is expected?
http://travelr.local?filter[galaxy_id]=1,2,3&filter[name]=abc&filter[amenities]=4,5,6

### What is actually happening?
http://travelr.local?filter%5Bgalaxy_id%5D=1,2,3&filter%5Bname%5D=abc&filter%5Bamenities%5D=4,5,6

**Comment by posva** [comment]
That is expected behaviour, by default we use `encodeURI` and `encodeURIComponent` to encode urls. You can override this behaviour with `stringifyQuery` (in docs) but it's not recommended to not encode characters, so make sure to do it for those that are necessary (I don't have the list, it probably depends on the browsers as well)
