### ISSUE TITLE
Reload page when router-link is clicked in the same route

### ISSUE THREAD

**Issue by armandomendivil** [vuejs/vue-router#2191]
### Version
3.0.1

### Reproduction link
[http://jsfiddle.net/aevdnmzw/](http://jsfiddle.net/aevdnmzw/)

### Steps to reproduce
click home link multiple times and look like it is just created just once

### What is expected?
I wanna reload the same page clicking  router-link

### What is actually happening?
It is just created once

---
I'm using element-ui but I'm lookin' that is a behavior for vue-router, I know is not a bug but I want to know how can I do to get my expected behavior, Cheers!

**Comment by posva** [comment]
Do a regular link with `window.location.reload`.

Please, next time consider using the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js) for questions first. But feel free to come back and open an issue if it turns out to be a bug 🙂
