### ISSUE TITLE
route containing prop and using a same component is not updated

### ISSUE THREAD

**Issue by kbouh320** [vuejs/vue-router#2247]
### Version
3.0.1

### Reproduction link
[https://jsfiddle.net/b7mj1Lkt/](https://jsfiddle.net/b7mj1Lkt/)

### Steps to reproduce
```javascript
{
    path: '/documents/:collectionSlug',
    component: PageListDocuments,
    name: 'list-documents',
    props: true,
    meta: {
        title: 'Documents'
    }
},
```
Navigating through different urls such as /documents/groundschool and /documents/administration does not update the url with the new prop, it will always stays on the first url selected even though  the beforeRouteUpdate hook is called in my component PageListDocuments.

To navigate through the different urls I use that code 
```html
<v-list-tile v-for="(item, index) in userMenuItems" :key="index" @click="clickMenu(item)">
    <v-list-tile-action><v-icon>{{ item.icon }}</v-icon></v-list-tile-action>
     <v-list-tile-title>{{ item.text }}</v-list-tile-title>
</v-list-tile>
```

```javascript
clickMenu(item) {
    if (_.has(item, 'link')) {
        if(item.link.indexOf('http') == 0) {
            window.open(item.link)
        }
        else {
            this.$router.push({ path: item.link })
        }
    }
     else if (_.has(item, 'action')) {
        item.action()
    }
}
```

My navigation guard shows the correct from and to object.

```log
change route to {name: "list-documents", meta: {…}, path: "/documents/flying", hash: "", query: {…}, …}
change route from {name: "list-documents", meta: {…}, path: "/documents/ground-school", hash: "", query: {…}, …}
```

### What is expected?
The url should be updated with the new subroute

### What is actually happening?
The url stays the same

**Comment by LinusBorg** [comment]
Your reproduction is not working, it's throwing errors in the console.

Also, since in jsfiddle you can't see the URL, you should consider writing your reproduction on codesandbox.io or a similar service, or provide a repository for us to clone.

**Comment by MohannadNaj** [comment]
This is the reproduction on codesandbox.io:

[https://codesandbox.io/s/vm3nq92k90](https://codesandbox.io/s/vm3nq92k90)

Looks like the url is updating as expected.

Note that printing the `$router` properties in the template will cause a `TypeError: Converting circular structure to JSON` error.

On a different note:
I came here to check the same issue, I thought navigating to a new url using the same component will fire the `mounted` hook again, but it turns out it's not like that. If the component template/watchers/.. depends on props passed by vue-router, it will be updated appropriately, but the component will remain `mounted` once.

**Comment by kbouh320** [comment]
Hi @MohannadNaj  and thanks for the sandbox

Indeed it works. I figured out the problem comes from my webpack dev server and history mode. Still investigating.
