### ISSUE TITLE
可以增加一个全局钩子函数吗，监听路由dom加载完成后触发回调函数

### ISSUE THREAD

**Issue by hxkuc** [vuejs/vue-router#2268]
### What problem does this feature solve?
我正在做一个功能，就是给路由加上动画跳转，类似于如下代码
```
<transition :name="transitionGroup.trransitionName" :mode="transitionGroup.mode">
  <router-view :class="transitionGroup.routerClass"></router-view>
</transition>
```
每次在动画完成之后我要清除上次跳转的动画，或者说把transitionGroup设置成默认的动画，保证每次在写跳转的时候在没有规定动画的前提下使用默认动画而不是使用上一次跳转的动画
问题在于：
当我使用afterEach的时候，afterEach其实是在dom渲染之前触发的，那么我改变transitionGroup也是在dom渲染之前触发的，所以这么做就会导致动画调用出问题

所以想问下有没有类似dom渲染之后触发的回调函数，我知道有个beforeRouteEnter但是这个是在组件内的，我不可能在每个组件里都写一个这个方法，所以想问下有没有什么好的方式去实现

### What does the proposed API look like?
```
router.afterDomReady(function() {
  store.dispatch('changeTransition', 'flipx')
})
```

**Comment by posva** [comment]
If you have a transition you can listen to transition events.

---

Please, next time consider using the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js) for questions first. But feel free to come back and open an issue if it turns out to be a bug 🙂

**Comment by hxkuc** [comment]
@posva Brother, you're so great
