### ISSUE TITLE
in-component guards not called correctly with key's router view

### ISSUE THREAD

**Issue by ccqgithub** [vuejs/vue-router#2291]
### Version
3.0.1

### Reproduction link
[http://jsfiddle.net/smxe4ht7/](http://jsfiddle.net/smxe4ht7/)

### Steps to reproduce
just look the demo:  http://jsfiddle.net/qajtru23/

### What is expected?
when the `router-view` has a new instance, it will have a new lifecycle, call (the component of the new router-view)'s  `beforeRouteEnter` guard .

### What is actually happening?

When the router change,  it will create a new `router-view` instance because the router-view has `key="$route.fullpath"`.

For the new router-view instance, it is expected to call the  `new component`'s `beforeRouteEnter` guard, but it only call the old component's `beforeRouteUpdate`,  never call `new component`'s `beforeRouteEnter` ....

and, i can't get the  new component instance of the new router view when the router change, so i can not update the new component's data!

**Comment by posva** [comment]
This is working as expected. The route isn't changing, so no `beforeRouteEnter`. You can hook into component hooks though, like `created` and `mounted`

Please, next time take the time to lay down repro steps, _just look the demo_ is not clear at all 😉 . Something like _Click add one_, _click add two_, _check console_ is fine

**Comment by ccqgithub** [comment]
@posva when i click `one`, `two`, or `three`, the `$route.path` is changed, why you say `The route isn't changing`?

```html
<div id="app">
  <transition name="slide-fade">
    <keep-alive>
      <router-view :key="$route.fullPath"></router-view>
    </keep-alive>
  </transition>
  <p><router-link to="/app/one">One</router-link></p>
  <p><router-link to="/app/two">Two</router-link></p>
  <p><router-link to="/app/three">Three</router-link></p>
  <div>
    <p style="color: red; line-height: 16px; margin: 0; padding: 0;" v-for="(item,index) in msgs" :key="index">
      {{item}}
    </p>
  </div>
</div>

<template id="home-component">
  <p>Value: {{x}}</p>
</template>
```

```js
const Home = { 
	template: '#home-component',
  props: ['id'],
  data: function() {
  	return {x: 0};
  },
  beforeRouteEnter: function(from, to, next) {
    next(function(vm) {
      vm.$root.addMsg('enter:' + vm.id);
    });
	},
  beforeRouteUpdate: function(from, to, next) {
    next();
    this.$root.addMsg('update:' + this.id);
	}
}

const router = new VueRouter({
  mode: 'history',
  routes: [{
      "path": "/app/:id",
      "name": "app",
      "component": Home,
      "props": true
  }]
})

new Vue({
  router, 
  el: '#app',
  data: {
  	msgs: []
  },
  methods: {
  	addMsg(msg) {
    	this.msgs.push(msg);
    }
  }
});
```
 Look at the example above, 

1.  After app is initialed,  the `route-view` will have a new instance(routerViewA), it will create a `Home` component instance (vmA).
2.  When i click the `two`, this route path has changed, so the `route-view` will have a new instance(routerViewB), it will create a `Home` component instance (vmB).
3.  When i click the `one` again , this route path has changed,  it wil return to `routerViewA` and `vmA`.

But, when i click `two`, it never trigger 'beforeRouteEnter' for `vmB`, only trigger `beforeRouteUpdate ` for `vmA`;

So, i can never reach the `vmB`. 

Maybe, when i first click `two`, i can use `mounted` hook for `vmB`.

But `One` => `Two` => `One` => `Two`,  it will not call `mounted` hook for `vmB`, so i can not reach `vmB`

**Comment by posva** [comment]
It's the same route with a different param, that's what I mean.

Cheers.

**Comment by ccqgithub** [comment]
@posva  thank you for explaining,  i understand it now, 

 but, the `step 2` above, in the new `router-view` instance's `vmB`, never call any router guard,  isn't it weird?

**Comment by posva** [comment]
I don't understand what you are saying, the route guard is being called...
This is becoming a question, though...

**Comment by akarelas** [comment]
@posva For us developers who use `<router-view :key="$route.fullPath" />`, the fact that `beforeRouteEnter` doesn't get called when transitioning between the same route but with different parameters, makes it almost impossible for us to work.

I'd like to be more specific: What I want to achieve, is to load (with AJAX) all the data that the new page (which is the same route as the current, but with different parameters) requires to be displayed correctly, before the page appears to the user. Because I don't want the page to appear empty to the user for a few milliseconds, which produce a flicker effect to their screen.

However, I believe that with the current way that vue-router works, you are forcing us to give them a flicker effect. This is because we use `:key="$route.fullPath"`

Am I wrong to use `:key="$route.fullPath"`? It makes life a lot easier some times, when you just want a fresh new component, without all the data that has been leftover from the previous pageview (of the same route, but with different parameters).

I understand that you don't want to make beforeRouteEnter to be executed every time, because you want to preserve backwards compatibility. Is it so unreasonable, therefore, to ask for a configuration parameter in router, which will make beforeRouteEnter to be executed every time, if the user wants? (And I think that they **do** want, if they use `:key="$route.fullPath"`).

Alternatively, do you see any workaround for my problem? (which is the flickering, whenever I change route).

Thank you, hoping for an answer!

**Comment by leoyli** [comment]
@akarelas, generally specking, there are many work around to avoid component flicking, depends on your use cases,

(1) use `v-if` in the parent component to defer a rendering;
(2) use `:key="$router.params"` if you want to avoid using `fullpath`;
(3) similarly, you can bind an function in computed property with customized key value generator. (e.g. `Date.now`, or an hash function);
(4) use `watcher` to enforce child rerender (but I see it is a bad practice).

**Comment by akarelas** [comment]
I only understood options (1) and (2) (that's how far my knowledge permits), and both of these would produce a flicker effect. Option (1) would produce a blank area on the screen for a short while. That's what I call a flicker effect. Isn't it?

I don't understand how option (2) would change anything from what I already have?

**Comment by akarelas** [comment]
I'm sorry, did I give the impression that I don't want to use the word fullPath for some reason? That's not at all the case.

**Comment by leoyli** [comment]
Oh, I see your use case. Your Ajax call is in the lifecycle and you want to update the state (context) without loosing your previous state (i.e. state 1 -> state 2, and no empty immediate state) right?! In this case I recommend you lift your fetching logic into vuex store or a smart component, and bind the `key` value with an unique identifier in from state.  You will have a flickering is due to an async nature and you have an unnecessary rerender in that period (aka, rerender in a wrong time). In any case, you have to ensure your app have received the data before the key get updated.

**Comment by posva** [comment]
Careful with `<router-view :key="$route.fullPath" />` as it will recreate the view component every time *anything* in the url changes (query, hash too).

>  the fact that beforeRouteEnter doesn't get called when transitioning between the same route but with different parameters, makes it almost impossible for us to work.

You have to use `beforeRouteUpdate` for params. Don't rely on the component being recreated for ajax fetching. You can also use a watcher on `$route.params` or `$route`

Locking as this has been explained in multiple issues, docs and forum posts already
