### ISSUE TITLE
Link :to does not allow numbers

### ISSUE THREAD

**Issue by rinu** [vuejs/vue-router#2322]
### Version
2.5.16

### Reproduction link
[https://jsfiddle.net/n7sjp3eL/](https://jsfiddle.net/n7sjp3eL/)

### Steps to reproduce
Create a router link to a number.

### What is expected?
`:to` should be allowed to be a number.

### What is actually happening?
`:to` is expected to be a string or object.
`Invalid prop: type check failed for prop "to". Expected String, Object, got Number.`

---
In my use case an id would be appended to the URL to load a single resource view. Without the id a list of resources is shown.

**Comment by LinusBorg** [comment]
Just convert it to a string for this edge case. 

I don't think we chould adjust theprop type check to include Numbers.

**Comment by rinu** [comment]
I am currently converting it but it looks ugly. I don't like fighting with the framework and making it do something it's not designed for. Is my use case not legitimate? Is there a good reason to not allow numbers?

**Comment by LinusBorg** [comment]
It's not that it's not "legitimate", it's just that it's an edge case that we shouldn'T optimize for, in my opinion.

Here's why: `to` only accepts to kinds of parameters:

1. a path, which is a `String`
2. options in form of an `Object`

Your case is an edge case because a Number on its own is not a valid path, and only with the `append` option and the fact that your particular dynamic path can be extended by a Number as a param it becomes valid.

So if we were to optimize for that, we would have to accept Numbers as a type for this parameter, which is confusing as it doesn't make sense for the normal, non-`append` use cases, and would mean router-link would not warn you against this:
```
<router-link v-bind:to="1">
```
Of course your app would simply break and you will eventually figure it out, but since a Number doesn'T make sense here, a helful warning would be great, right? For that we need to *not* accept numbers as avalid type for this prop.

We could also typecast all non-object params to strings in `router-link`, but that could also lead to unexpected results if you pass other stuff besides numbers in.

---

As a sidenote, You should keep your ids as strings in general. URLs are always strings, so if your ids have to be numbers, you will have to typecast them into Numbers over and over when reading them from `$route.params` - because they will be strings, not numbers, when the user refreshes the page.

**Comment by posva** [comment]
Convert it to a string as the error is telling you to do. This could also conflict with #880

**Comment by rinu** [comment]
I disagree still. When I'm sending someone to a numeric route it should be converted to a string. It would probably work as expected by only changing one line to allow numbers.

*The /number URL is invalid*
It just isn't. Vue router will let me register it and it works as expected.

*The app would break with accidental numbers*
The app would not break. The client would be sent to a page that will result in a 404 if that number is not a registered route.

*You need a warning with accidental numbers*
There is no point in having a warning, you see a 404 page.

*You would need to convert types*
This is JavaScript still. Converting strings to numbers and vice versa happens all the time without thinking about it or doing anything explicit. Don't get me wrong, knowing your types and using them properly is a good thing. But this sort of limitation eliminates the good side of loose typing.

*You can convert to string yourself*
I can but it's ugly. Also, see above.

*https://github.com/vuejs/vue-router/issues/880*
Is not a good idea. Shorthands for back and forward are a good idea but not in a confusing way like proposed there. It makes more sense for `:to="-1"` to literally go to `/-1` not back.
