### ISSUE TITLE
this.$route.params returns "undefined" as a string

### ISSUE THREAD

**Issue by roblav96** [vuejs/vue-router#238]
I was trying to do something like so:
```javascript
if ( !_.isUndefined( this.$route.params.id ) ) {
```
but if there are no parameters, it returns undefined as a string.
![bug](http://i.imgur.com/6CBWPtZ.png)

**Comment by yyx990803** [comment]
Are you using `v-link` or `router.go` to route that expects params but not providing the params?

**Comment by roblav96** [comment]
I'm using route.go with params as an undefined value.

**Comment by yyx990803** [comment]
A param should not be undefined... consider a route like `a/:id/b`, there's no reasonable way to interpret `id` as optional. Therefore `a/` and `a/:id` should be treated as different routes. If you are going to `a/:id` then you should **always** provide an id, otherwise you should just go to `a/` instead.

**Comment by roblav96** [comment]
Oh ok. I didn't know if that was a bug or something. Thank you!
