### ISSUE TITLE
Nodes leak when using an input with type=password

### ISSUE THREAD

**Issue by posva** [vuejs/vue-router#2389]
### Version
3.0.1

### Reproduction link

```html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Document</title>
</head>


<body>
  <script src="https://unpkg.com/vue@2.5.17/dist/vue.min.js"></script>
  <script src="../dist/vue-router.min.js"></script>

  <div id="app">
    <router-link :to="'/'">Home</router-link>
    <router-link :to="'/Login'">Login</router-link>
    <router-view />
  </div>

  <script>
    const Home = {
      template: `
      <div class="home">
      <input 
        type="password"
        placeholder="password" 
        name="password"><br>
  </div>
  `
    }

    const Login = {
      template: `
      <div class="login">
    <div>
      <h2>Login</h2>
      
      <button>Login</button>
    </div>
  </div>
  `,
      methods: {
        submitClicked(id, password) { }
      }
    }

    Vue.use(VueRouter);
    const router = new VueRouter({
      mode: "history",
      base: '/explorations/',
      routes: [
        {
          path: "/",
          name: "home",
          component: Home
        },
        {
          path: "/login",
          name: "login",
          component: Login
        }
      ]
    });

    new Vue({
      router,
    }).$mount("#app");
  </script>

</body>

</html>
```

(file to be created in `explorations` folder) in vue-router repro after running `npm run build`

### Steps to reproduce
- record memory grap in performance tab in chrome
- click links to change views multiple times
- garbage collect
- repeat
- stop recording
- check node count increase

### What is expected?
node count should go back to the same value after second garbage collection

![screen shot 2018-09-16 at 14 52 52](https://user-images.githubusercontent.com/664177/46256221-ff809700-c4a7-11e8-8cbd-4d040c32c7e4.png)

### What is actually happening?
it keeps increasing

![screen shot 2018-09-16 at 14 53 44](https://user-images.githubusercontent.com/664177/46256222-ff809700-c4a7-11e8-8b05-d24f8b22030b.png)

---
Removing the type=password makes it behave as expected

**Comment by chiaweilee** [comment]
![screenshot 2018-11-13 at 17 03 10](https://user-images.githubusercontent.com/29817353/48402337-601d1800-e766-11e8-9794-2e2de7b8853b.png)
![screenshot 2018-11-13 at 17 04 45](https://user-images.githubusercontent.com/29817353/48402340-64493580-e766-11e8-8047-c99b05471ae2.png)

seems like VueComponent and VNode did not cleared.
I did some test, seems little bit better:
```
// vue-router.esm.js
// # 535
Vue.mixin({
beforeCreate: function beforeCreate () { ... },
    destroyed: function destroyed () {
      registerInstance(this);
      this.$vnode = null; // test
    }
});
```

**Comment by GummyDonut** [comment]
Sorry to bother, has there been any progress on this since, we also noticed this memory leak as well and was wondering if there was any work around?

Edit:  I tried @chiaweilee fix with the reproduction and unfortunately it looks like the nodes (green line) still increase over time.
![image](https://user-images.githubusercontent.com/5553615/48793588-7a567900-ecc5-11e8-8964-29ce4079d6b4.png)

**Comment by Domino9697** [comment]
I've done some digging and I think this issue is not related to Vue Router. I tried to reproduce this issue in plain Vue by just toggling a password input on and off.

I created a JSFiddle reproducing this:

https://jsfiddle.net/Domino9697/u2Lnh9r3/

If you follow the steps mentioned by @posva above by clicking on the button instead of changing views, you will have these results in the performance tab:

![Vue_input_problem](https://user-images.githubusercontent.com/31185922/58244641-50a10c00-7d53-11e9-8312-4a9da60ce4f2.png)

By removing the type="password", you will see a normal behavior as described by @posva.

I then did some more digging in the memory panel of the chrome dev tools and I found that the Detached HTML Input elements were still referenced by a node named Blink Roots:

![image](https://user-images.githubusercontent.com/31185922/58244947-f05e9a00-7d53-11e9-971a-008f762f4831.png)

These Blink Roots do not appear when using an input type other than "password".

I then tried to reproduce the issue in plain JavaScript to see if it was a Vue related issue:

https://jsfiddle.net/Domino9697/zb59ch2j/

The idea is to add a password type input and then to remove it from the DOM in plain JavaScript using a toggle button.

We get the same issue as above:

![javascript_password](https://user-images.githubusercontent.com/31185922/58245377-ef7a3800-7d54-11e9-9863-451e6353c01e.png)

However, if we remove the input type from the field we get this:

![javascript_input_text](https://user-images.githubusercontent.com/31185922/58245410-01f47180-7d55-11e9-9c52-9ff599069d3c.png)
  
I thus believe this is a browser related issue.

**Comment by posva** [comment]
Thanks! I think you should open an issue in chromium and any other browser that has the same leak. I haven't checked their issue trackers so maybe it was already reported

**Comment by posva** [comment]
I opened https://bugs.chromium.org/p/chromium/issues/detail?id=967438
to me the leak only happens if we type in the password field

**Comment by Domino9697** [comment]
Hmmm this is weird ! In my case, this also happens when I am only toggling the password input ... In both cases, I think the problem is related to the Blink root element referencing the password html input elements. Since these are referenced, they cannot be removed with the garbage collector.

**Comment by posva** [comment]
Closing as this is not related to Vue nor Vue router
