### ISSUE TITLE
How to add ''/' in the end to link 'foo/' instead  'foo'

### ISSUE THREAD

**Issue by kondrashkin465** [vuejs/vue-router#2432]
### What problem does this feature solve?
I need add "/" to links in my project. I can change path in router setting on "path//" but i using nuxt , where routing  the generating . How I can settings that?

### What does the proposed API look like?
add settings which will be add to path "/"

**Comment by posva** [comment]
See https://github.com/vuejs/vue-router/issues/1443#issuecomment-308981849

---

Please, next time consider using the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js) for questions first. But feel free to come back and open an issue if it turns out to be a bug 🙂
