### ISSUE TITLE
props function repeatedly firing under specific circumstances

### ISSUE THREAD

**Issue by 719media** [vuejs/vue-router#2444]
### Version
3.0.1

### Reproduction link
[https://codepen.io/anon/pen/ePrqVe?editors=1010](https://codepen.io/anon/pen/ePrqVe?editors=1010)

### Steps to reproduce
Open up the codepen.
Click `Foo Link 1` to navigate to that route.
Scroll. Notice the console.log fires repeatedly during scroll.

### What is expected?
vue-router props function would only fire once on route change

### What is actually happening?
vue-router props function fires repeatedly

---
The problem goes away if you remove the line from the template `<div v-text="viewportScrollTop"></div>`

**Comment by posva** [comment]
it only appears once

**Comment by 719media** [comment]
I've made a simpler repro:

https://codepen.io/anon/pen/mzKbMr?editors=1010

The problem is definitely there. The callback is being fired basically whenever any of the parent reactive data values change. It doesn't seem to me that it should?

**Comment by 719media** [comment]
@posva Can you test again?

**Comment by posva** [comment]
I did test but forgot to leave a message hehe. It renders the router-view again because it's a functional component, therefore casting the props function again. You can always wrap it in a stageful component but the props, when defined as a function should be relatively simple not to be a perf problem
