### ISSUE TITLE
next(false) doesn't render component when using browser navigation

### ISSUE THREAD

**Issue by JosNun** [vuejs/vue-router#2458]
### Version
3.0.1

### Reproduction link
[https://codesandbox.io/s/rjwjwqlzlm](https://codesandbox.io/s/rjwjwqlzlm)

### Steps to reproduce
- Use browser navigation to navigate to a page where the `beforeEnter()` method calls `next(false)`.
- Eg. When viewing [rjwjwqlzlm.codesandbox.io/](https://rjwjwqlzlm.codesandbox.io/) in a browser, paste [rjwjwqlzlm.codesandbox.io/](https://rjwjwqlzlm.codesandbox.io/) in the omnibox.

### What is expected?
Like it works when using the router-link navigation, one would expect that changing the URL from `somedomain.com/` to `somedomain.com/admin` (or other "protected" route) would return the user to the previous page.

### What is actually happening?
Instead of working properly, the URL is changed to what it is supposed to be, but no component is rendered at the initial route. 

---
A workaround is using `next(from.fullPath)` instead of using `next(false)`

**Comment by posva** [comment]
The thing is, by entering a new URL, you are in a _"new context"_ with no access to previous URL. The workaround would not work if changing from `/foo` to `/admin`.
You can however check the `matched` array to see if it matched any route to properly redirect the user

**Comment by BenceSzalai** [comment]
Possible workarounds, that work even when navigating from a path other than `/`:

Workaround 1:
Use hash mode instead of history for [navigation](https://router.vuejs.org/guide/essentials/history-mode.html#html5-history-mode).

Workaround 2:
You can continue using History mode, by implementing this:
Store the last successfully accessed route in sessionStorage using the [`afterEach`](https://router.vuejs.org/guide/advanced/navigation-guards.html#global-after-hooks) feature, and read that from sessionStorage and use in the `next()` calls, instead of `false`.
