### ISSUE TITLE
How to get passed views in named view?

### ISSUE THREAD

**Issue by rrandom** [vuejs/vue-router#2534]
### What problem does this feature solve?
Let's see we have a component `Layout.vue`.
```html
<div>
   <router-view name="left">
   <router-view name="right">
</div>
```

in the router.js:
```javascript
const left = {
  template: '<div>left</div>',
};

const right = {
  template: '<div>right</div>',
};

const onlyOne= {
  template: '<div>onlyOne</div>',
};


const router = {
  path: '/layout',
  children: [
    {
      path: 'both',
      components: {
        left: left,
        right: right,
      }
    },
    {
      path: 'only-one',
      components: {
        right: onlyOne,
      }
    }
  ]
};
```
In this example, when path at '/layout/only-one', Layout.vue dont know the named view 'left' is not passed in.

So. In Layout.vue. I can not know if specific named view passed in or not, unless I watch `$route` which is error prone. Is there any way the named views could pass as props or something else?

### What does the proposed API look like?
named views could be passed as props

**Comment by posva** [comment]
You should be able to use `$route.matche`

---

Please, next time consider using the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js) for questions first. But feel free to come back and open an issue if it turns out to be a bug 🙂
