### ISSUE TITLE
BeforeRouteEnter hook executes mounted hook

### ISSUE THREAD

**Issue by Rolanddoda** [vuejs/vue-router#2563]
### Version
3.0.2

### Reproduction link
[https://codesandbox.io/s/yqj0olnkk9](https://codesandbox.io/s/yqj0olnkk9)

### Steps to reproduce
In the sandbox go to `/about` manually.

### What is expected?
The mounted hook should not be executed.

### What is actually happening?
If you open the console you can see that mounted hook gets executed.

---
I don't know if this is made by design, but since beforeRouteEnter runs before the component gets mount, the mounted hook should not be executed if from beforeRouteEnter hook you redirect to another path. It seems like a bug to me.

**Comment by posva** [comment]
The callback passed to `next` gets executed after `mounted`. This is by design.
BTW, you can probably extract the code to a method and call the method in the `next` callback :)
Also, don't pass artificial params that have not been declared as props. This has never been supported and we do not plan on supporting local state on navigations
