### ISSUE TITLE
跳转到新页面通过params传参，取不到参数值

### ISSUE THREAD

**Issue by zbjy** [vuejs/vue-router#2572]
### Version
3.0.1

### Reproduction link
[https://codesandbox.io/s/pwjrx9r6lm](https://codesandbox.io/s/pwjrx9r6lm)

### Steps to reproduce
const {href} = this.$router.resolve({
                        name: "test",
                        params: {
                            id:2
                        }
                    });
                    window.open(href, '_blank');
在新页面获取不到参数id的值
let params = this.$route.params;
                alert(params.id)

### What is expected?
期望在新页面能取到通过params传递的参数值

### What is actually happening?
在新页面未能取到通过params传递的参数值

**Comment by posva** [comment]
make sure to declare params in the `path`

---

Please, next time consider using the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js) for questions first. But feel free to come back and open an issue if it turns out to be a bug 🙂

**Comment by DavisYao88** [comment]
如果需要通过params取到参数必须在router定义的时候,path写上占位符,目前vue-router3.x版本看来不支持隐式传参
