### ISSUE TITLE
Unknown element of vue router (e.g. router-link, router-view)

### ISSUE THREAD

**Issue by JeromeDeLeon** [vuejs/vue-router#2581]
### Version
3.0.2

### Reproduction link
[https://github.com/JeromeDeLeon/vue-router-bug](https://github.com/JeromeDeLeon/vue-router-bug)

### Steps to reproduce
* Create a project using vue-cli choosing manual preset.
* Enable the following features:
   -  Babel
   -  Router
   -  Vuex
   -  Use config files
* Run the application in development

### What is expected?
Show the template of Home.vue

### What is actually happening?
The app was just showing the "Home | About" and nothing else. In console (dev tools), there's an error showing unknown elements for router-link and router-view.

---
I just did nothing but follow the documentation when creating a project but did a side note of manually selecting the features.
I tried again to create another project, but same result. Again, I tried, same result but there's no error in the console (dev tools)

**Comment by posva** [comment]
Your repo was missing an eslint config but everything is working.

---

Please, next time consider using the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js) for questions first. But feel free to come back and open an issue if it turns out to be a bug 🙂
