### ISSUE TITLE
router-view mounted lifehook?

### ISSUE THREAD

**Issue by igorveremsky** [vuejs/vue-router#2584]
### What problem does this feature solve?
I use preloader at my spa and want to hide it only if page DOM ready, for not clone code to mounted lifehook of all my routes components will be good to have general mounted lifehook for `router-view` 

### What does the proposed API look like?
```js
Router.viewMounted(() => {
	// do some on router view mounted
})
```

**Comment by posva** [comment]
There router.onReady and your root component mounted hook.

---


Please, next time consider using the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js) for questions first. But feel free to come back and open an issue if it turns out to be a bug 🙂
