### ISSUE TITLE
Clarify hook return value in "Custom Fields" documentation

### ISSUE THREAD

**Issue by jonagoldman** [vuejs/vue-router#259]
Its not clear just from reading the "Custom Fields" section inside "Route Object & Route Matching", that **the hook must return something*** in order for it to work.

I was learning about vue-router and read this section before reading about hooks.

**Comment by amirrustam** [comment]
@jonagoldman Actually this is addressed within http://vuejs.github.io/vue-router/en/pipeline/hooks.html under "Hook Resolution Rules," rule 3 . If the hook accepts the `transition` argument then it needs to continue the pipeline with `transition.next()`, otherwise it does not have to return anything.
