### ISSUE TITLE
v-if/else Causes incorrect router-link to be followed when conditional changes

### ISSUE THREAD

**Issue by wadetandy** [vuejs/vue-router#2612]
### Version
3.0.2

### Reproduction link
[https://codesandbox.io/s/q3mp33l879](https://codesandbox.io/s/q3mp33l879)

### Steps to reproduce
- Observe the navigation has links for "Register" and "Sign In"
- Click the "Sign In" link
- Click "click here to sign in" on the page
- Observe the navigation will change to a "signed in" state with "User Profile" and "Sign Out" links
- Click the "User Profile" or "Sign Out" links

### What is expected?
If clicking "User Profile", the page should change to `/profile` and have the text "hello user"
If clicking "Sign Out", the page should change to `/sign_out` and be a sign out placeholder page

### What is actually happening?
If clicking "User Profile", the page changes to `/register` and loads the corresponding component
If clicking "Sign Out", the page should change to `/sign_in` and loads the corresponding component

It seems the navigation link elements are not being replaced when the conditional flips, but instead the inner html is being switched out.  This causes the original click handlers to be preserved on each link, which results in the "signed in" links firing the click handlers of the element that corresponded to its position in the list for the "signed out" path.

---
This may be a core vue runtime bug, but since I have run into the issue only with `router-link` I opened it here.

**Comment by posva** [comment]
this is related to the `a` elements being used inside the `li` instead of having the `router-link` being an `a`. Using an `li` and then nesting a `router-link` inside will be the right way to go:

```html
<li>
      <router-link :to="{ name: 'profile' }">
        User Profile
      </router-link>
</li>
```

Not sure if is related to recent change in Vue core with slots

another workaround is to key the `ul`

**Comment by wadetandy** [comment]
In my case that's not a workable solution, since my UI library (bootstrap in this case) requires the `active` class to be set on the `li`, not the anchor tag.

(`key` did end up being a good workaround in this case, but this shouldn't be necessary)

**Comment by wadetandy** [comment]
>Not sure if is related to recent change in Vue core with slots 

Have verified this is an issue with both latest 2.6.x and 2.5.x releases of Vue, so not sure whether that applies.

**Comment by mjntan35** [comment]
@wadetandy 

https://codesandbox.io/s/jpwv3nq923

I added key attribute into the router-link.. it seems to be working now

**Comment by wadetandy** [comment]
yeah, this was my workaround as well.

After diving into the code a little further, it seems the issue is due the [click handler](https://github.com/vuejs/vue-router/blob/dev/src/components/link.js#L64-L66) using a closure to access the `location` variable, as it isn't updated with successive renders of the component.  If you rerun the [`router.resolve`](https://github.com/vuejs/vue-router/blob/dev/src/components/link.js#L34) inside the handler, it calculates the correct location and it works correctly.  

Would be glad to submit a PR to fix this issue if that's the desired solution.

**Comment by posva** [comment]
I looked again at the code and the problem disappears when using `$root` instead of the `$auth` module because this module was a `Vue.extend`. I didn't see that the first time but that's not supposed to be done and is unsupported. For small applications, you can put the methods, data, etc at the root instance in main.js and then access it through `$root`, otherwise, using something like Vuex will work. This is because you need the reactivity, otherwise using a plain class would also work. You could also use Vue.utils.defineReactive but I would prefer the two other solutions as they are more likely to keep working in future major versions without any or minor change

I didn't look further into the problem as I didn't find a trivial solution but because it was not supposed to work in the first place I will close this. If someone wants to dig the problem and find a solution, please ping me here 🙂
