### ISSUE TITLE
directive on vue-router does not run update hook when created inside functional component

### ISSUE THREAD

**Issue by species7213uv** [vuejs/vue-router#2636]
### Version
3.0.2

### Reproduction link
[https://jsfiddle.net/xqge8a2m/](https://jsfiddle.net/xqge8a2m/)

### Steps to reproduce
First of all, apologies, because my jsfiddle seems to have a different problem. There the render function of the functional component is performed each time the route changes. I don't understand why.
This does not occur in my project, which I tried to reproduce.
There I get the "inserted" hook, but never the updated, even if I press the links and change the route (and the activeClasses gets updated)

### What is expected?
The directives update hook should be triggered

### What is actually happening?
The updated hook is not triggered. Only the inserted (when I first render the page). Then nothing more.

---
I am using the latest vue version 2.6.8.

**Comment by posva** [comment]
functional components are always re rendered, so the whole thing is updated every time. You probably want to use the inserted hook on top of the updated hook

---

Please, next time consider using the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js) for questions first. But feel free to come back and open an issue if it turns out to be a bug 🙂
