### ISSUE TITLE
translations with vue-router and vue-i18n

### ISSUE THREAD

**Issue by Jejec** [vuejs/vue-router#2643]
### What problem does this feature solve?
Hello,

I apologize if I don't make my request correctly but I only had a choice for an error or a new feature.
I have been looking for a solution to translate my urls as cleanly as possible according to the language.  I was wondering if you had a particular solution to propose?

Thank you for your time.

### What does the proposed API look like?
I just don't have a viable solution right now.

**Comment by posva** [comment]
Hi, yeah, sorry, issues are for bug reports and feature requests only. You will have to use the appropriate channel for questions.

This is a question I have gotten multiple times so I will shortly answer here and probably add some docs in the future.

Handling translated url routes isn't easy because you have to replace the whole routes config and this is not well handled right now by vue router because it's dynamic routing and it wasn't prepared for this in the first place. However, you should be able to achieve this by creating a new router and replacing the matcher as pointed out here: https://github.com/vuejs/vue-router/issues/1234#issuecomment-357941465
