### ISSUE TITLE
refresh in windows for about 20 times, it will redirect to default page.

### ISSUE THREAD

**Issue by wghust** [vuejs/vue-router#2657]
### Version
2.8.1

### Reproduction link
[https://github.com/vuejs/vue-router](https://github.com/vuejs/vue-router)

### Steps to reproduce
1：windows system
2：refresh one page without default page, eg: '/abc/axxx'
3：it will sometimes redirect to '/'

### What is expected?
no auto redirect

### What is actually happening?
redirect to default page '/';

**Comment by posva** [comment]
This is probably something in your code.

---

Please, next time consider using the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js) for questions first. But feel free to come back and open an issue if it turns out to be a bug 🙂

**Comment by wghust** [comment]
@posva why you close all about this question? I search in the issues，they all be closed without no answer.
