### ISSUE TITLE
When different parameters are used in the same component, the keep-alive function is not normal.

### ISSUE THREAD

**Issue by chaoren1641** [vuejs/vue-router#269]
I opened the keep-alive in router-view.

Use the following routing configuration:
```js
router.map({
  'order:id': {
    component: orderDetail
  }
});
```

When I visited `order/1`, it was a state of preservation. But this time to visit the `order/2` display is also the content of `order/2`

**Comment by chaoren1641** [comment]
Here is an sample http://jsfiddle.net/vq8xyocm/2/

**Comment by dirtysnow** [comment]
have the exact same problem, if someone could answer, it would be greatly appreciated!

**Comment by amirrustam** [comment]
@chaoren1641 @dirtysnow The `data` transition hook can help you here. Its API docs actually touches on this exact matter: http://vuejs.github.io/vue-router/en/pipeline/data.html

Using the JSFiddle (http://jsfiddle.net/vq8xyocm/2/) you provided as reference you can solve this issue by setting the `message` every time the component is loaded/displayed, instead of setting it within the component data property. So in your Fiddle you were doing this:

```javascript
var Bar = Vue.extend({
    template: '<p>This is bar!,params is {{message}}</p>',
    data :function() {
      return {
        message:'hello,' + this.$route.params.id
      }
    }
})
```
But to fix the problem, you should do this instead:
```javascript
var Bar = Vue.extend({
    template: '<p>This is bar!,params is {{message}}</p>',
    route: {
    	data: function(transition) {
	        transition.next({message: this.$route.params.id });    
      }
    }
})
```
I've updated the Fiddle and you can see it working here: http://jsfiddle.net/vq8xyocm/3/

From a developer UX standpoint this behavior is not obvious, so I would consider that this part needs some enhancement, and is not as intuitive as the rest of Vue's API. @yyx990803's input would be valuable here.

**Comment by chaoren1641** [comment]
@amirrustam  thank you, I really do not understand this method, a few days in the project to try

**Comment by torresyb** [comment]
我也碰到了类似的问题，不知道是如何解决的，求解
