### ISSUE TITLE
Strange behavior @click.stop

### ISSUE THREAD

**Issue by Pinegin** [vuejs/vue-router#2702]
### Version
3.0.3

### Reproduction link
[https://jsfiddle.net/rmy08k3u/1/](https://jsfiddle.net/rmy08k3u/1/)

### Steps to reproduce
Good day.

Faced a problem, can anyone be able to help.

When placing a block in the router-link with the attribute @click.prevent.stop, clicking on the block does not make the transition. But placed in the input-checkbox block does not work.

When placing a block in the router-link with the @click.stop attribute, clicking on the block makes the transition. And located in the input-checkbox block, it works.

### What is expected?
When placing a block in a router-link with the @click.stop attribute, a click on the block should not make a transition, and placed in the input-checkbox block should work.

### What is actually happening?
When placing a block in the router-link with the @click.stop attribute, clicking on the block makes the transition. And located in the input-checkbox block, it works.

**Comment by posva** [comment]
This is working correctly

---

Please, next time consider using the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js) for questions first. But feel free to come back and open an issue if it turns out to be a bug 🙂
