### ISSUE TITLE
it works strange when dynamic route matching and keep-alive use together

### ISSUE THREAD

**Issue by duanyijie** [vuejs/vue-router#2734]
### Version
3.0.3

### Reproduction link
[https://codepen.io/duanyijie/pen/yrxoWy?editors=1010](https://codepen.io/duanyijie/pen/yrxoWy?editors=1010)

### Steps to reproduce
1.open devTools
2.click comA-name-1
3.click comB-name-3

### What is expected?
expect only comB-childComB mounted

### What is actually happening?
comB-childComB and comA-childComA mounted together

---
expect each child component mounted once only and can be kept ailve

**Comment by posva** [comment]
What is happening is that by using the `key` attribute, you are forcing multiple instance of the same component, and because it is linked to a router param, even though the component isn't active, it's still changing. This should appear without vue-router too

To be clear, all components are kept alive though
