### ISSUE TITLE
Cannot access params when using typescript in vueclass

### ISSUE THREAD

**Issue by j-d-carmichael** [vuejs/vue-router#2756]
### Version
3.0.3

### Reproduction link
[https://i.stack.imgur.com/heuWw.png](https://i.stack.imgur.com/heuWw.png)

### Steps to reproduce
Try to access the params of a route within the typescript vue class as illustrated above and the compiler cannot resolve params.

### What is expected?
That the params are found and no error is thrown

### What is actually happening?
Typescript throws an error

---
The only way to get this working right now for me is to:
1 - Import the router to the component
2 - Access the params via string literals:  ``router['history'].current.params.hash``

This however breaks my linter.

**Comment by posva** [comment]
it's `this.$route.params`. `router.history` is not public API btw

---

Please, next time consider using the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js) for questions first. But feel free to come back and open an issue if it turns out to be a bug 🙂
