### ISSUE TITLE
Initial navigation allows missing the `base` part

### ISSUE THREAD

**Issue by donne1226** [vuejs/vue-router#2782]
### Version
3.0.3

### Reproduction link
[https://codesandbox.io/s/pyl49](https://codesandbox.io/s/pyl49)

### Steps to reproduce
set url /home or /app/home

### What is expected?
/app/home  -> direct to home page.
/home -> direct to blank page.

### What is actually happening?
/app/home  -> direct to home page.
/home -> direct to home page.

---
I wonder know if this is a  bug or feature? And I expect /home should not link to home page,  do I use the 'base' option correctly

**Comment by Airkro** [comment]
same problem

**Comment by Naeemo** [comment]
The `base` prefix in `path` will be trimmed here, while a path without a leading `base` will be used directly.
https://github.com/vuejs/vue-router/blob/9b01cbcc2c2c94ecbaa7a7df731febdb21352c4c/src/history/html5.js#L74-L80

It looks like a issue to me too, can we change the behavior?

**Comment by posva** [comment]
This should indeed not happen

**Comment by posva** [comment]
Coming back at this: the point of the `base` attribute is to allow serving an application from a different folder in your server like `example.com/app` instead of `example.com`. This means that the server must serve the application bundle **only** at `/app`. It shouldn't be serving an app at the root that uses a `base` option to `/app` and this scenario shouldn't exist
