### ISSUE TITLE
Visiting another page immediately creates the respective component, before disposing the component of the previous page. 

### ISSUE THREAD

**Issue by Rolanddoda** [vuejs/vue-router#2847]
### Version
3.0.7

### Reproduction link
[https://codesandbox.io/s/vuex-register-unregister-module-roli-roli-ct4kz](https://codesandbox.io/s/vuex-register-unregister-module-roli-roli-ct4kz)

### Steps to reproduce
1. When the page loads you are in the home component (/ route)
2. Click the Contact button to navigate to the contact component (/contact route)
3. Observe the error in the console.

In the Home and Contact components (or pages) I use store.registerModule and store.unregisterModule to dynamically register/unregister the same module.

### What is expected?
No error should be shown. If you go to the Home later About and later Contact page (and vise versa) everything works as expected.

### What is actually happening?
Vue router runs the new component before destroying the old one.

---
Initially I thought was a vuex issue and I opened one [here](https://github.com/vuejs/vuex/issues/1580). But then I saw that is a vue router issue. I tried to find if that issue already exists and couldn't find something.

As a workaround I can use transition mode out-in. And everything works
```js
    <transition mode="out-in">
      <router-view></router-view>
    </transition>
```

but to me, it doesn't makes sense to mount a component, before destroying the other one. What I am missing?

**Comment by posva** [comment]
This happens because dynamic components behave that way, and I thing is related to Vnode creation in Vue. It's something that would probably be a breaking change if changed.

You can however use the `beforeRouteLeave` hook to unregister the module. That way you are sure it works. I wonder if we should update the ssr docs https://ssr.vuejs.org/guide/data.html#store-code-splitting as well
