### ISSUE TITLE
Inconsistency router.resolve with named route

### ISSUE THREAD

**Issue by pimlie** [vuejs/vue-router#2887]
### Version
3.1.2

### Reproduction link
[https://jsfiddle.net/2xepjmf0/](https://jsfiddle.net/2xepjmf0/)

### Steps to reproduce
Call `router.resolve` both with as without the name of the route. When you specify the name, the last `/` will be escaped to a `%2F`. If you dont specify the name the last `/` will just be a `/` 

### What is expected?
Both calls to router.resolve return the same info

### What is actually happening?
They do not

**Comment by posva** [comment]
When you don't specify the name, what gets used is the path+query+hash, the rest is ignored. Which means you are passing this string to resolve: `'/user/you/#hash'` which is indeed different from `'/users/you%2F#hash'`. This is because slashes must be escaped inside params. We do it automatically on the object params but we cannot guess where to do it on a string

**Comment by pimlie** [comment]
Understood, thanks for the quick update :)
