### ISSUE TITLE
<!-- --> is rendered  instead of displaying the proper error message

### ISSUE THREAD

**Issue by hellboy81** [vuejs/vue-router#2889]
### Version
3.1.2

### Reproduction link

Router configuration:

[https://jsfiddle.net/w67fuxoj/](https://jsfiddle.net/w67fuxoj/)

### Steps to reproduce
- run wepack build with yarn
- open browser window with vue 
- vue is detected
- routes are detected
- In <RouterView> (functional) with name default   is rendered  instead of displaying the proper error message

### What is expected?
Component from route should be shown 

### What is actually happening?
`<!---->` is shown

---
Unable to investigate reason why component is broken

**Comment by posva** [comment]
Try using `router.resolve` to see what route is being matched. When no route is matched, nothing is displayed, it's not an error.

Please next time you report a bug, provide a runnable reproduction not just some piece of code. I cannot even help you with that code sample because there isn't even a navigation

**Comment by hellboy81** [comment]
```js
let testXXXRoute = router.resolve({
  name: 'testXXX',
})
```

matches the correct router

![image](https://user-images.githubusercontent.com/341600/63249687-431ff300-c26a-11e9-9725-53594f833f38.png)

**Comment by hellboy81** [comment]
@posva  can u provide possible issue duplicates?
