### ISSUE TITLE
'base' does not work with absolute URL

### ISSUE THREAD

**Issue by njam** [vuejs/vue-router#2927]
### Version
3.1.3

### Reproduction link
[https://repl.it/@njam/vue-router-base](https://repl.it/@njam/vue-router-base)

### Steps to reproduce
1. Set 'base' to an absolute URL
2. Resolve any link

### What is expected?
Final URL is based on absolute base URL:
"http://example.com/foo"

### What is actually happening?
Final URL is using base URL as relative path:
"/http:/example.com/"

---
I couldn't find a ticket for this, only a closed PR: https://github.com/vuejs/vue-router/pull/1353

**Comment by posva** [comment]
This is expected, the router expects only the URI part, without the domain. It does strip it when provided through the `base` element but not otherwise since the domain is out of router's reach so it would be confusing the specify a full url in the js, people may end up specifying different domains depending on the build when at the end, the URI is enough

**Comment by njam** [comment]
Ok thanks for clarifying!
