### ISSUE TITLE
addRoutes is not a function 

### ISSUE THREAD

**Issue by TaOooo** [vuejs/vue-router#2946]
### Version
3.1.3

### Reproduction link
[https://jsfiddle.net/e2swfukg/](https://jsfiddle.net/e2swfukg/)

### Steps to reproduce
axios.post(`/getPaymentList`).then(res => {
  if (res.status == 200 && res.data.code == 200) {
    let newRouter = res.data.data

    let paymentList = {
      path: "/payments",
      name: "Payments",
      component: Home,
      children: []
    }
  
    newRouter.forEach(element => {
        paymentList.children.push({ path: '/Payments/' element.pname , component: Payments})
    })

    Router.addRoutes(paymentList)
  }
});

### What is expected?
the data from database that can add in router

### What is actually happening?
vue_router__WEBPACK_IMPORTED_MODULE_1__.default.addRoutes is not a function

**Comment by posva** [comment]
It has to be the router instance, not the imported router from `vue-router`

---

Please, next time consider using the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js) for questions first. But feel free to come back and open an issue if it turns out to be a bug 🙂
