### ISSUE TITLE
able to change "to" route params in beforeRouteLeave hook

### ISSUE THREAD

**Issue by fxjeep** [vuejs/vue-router#2949]
### What problem does this feature solve?
The function I need is updating the params in "to" route in a component's beforeRouteLeave hook.

Changing params properties in "to" argument does not work. Adding new route in next() callback will call beforeRouteLeave again.

According to the document, next() callback in beforeRouteLeave should only take a "false" argument or no argument. 

Do you know how to implement my requirement?

### What does the proposed API look like?
n/a

**Comment by posva** [comment]
`to` and `from` are readonly parameters. `beforeRouteLeave` will be called every time you try to leave the view.

---

Please, next time consider using the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js) for questions first. But feel free to come back and open an issue if it turns out to be a bug 🙂
