### ISSUE TITLE
Console flooded with "Non-Error promise rejection captured with value: undefined"

### ISSUE THREAD

**Issue by koresar** [vuejs/vue-router#3095]
### Version
3.1.3

### Reproduction link
[https://exmaple.com/NOT_NEEDED](https://exmaple.com/NOT_NEEDED)

### Steps to reproduce
I'm calling `context.redirect("/")` in Nuxt.js middleware. I've found the exact lines in vue-router source code where it rejects with `undefined`.

### What is expected?
Promise rejections contain error object or do not reject.

### What is actually happening?
Console is flooded with "Non-Error promise rejection captured with value: undefined". We receive huge amount of Sentry issues automatically caught as `UnhandledRejection`

---
The `History.confirmTransition` method calls the function `abort()` (stack trace shows this exact line https://github.com/vuejs/vue-router/blob/fc42d9cf8e1d381b885c9af37003198dce6f1161/src/history/base.js#L163 ) which in turn calls `onAbort(err)` (stack trace shows this exact line https://github.com/vuejs/vue-router/blob/fc42d9cf8e1d381b885c9af37003198dce6f1161/src/history/base.js#L117 ) within the `transitionTo` method (stack trace shows this exact line: https://github.com/vuejs/vue-router/blob/fc42d9cf8e1d381b885c9af37003198dce6f1161/src/history/base.js#L88 )

 The `onAbort` then calls `reject(err)` (as Promise rejection), but the `err` is undefined (because `abort()`).

I assume, that the rejection should never happen.

To my very limited knowledge this line:
```js
onAbort && onAbort(err)
```
should be replaced with this:
```js
err && onAbort && onAbort(err)
```

**Comment by koresar** [comment]
Could be as well Nuxt.js bug... They promisify the `next` router calls and could be that the promisificaiton went wrong.

**Comment by Kolobok12309** [comment]
Have same problem
```js
this.$router.replace('/');
```
In `/` redirect that throw error
Some bad fix
```js
this.$router.replace('/', null, () => {});
```

**Comment by posva** [comment]
This is related to the promise api when no callbacks are passed to push/replace. You can find about it in the docs and an explanation behind the change at https://github.com/vuejs/vue-router/issues/2881#issuecomment-520554378

@Kolobok12309 you should be able to find the answer in that comment

@koresar in your case, it's a bit different because you are using a redirect, which internally is probably calling `next` inside a beforeEach hook, causing a redirection, aborting the previous call of `router.push`/`router.replace` and causing that specific call to return a rejected promise. If that's not what you did, then I will need a boiled down repro (it can use Nuxt) to check it, ping me once you have one.

The Promise API for navigation will go through an RFC for the next version of Vue Router, especially for what should and should not reject the promise

**Comment by koresar** [comment]
That was right guess, Eduardo.
I do redirect and I do reject previous push.
👏
