### ISSUE TITLE
Passing Params as Props does not Work Well with Composition API

### ISSUE THREAD

**Issue by geekox86** [vuejs/vue-router#3118]
### Version
3.1.3

### Reproduction link
[https://github.com/geekox86/OeMis](https://github.com/geekox86/OeMis)

### Steps to reproduce
1- `yarn serve`.

2- A type error is thrown in the terminal.

3- The types of `beforeRouteEnter` parameters (in `src/Base/Organization/Structure.vue` line 88) are not recognized by TypeScript.

### What is expected?
The program should execute correctly without having to define routing component `props` using the old syntax of Vue options API.

### What is actually happening?
The program does not work unless the old syntax of Vue options API is used to define routing component `props`.

---
See line 92 in `src/Base/Organization/Structure.vue`, if this line is uncommented everything works perfectly, but I do not want to use this old syntax. I just want to relay on Typescript type definitions in the `setup` function for `props`.

**Comment by posva** [comment]
You still have to declare the prop on the component: that line should not be commented. Regarding typing you should use `PropType` exported by `@vue/composition-api`

---

Please, next time consider using the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js) for questions first. But feel free to come back and open an issue if it turns out to be a bug 🙂

**Comment by geekox86** [comment]
@posva Thank you for your prompt reply and sorry if it is not a valid bug.

Since we are at it, can you hint me to the right direction in using `PropType`:

```
<script lang="ts">
    import {
        createComponent,
        reactive,
        PropType
    } from '@vue/composition-api'

    export default createComponent({
        setup: (props: { id: PropType<string> }) => {
            const selection = reactive({})

            return { selection }
        }
    })
</script>
```

Is this correct?

**Comment by posva** [comment]
I don't have the example at hand but it think it was like this:

```ts
props: {
  id: {
    type: String
  } as PropType<string>
}
```
