### ISSUE TITLE
Transpile/expose utils for importing into project

### ISSUE THREAD

**Issue by Knogobert** [vuejs/vue-router#3119]
### What problem does this feature solve?
This let's devs rely on one source of truth for using the same utilities as vue-router when building similar functionality into our own projects.

Mainly, this came up when looking for a way to import the `stringifyQuery` function from `vue-router/src/util/query.js`. Then realizing that it would need to be transpiled from TS etc. for it to be able to be imported.
This was so that I could build a URL with parameters to be sent to an API.

I have not researched further than this, but maybe there are more functions that could benefit devs by exposing them more easily?

### What does the proposed API look like?
```js
import { stringifyQuery } from 'vue-router';
...
const encodedQueries = stringifyQuery(query);
```

**Comment by posva** [comment]
Those utilities are used internally but we don't want to expose them because they could change in the future. So for the moment, with vue router 3, this is not going to happen. Things might change in vue router 4.

That being said, you don't really need those utilities, there are plenty of libraries that do that stringification. You even have a native URLSearchParams
