### ISSUE TITLE
Having store accessible from router on initialization depends on order of use statements

### ISSUE THREAD

**Issue by 719media** [vuejs/vue-router#3121]
### Version
3.1.5

### Reproduction link
[https://codesandbox.io/s/vue-routing-example-jf31j](https://codesandbox.io/s/vue-routing-example-jf31j)

### Steps to reproduce
The codesandbox works fine as is. However, if you change the order of the imports to

```
import router from "./router";
import store from "./store";
```
 as described in the code, the router.beforeEach will be unable to access the $store.

### What is expected?
the store would work in the router, regardless of the order of Vue.use statements

### What is actually happening?
The store is only initially accessible in router.beforeEach if Vue.use(Vuex) is called before Vue.use(Router);.

**Comment by posva** [comment]
This is because of the way these two plugins are installed and how the injection is done in Vuex: by checking on the parent on a `beforeCreate`. Unfortunately we cannot change that so the router should come last, if you want the navigation guard to happen on the first navigation.
Given the very reasonable ordering working properly, I don't think there is a need to allow a different ordering.
It won't be a problem in the next version though
