### ISSUE TITLE
[typescript] Incompatible Route and Location types

### ISSUE THREAD

**Issue by victortwc** [vuejs/vue-router#3139]
### Version
3.1.6

### Reproduction link
[http://shorturl.at/ixJQ5](http://shorturl.at/ixJQ5)

### Steps to reproduce
```
this.$router.push({
    ...this.$route, 
    params: {
        newParam: true
    }
})
```

With typescript, it breaks.

### What is expected?
Route and Location types are compatible.

### What is actually happening?
As Route now have the name parameter with `string | null | undefined` it breaks the navigation, as `Location` will only accept `string | undefined` as name.

---
Commit causing the issue:
https://github.com/vuejs/vue-router/commit/8f831f28f33bb766d5baaabc8b2daff259f3d45b

**Comment by posva** [comment]
The types are indeed not compatible: `null` can exist as a value of `Route` but when providing a `Location` with methods like `push` and `replace`, `null` is not valid `name`. FYI, there are a few other things that cannot be passed like `fullPath`. In general, spreading `$route` to a `push`/`replace` is a bad idea because it's a normalised location and it contains more information than a `Location`
