### ISSUE TITLE
<router-link> doesn't blur

### ISSUE THREAD

**Issue by krystof-k** [vuejs/vue-router#3149]
### Version
3.1.6

### Reproduction link
[https://codesandbox.io/s/xenodochial-murdock-xssfp](https://codesandbox.io/s/xenodochial-murdock-xssfp)

### Steps to reproduce
You can set up a new project `vue create .` & `vue add router`, then add

```css
a:focus {
border: 5px solid red;
}
```

and try to click any of the navigation links.

### What is expected?
It should blur after route changed.

### What is actually happening?
It doesn't blur.

---
I tried googling for a long time but found no issues mentioning this. So either I'm missing something or it nobody styles focus state.

**Comment by posva** [comment]
This is unrelated to vue or vue router, when you click a link it becomes focused.

---

Please, next time consider using the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js) for questions first. But feel free to come back and open an issue if it turns out to be a bug 🙂

**Comment by krystof-k** [comment]
Well, yes, but usually when you click a link, a new page is loaded where the link is no longer focused. So I would say it is an issue of Vue Router, or any other JS routing that doesn't refresh the page.
