### ISSUE TITLE
Uncaught TypeError: Cannot read property 'to' of null

### ISSUE THREAD

**Issue by lmk123** [vuejs/vue-router#325]
#### Updated:

When I upgrade to **vue-router@v0.7.8** (before is **vue-router@0.7.7**), this error happened. 

I reproduces this error in jsFiddle(with **vue-router@v0.7.8 and vue@1.0.14**): https://jsfiddle.net/lmk123/Lkohd5en/5/

But with **vue-router@0.7.7 and vue@1.0.14**, it don't happened: https://jsfiddle.net/lmk123/Lkohd5en/7/

**Comment by amirrustam** [comment]
Looks your transition target path is null. Can you provide some code or a jsFiddle that reproduces the issue?

**Comment by lmk123** [comment]
@amirrustam The code is here: https://github.com/lmk123/crx-selection-translate/blob/master/src/options/index.js#L37

I will create a jsFiddle later.

**Comment by lmk123** [comment]
I reproduces this error in jsFiddle: https://jsfiddle.net/lmk123/Lkohd5en/1/

**Comment by amirrustam** [comment]
Looks like with the update you can't specify a redirect route with a name. You have to provide a literal path string: https://jsfiddle.net/Lkohd5en/8/

Actually, the documentation doesn't specify that you can define redirects with route names. It explicitly states that redirects must be defined like so: `{ fromPath: toPath, ... }`. Please read: http://vuejs.github.io/vue-router/en/api/redirect.html

However, since it was working in the previous version, then this is a breaking change. @yyx990803 is this expected behavior or an unexpected consequence of a change?
