### ISSUE TITLE
[Feature Request] Refresh/Re-Navigate to current route to re-trigger route guards, data-fetching, and props assignments

### ISSUE THREAD

**Issue by douglasg14b** [vuejs/vue-router#3295]
### What problem does this feature solve?
Routing setups that dynamically trigger data fetching during navigation guards, and assign that data to component props are very handy and clean to configure on a global level. However, if you are looking at data in a route/component, and that data needs to be replaced/reloaded, you are stuck in a difficult situation. Either you need to reload the entire page/app, navigate away and then back to the route, or setup overly complex logic to modify potentially deeply nested object properties in place (Which is largely unfeasible if you have to do this for hundreds of different routes...).

The solution? Simply reloading the current route as if it was being navigated to. This triggers all the route guards, triggers all the data fetching, triggers all the props assignments, and sets up the component(s) fresh as they need to be. 

Back in AngularJS days, this made completely refreshing a route and it's data beyond simple, as all the navigation triggers & guards have the logic to handle data getting & assignment. KISS in it's finest.

However, it seems that vue router has no support for re-navigating/reloading the current route. It requires hacks or extensive workarounds, most of which directly impact user experience.

### What does the proposed API look like?
Unsure.

There has been a lot of misc discussions about this, for years, all of which have been shut down. Hopefully I clarified the problem space better than other requests...

**Comment by posva** [comment]
This has indeed been asked a few times because it existed before. It was removed because navigating to the same route to trigger everything was a workaround to fetching. Depending on how the loading state is handled in the application, fetching can be done inside or outside components. When done inside components, you can put fetching logic inside methods to reuse them and handle differently initial navigation from sub sequent navigations or not. Running all the other guards would be useless and potentially introduce problems of double fetching other information, unnecessary auto checks, etc that's why this kind of pattern was removed.

Note you can still trigger a new navigation by adding a query attribute like `router.push({ query: {t: Math.random()}})`
