### ISSUE TITLE
Nuxt-link and router-link don't create href attribute

### ISSUE THREAD

**Issue by SergeiPleshkov** [vuejs/vue-router#3343]
### Version
3.1.6

### Reproduction link
[https://github.com/SergeiPleshkov/create-nuxt-app](https://github.com/SergeiPleshkov/create-nuxt-app)

### Steps to reproduce

Serve reproduction repo, inspect the source code.

![image](https://user-images.githubusercontent.com/29925191/95989736-55c49680-0e33-11eb-959b-bb39625e24f7.png)

source code from devtools' network tab
![image](https://user-images.githubusercontent.com/29925191/95989883-8278ae00-0e33-11eb-8c4b-dd5940c365d9.png)

document ready
![image](https://user-images.githubusercontent.com/29925191/95989982-a1774000-0e33-11eb-9057-39a8ba700b8f.png)

### What is expected?
Passing not defined dynamic prop to `<n-link>` or `<router-link>'`should not cause href loss in SSR mode.

### What is actually happening?
Href attribute appears after browser render.

---
I also created an [issue](https://github.com/nuxt/nuxt.js/issues/8204) in nuxt repo, but i think this is mainly vue-router problem.

**Comment by posva** [comment]
If you provide an `href` attribute, it will override component's behavior, that's intended (in Vue). If you want to have better control of router-link, use the `v-slot` api

**Comment by maoberlehner** [comment]
I also ran into this problem. And I understand the reasoning in the following case:
`<RouterLink to="/a" href="/b">` but I don't understand what's the point of removing `href` in case of `<RouterLink to="/a" :href="undefined">`. In my opinion `:href="undefined"` should be treated as if `href` was not set at all.

Currently `<RouterLink to="/a" :href="undefined">` renders `<a>` without a `href`! This is a huge problem in terms of SEO and because the link still works when you click it, this often goes unnoticed.

I understand that there may be counter arguments to that. If this is actually the intended behavior, here is a workaround:

```html
<!-- This does **not** work correctly, `href` not rendered on RouterLink even if it is `undefined` -->
<Component
  :is="link.href ? `a` : `RouterLink`"
  :href="link.href"
  :to="link.to"
/>

<!-- Workaround -->
<Component
  :is="link.href ? `a` : `RouterLink`"
  v-bind="link.href ? { href: link.href } : { to: link.to }"
/>
```

**Comment by posva** [comment]
@maoberlehner note this is vue behavior. The idea is to be able to override existing bindings (which is exactly what is happening). For example in the case of `v-bind` with an object and then a specific `:href="undefined"` to remove that attribute.

Note that in your workaround you could also use a `v-if="link.href"` to render an `a` or a `router-link`
