### ISSUE TITLE
[Typescript] Location in Router.resolve should allow for undefined params to remove them

### ISSUE THREAD

**Issue by Glandos** [vuejs/vue-router#3344]
### Version
3.4.6

### Reproduction link
[https://jsfiddle.net/wr0ehvsd/2/](https://jsfiddle.net/wr0ehvsd/2/)

### Steps to reproduce
Call `router.resolve({ params: { id: undefined } })` to get the route for the same location with the `id` parameter.

The route is correctly defined with `/:id?` so `id` is optional.

### What is expected?
No typescript compiler error.

### What is actually happening?
Typescript complains because `params` in Location is `Dictionary<string>` and not `Dictionary<string | undefined>`

However, the behavior from vue-router is correct.

---
Maybe there is a workaround, but I didn't find it.

**Comment by Glandos** [comment]
I've found a workaround. Since `:id?` is matched against `[^/]+` by default, I modified the pattern and declare the following path: `/:id([^/]*)?`. It's kind of a hack though. I'd much prefer to see a better typing :+1:

**Comment by posva** [comment]
The type for params is correct, they are supposed to be strings. `undefined`/`null` are not supported (even though they are working). The correct way to remove a param is to not provide it in the `params` object, e.g. doing `params: {}`. Is there any reason to support explicitly passing the param with `undefined`?

Edit: Optional params are kept when doing relative navigations but are removed if a `name` is provided. Which means that `{ params: {} }` will keep an optional param but `{ name: 'home', params: {} }` (this is intended)

**Comment by Glandos** [comment]
> Optional params are kept when doing relative navigations but are removed if a name is provided. Which means that { params: {} } will keep an optional param but { name: 'home', params: {} } (this is intended)

OK, is there any rationale for this in the documentation? Sorry if I missed it :/

For now, I only have one optional param, but what if I had `/:id?/:alias?` and I just want to remove `alias` from the route? I can call:
```javascript
    const clone = {...this.$route.params}
    delete clone.alias
    this.$router.resolve({
      name: this.$route.name ?? undefined,
      params: clone
    })
```
But this seems to a bit heavy. I can admit that it's not a typical use case :wink:

**Comment by posva** [comment]
It's because relative navigation happens on the same route, so it's meant to behave differently based on the current location and it's more interesting to keep any optional params. Whereas named navigation is explicit and might navigate to a different location, and should yield the same result no matter where we are when it comes to its optional params. Since optional params are not required, `{ name: 'optionalparams' }` resolves to a location without them whereas required params will try to reuse params with the same name for convenience, especially when navigating between nested routes that have parent routes with params defined.

To remove the alias param in your example you have, params should only contain `id`:

```js
const clone = { ...this.$route.params, alias }
// or 
params: { id: this.$route.params.id }
```

You can also create a function `exclude(this.$route.params, 'alias')` similar to lodash's pick
