### ISSUE TITLE
Allow Protocol and Host to be Included in Base

### ISSUE THREAD

**Issue by stephahart** [vuejs/vue-router#3372]
### What problem does this feature solve?
When the html includes a `<base>` tag, a default target is specified for all links on the page. For the app I'm working on, this `<base>` tag is only inserted for the production environment so that static assets are loaded through our CDN (all static assets are referenced with relative paths). 
(Note: we currently only build our app once and promote the build artifacts through our different environments (development, staging, production, etc.). Adding the `<base>` tag only for production allows us to do this, otherwise we'd have to rebuild the app for production only, which we don't want to do.)

This causes a unique issue where vue-router works in all environments except production (the only environment where the `<base>` tag is included). This is because vue-router links are relative and follow the target set by the `<base>` tag, which is expected behavior in the browser.

### What does the proposed API look like?
To work around this issue, I would instead like to include the protocol/domain in our base so that router links stay on the same domain (instead of directing the user to the CDN). For example, our router would be initialized as so:
```
const pathBase = "/some-base"
const router = new VueRouter({
  mode: "history",
  base: window.location.protocol + "//" + window.location.host + pathBase,
  routes,
});
```
Right now, providing the protocol/domain in the base option does not work because the base is assumed to be the beginning of a relative path.

**Comment by posva** [comment]
> Right now, providing the protocol/domain in the base option does not work because the base is assumed to be the beginning of a relative path.


Yes, the base should not contain a domain. On client-side navigation, you cannot use the domain part of the URL. You can manually strip it out if necessary, or in your case just provide `pathBase`.

You cannot use a `base` tag to point to a CDN because it will break all the links of your application, this is part of HTML, we cannot change it in vue-router.

Links in Vue Router, especially in hash mode are intentionally relative to work across environments and protocols
