### ISSUE TITLE
Add a clear before handler that is called any time url navigation matches a route (not a route resolution / component).

### ISSUE THREAD

**Issue by sqcrh** [vuejs/vue-router#3389]
### What problem does this feature solve?
It is a common need to create a route guard that checks if a user or resource is authorized or authenticated activating a *route*.  This currently does not exist, and the existing per route beforeEnter handler really aligns with component activation not route activation.  I think it makes more sense to include auth type guards in the url/routing module and not the component because the guard logic is shared among some large percentage of the routes and doesn't have relate specifically to component logic.  And often you want this logic to apply to some routes not all routes. Currently to meet this need you have to:

  1. Watch $route.  Not ideal, because you have to roll your own logic to match the guard to the route.  
  2. Use the global beforeEach.  Again, not ideal because you have to roll your own logic to apply guard to selected routes.  
  3. Use beforeRouteUpdate and beforeRouteEnter in the component.  This isn't ideal because the global auth guards should not be buried in a component and they don't use any component logic.  The guard is related to the route.  
  4. Reach for the beforeEnter handler, which only activates when the route resolution is changed but many people expect it to be called when the the route is matched

I think there is a need for this based the necessity of a call out in the documentation, a handful of issues in the repo, and questions on the forum.  The current route paradigm makes sense and has parity when you are talking about a component (enter, update, leave).  But when you talk about a **route** there is a parity mismatch.  You would expect a route handler to be called an time the route url changes and a route is matched.

I see there is was a proposal to add a beforeUpdate, which I think was rightfully closed with an addition to the component.
https://github.com/vuejs/vue-router/issues/1577

There was also a proposal to deprecate beforeEnter, which I think actually makes sense because again beforeEnter is confusing, but without a replacement i understand why it was closed. 
https://github.com/vuejs/vue-router/issues/2540

Some more relevant issues and questions:
  * https://github.com/vuejs/vue-router/issues/2600
  * https://github.com/vuejs/vue-router/issues/1012
  * https://forum.vuejs.org/t/beforeenter-doesnt-catch-param-changes/97451
  * https://forum.vuejs.org/t/how-to-invoke-beforeenter-everytime-route-param-changes-in-the-same-path/97551
  * https://forum.vuejs.org/t/vue-router-beforeenter-guard-not-working-on-url-change/42300
  * https://forum.vuejs.org/t/vue-router-beforeenter-doesnt-work-properly-for-children-path/20019
  * https://forum.vuejs.org/t/vue-router-trigger-beforeenter-in-all-segments-of-the-url/37462

### What does the proposed API look like?
Deprecate confusing beforeEnter that really aligns with the component not the route and create a handler called before, beforeNavigate, or beforeMatch that is called before a *route* is matched and pushed onto the stack.

**Comment by posva** [comment]
> It is a common need to create a route guard that checks if a user or resource is authorized or authenticated activating a route. This currently does not exist, and the existing per route beforeEnter handler really aligns with component activation not route activation

It is indeed a very common use case, but it does exist... `beforeEnter` and any other guards align with route changes, **not with component mounting/unmounting** (as that can be done with component hooks already).

> Currently to meet this need you have to:
> Use the global beforeEach. Again, not ideal because you have to roll your own logic to apply guard to selected routes.

This is exactly what `meta` fields were designed for: https://router.vuejs.org/guide/advanced/meta.html. In v4, the check doesn't require to go through `matched` anymore, you can directly check `to.meta.requiresAuth` (check [this RFC](https://github.com/vuejs/rfcs/pull/144) for more details)

> But when you talk about a route there is a parity mismatch. You would expect a route handler to be called an time the route url changes and a route is matched.

Navigation guards are triggered based on route changes:

- `beforeEach`: before any navigation
- `beforeEnter`: before entering the route
- `beforeRouteEnter`: before entering the route
- `beforeRouteUpdate`: before the route changes while staying on the same route record (definition of a route with `routes`)
- `beforeRouteLeave`: before the route changes to a different route record

As pointed out in https://github.com/vuejs/vue-router/issues/2540#issuecomment-448971305, `beforeEnter` has a use case, if you find it confusing, I think we should add more details to the documentation at https://router.vuejs.org/guide/advanced/navigation-guards.html#per-route-guard.
I read the different forum posts and issues and it all comes down to `beforeEnter` not being explained correctly on the docs

Ultimately, what you are proposing with `beforeNavigate` is the same as having a global `beforeResolve` with a `meta` property. The reason it's not at a record level is because it would end up in multiple ways to do the same thing, also not exposing developers to `meta` fields which is a powerful tool to customize routing logic specifically for your application. This makes me think that there are a few updates that we can do at https://next.router.vuejs.org/guide/advanced/data-fetching.html#fetching-after-navigation now that `meta` fields are merged. Specifically, it's possible to attach fetching logic to `meta`, resolve it globally for all navigations in a `beforeResolve`, attach data to `meta` (in v4) and read it at component creation and inside `beforeRouteUpdate`. With a store, you only need to attach the data to the store directly in a `beforeResolve` hook and you are done.

If you want to bring new ideas after this, you can do so by opening an RFC at https://github.com/vuejs/rfcs.

**Comment by sqcrh** [comment]
@posva I am very greatful for the time you took reading the feature request. I think you misunderstood the key point and i hope you reconsider my opinion.

I think the widespread confusion is not simply an issue of documentation, i think the api is counter-intuitive to those without a deeper knowledge of the routers internals. I call push without a new url without a param change "enter" is called, i push with new url that maps to a param it isnt. I think many developers expect a per route handler that will be called any time push is called, the url changes, and matches a route. Better documentation would help, maybe moving the comment at the top into the description of before enter, but ideally this wouldnt be necessary.

Upon further further reflection, i think you make a good point that meta does meet the need i discussed without too much additional work. We could just drop a handler into meta, but i do think think the api would be clarified with a generalized before handler that aligns better with when route.push is called, the url changes, and a route is matched.

I am not sure why the comments made on #2540 wouldnt equally apply to a broader before handler, but I admit I don't fully understand the neuances of the use case described there by LinusBorg.

Thats again for your time, i hope you consider this issue as the project moves forward. If you do feel this idea may gain support i would be happy to formulate it into an rfc.

**Comment by sqcrh** [comment]
For others looking for this feature.  Implementing this feature using meta (posva's suggestion) might look something like this:

```javascript
// warning: untested

const routes = [
  {
    name: 'user',
    path: '/users/:id',
    component: User,
    meta: {
      before: guards.authorized,
    },
  },
]

const router = new VueRouter({
  mode: 'history',
  base: process.env.BASE_URL,
  routes,
});

router.beforeEach((to, from, next) => {
  if (to.meta.before) to.meta.before(to, from, next);
  else next();
});
```

**Comment by just7mile** [comment]
> For others looking for this feature. Implementing this feature using meta (posva's suggestion) might look something like this:
> 
> ```js
> // warning: untested
> 
> const routes = [
>   {
>     name: 'user',
>     path: '/users/:id',
>     component: User,
>     meta: {
>       before: guards.authorized,
>     },
>   },
> ]
> 
> const router = new VueRouter({
>   mode: 'history',
>   base: process.env.BASE_URL,
>   routes,
> });
> 
> router.beforeEach((to, from, next) => {
>   if (to.meta.before) to.meta.before(to, from, next);
>   else next();
> });
> ```

This is will not work for the nested routes, where both parent and child have dynamic parameters, so both have meta with before guard. If next function passed to the parent's guard then the chid's guard will be bypassed and vise versa.
