### ISSUE TITLE
Multiple paths for single route

### ISSUE THREAD

**Issue by realnot** [vuejs/vue-router#3394]
### What problem does this feature solve?
This one:  https://github.com/pillarjs/path-to-regexp/issues/235

Current error:

```console
vue-router.esm.js?8c4f:1495 Uncaught TypeError: path.replace is not a function
    at normalizePath (vue-router.esm.js?8c4f:1495)
    at addRouteRecord (vue-router.esm.js?8c4f:1372)
    at eval (vue-router.esm.js?8c4f:1422)
    at Array.forEach (<anonymous>)
    at addRouteRecord (vue-router.esm.js?8c4f:1418)
    at eval (vue-router.esm.js?8c4f:1422)
    at Array.forEach (<anonymous>)
    at addRouteRecord (vue-router.esm.js?8c4f:1418)
    at eval (vue-router.esm.js?8c4f:1422)
    at Array.forEach (<anonymous>)
```

### What does the proposed API look like?

```javascript
path: ['create', ':id'] 
```

Apply the first one if no argument is passed and the second one in other case.

**Comment by posva** [comment]
This was discussed over on the Discord chat, you can use a regular param and pass it to props (https://router.vuejs.org/guide/essentials/passing-props.html#function-mode) `props: to => ({ id: to.params.id == 'created' ? null : 'to.params.id' })`.

You can also create another route:

```js
const commonRouteProperties = { component: ..., etc }

new Router({
  routes: [ { path: '/create', ...commonRouteProperties }, { path: '/:id', ...commonRouteProperties }]
})
```

Putting both routes together would be confusing in terms of active behavior.


Note that you can use alias for multiple paths (although in your scenario it won't work because aliases must share the same params) (https://router.vuejs.org/guide/essentials/redirect-and-alias.html)
