### ISSUE TITLE
route.query & route.meta empty on created in the root component having router-view

### ISSUE THREAD

**Issue by darkylmnx** [vuejs/vue-router#3419]
### Version
3.4.9

### Reproduction link
[https://codesandbox.io/s/vue-router-routes-empty-on-load-jyl0y?file=/src/App.vue](https://codesandbox.io/s/vue-router-routes-empty-on-load-jyl0y?file=/src/App.vue)

### Steps to reproduce
1. Go to the reproduction link
2. After load, check the console

### What is expected?
I was expecting the current route's values to be filled, so as to do conditionnal stuff based on it.

### What is actually happening?
- On created it's empty
- On update it get's filled

My guess is, it's filled only when router-view is resolved.
This makes conditionnals based on route.meta or route.query impossible in the root component holding the router-view.

![image](https://user-images.githubusercontent.com/1426357/102704585-a61a0380-427d-11eb-9883-99d630aab784.png)

**Comment by posva** [comment]
Navigations are asynchronous and decoupled from component mounting. This is necessary because of navigation guards among other things. You can either check for `$route === null` for the start location (initial navigation not resolved yet) or use https://router.vuejs.org/api/#router-onready

Remember to use the [forum](http://forum.vuejs.org/) or the [Discord chat](https://vue-land.js.org/) to ask questions!

**Comment by darkylmnx** [comment]
@posva 

> decoupled from component mounting

But when there isn't the `<router-view />` the router doesn't trigger anything, wether sync or async, as that the expected behaviour?
