### ISSUE TITLE
vue-router positionStore memory leak

### ISSUE THREAD

**Issue by hezedu** [vuejs/vue-router#3445]
### Version
3.4.9

### Reproduction link
[https://hezedu.github.io/SomethingBoring/vue-router-positionstore-memory-leak/index.html](https://hezedu.github.io/SomethingBoring/vue-router-positionstore-memory-leak/index.html)

### Steps to reproduce
I read the source code and found that positionStore has only set, not deleted.

### What is expected?
The data in positionStore should be cleared on history.push() or history.replace().

### What is actually happening?
The memory haspmap:positionStore will continue to grow.

**Comment by hezedu** [comment]
Source code repository:  https://github.com/hezedu/SomethingBoring/tree/master/vue-router-positionstore-memory-leak

**Comment by posva** [comment]
Thank you but this is not a memory leak per se, if you keep navigating and pushing entries into the history, it's normal for it to grow. It would be problematic if it was cleared.

In practice, this will never be a problem because one would need to repeat the action millions of times.

That being said, if you have a reasonable PR proposal to clear them out when unused, I will be very happy to review it
