### ISSUE TITLE
Props function re-evaluates when router-view component updates

### ISSUE THREAD

**Issue by fango256** [vuejs/vue-router#3449]
### Version
3.4.9

### Reproduction link
[https://codesandbox.io/s/broken-morning-oy16n](https://codesandbox.io/s/broken-morning-oy16n)

### Steps to reproduce
Create a props function for a route, update the component that contains "router-view" and the props function re-evaluates.

### What is expected?
The documentation states that the props function is only evaluated on route change.

### What is actually happening?
It seems to re-evaluate when App.vue (router-view parent i presume) updates as well.

---
We use simple stateless props function to convert url string segments into our custom Guid objects and pass them through as Object props to route components. A common pattern for us is to watch for prop changes in our route components and call vuex methods that might cause updates to App.vue (e.g. a loading dialog) - as the props function refires it is causing an infinite loop as we detect a prop change and load again...

Is it expected that the props function re evaluates in this scenario?

**Comment by posva** [comment]
Since RouterView is a functional component, it renders every time its parent (here, App.vue) renders and we need to call the props function to make sure the data is up to date. The solution is to wrap any changes like the timer inside its own component or to wrap the RouterView with a component (much simpler).

The documentation could be more precise but would also end up being confusing for new users. Suggestions to improve docs are always welcome as PR!
