### ISSUE TITLE
There needs to be a way to disable scroll savedPosition

### ISSUE THREAD

**Issue by rhysburnie** [vuejs/vue-router#3462]
### What problem does this feature solve?
There needs to be a way to disable scroll savedPosition

It causes a style recalc and is slowing our app down (we see its the cause in profiler)

We dont use this feature and it seems like something that should be optional

### What does the proposed API look like?
Router init option
```
{
  saveScrollPosition: false, // or similar
}
```

**Comment by rhysburnie** [comment]
We have saved saved 42ms on average by fixing it manually, but an option to disable if you're not using the feature would be great rather than having to patch the package as we will have to do currently.
window.pageYOffset takes 40ish ms

**Comment by posva** [comment]
scrollBehavior is quite essential for SPAs to scroll to the right position when navigating so I don't think it's worth having an option to disable it since **it should always be set**. Saving 42ms is imo not worth the bad UX. The only exception being an SPA where everything fits in the screen in all supported devices **on every single page**. If you really think this is worth pursuing, you should show with practical and boiled down demos that removing such option can make the UX better. Only then, we should consider this
