### ISSUE TITLE
A callback to next() of beforeRouteEnter executed before mounted()

### ISSUE THREAD

**Issue by MaciejJanyska** [vuejs/vue-router#3472]
### Version
3.4.6+

### Reproduction link
[https://codesandbox.io/s/vue-router-346-bgn2c](https://codesandbox.io/s/vue-router-346-bgn2c)

### Steps to reproduce
1. Open "Page 1" from the header

### What is expected?
The right order of the executions of callback in next() of beforeRouteEnter and mounted.

### What is actually happening?
The order of the executions of callback in next() of beforeRouteEnter and mounted are different in different version of view-router
[Here](https://codesandbox.io/s/vue-router-345-hjiv2) is a reproduction link to the same sandbox with vue-router 3.4.5

**Comment by MaciejJanyska** [comment]
#3402

**Comment by MaciejJanyska** [comment]
[Here](https://codesandbox.io/s/vue-router-345-hjiv2) is a reproduction link to the same sandbox with vue-router 3.4.5

**Comment by posva** [comment]
This is likely to be related to https://github.com/vuejs/vue-router/pull/2875.

The behavior is still correct as one shouldn't rely on the ordering among `created`/`mounted` (component lifecycle hooks) and navigation hooks like `beforeRouteEnter()` because the order is not guaranteed and dependant of features like transitions, keep alive and other combinations and therefore, unreliable.

The only thing that is part of the API, and that can be made clearer in docs, is that the component renders once (_DOM updates triggered_) before calling the `next` callbacks.

**Comment by MaciejJanyska** [comment]
Please note that [the same example](https://codesandbox.io/s/vue-router-345-hjiv2) app has completely different behavior relates to the vue-router version. Unfortunately same thing happened in our company's application. It's a pity that the issue was closed immediately :(
