### ISSUE TITLE
[Feaure Request] Reload component when navigating among pages rendered by a same component

### ISSUE THREAD

**Issue by bigradish** [vuejs/vue-router#3479]
### What problem does this feature solve?
Suppose there is a route:
```
{
      path: '/user/:id',
      name: 'userHome',
      component: () => import('./views/user/Home'),
      props: true
    },
```
When navigating from page '/user/1' to page '/user/2', the page is not updated for the rendering component is the same and vue router will not reload it.

### What does the proposed API look like?
Reload the component when any of the route's params changed.

**Comment by posva** [comment]
Pass a `key` attribute to `<router-view>` to force it recreating.

---

Please, next time consider using the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js) for questions first. But feel free to come back and open an issue if it turns out to be a bug 🙂

**Comment by bigradish** [comment]
@posva I just use $router.push to navigate and do not use `<router-view>`. How can I achieve that?

**Comment by BiYuqi** [comment]
> Pass a `key` attribute to `<router-view>` to force it recreating.
> 
> Please, next time consider using the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js) for questions first. But feel free to come back and open an issue if it turns out to be a bug 🙂

when I pass a random key to `router-view`, It seems that the current component is cached and the interface to the page is requested in multiples
