### ISSUE TITLE
this.$router.push用query传参进入一个页面,再进入另一个页面后this.$router.go(-1),类型出现问题

### ISSUE THREAD

**Issue by 1593292349** [vuejs/vue-router#3505]
### Version
3.5.1

### Reproduction link
[https://codepen.io/](https://codepen.io/)

### Steps to reproduce
1. this.$router.push({name:'页面',query:{test:true}});
2.此时页面this.$route.query.test类型是boolean
3.this.$router.push({name:'子页面'})
4.this.$router.go(-1)
5.此时页面this.$route.query.test类型是string

### What is expected?
this.$route.query.test类型始终是boolean不变

### What is actually happening?
this.$route.query.test第一次为boolean,第二次为string

**Comment by posva** [comment]
since the query comes from the URL, you should only pass strings and expect strings when reloading the page.

Next time provide a valid reproduction and open the issue in English.

---

Remember to use the [forum](http://forum.vuejs.org/) or the [Discord chat](https://vue-land.js.org/) to ask questions!
