### ISSUE TITLE
Incorrect router-link status on start app on route '/'

### ISSUE THREAD

**Issue by ariran5** [vuejs/vue-router#3523]
### Version
3.5.1

### Reproduction link
[https://codepen.io/Aria-n/pen/yLgjgWV?editors=1010](https://codepen.io/Aria-n/pen/yLgjgWV?editors=1010)

### Steps to reproduce
I use 4.0.6 version 

1. Configure first variant (https://codepen.io/Aria-n/pen/yLgjgWV?editors=1010)

2. use ```<router-link :to="{name: 'home'}">home</router-link>```

### What is expected?
I expect router link has active class and route home should be matched

### What is actually happening?
router don't match home route

**Comment by posva** [comment]
All root routes should have a `path` that starts with `/`. you cannot have a route `''` and `'/'`.

---

Please, next time consider using the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js) for questions first. But feel free to come back and open an issue if it turns out to be a bug 🙂. Also note this is the repository for Vue Router 3, not 4 (Vue 3)
