### ISSUE TITLE
[feature] declaring sub-routes in the route itself

### ISSUE THREAD

**Issue by PavelPolyakov** [vuejs/vue-router#353]
Hi,

I want to keep it here as feature request.

As we once talked: http://forum.vuejs.org/topic/780/is-that-possible-to-declare-subroutes-inside-the-component/2 .

It would be cool, to have an option to configure sub-routes from the route declaration itself, not only from the global route map.

Regards,

**Comment by yyx990803** [comment]
This is unlikely to be supported because when combined with async component it makes route matching indeterministic, and also requires the entire matching process to be async. However it does not provide much practical advantage over a centralized route map, therefore it's not really worth the tradeoff.
