### ISSUE TITLE
Option to prevent parent route's route.data() firing when subRoute changes?

### ISSUE THREAD

**Issue by fnlctrl** [vuejs/vue-router#357]
For example, with a map like this:
```javascript
'/a': {
  component: A
  subRoute: {
    ':index': {
      component: B
    }
  }
}
```

when transitioning from /a/1 to /a/2,  B's route.data is fired,
but A's route.data is also fired, could there be an option to prevent that?

**Comment by fnlctrl** [comment]
It was because I set canReuse to false...

**Comment by fnlctrl** [comment]
not it wasn't...

**Comment by jsiebach** [comment]
This is expected behavior: http://vuejs.github.io/vue-router/en/pipeline/data.html

> Called on an incoming component during the activation phase, after the activate hook has been resolved. **It is also called when the route has changed and the current component is reused.**

`canReuse` being `true` will make sure the `activate` hook is not re-run.  So you can fetch data for A in the `activate` hook.  

http://vuejs.github.io/vue-router/en/pipeline/activate.html
http://vuejs.github.io/vue-router/en/pipeline/can-reuse.html

**Comment by fnlctrl** [comment]
Thank you! I went on to use `created` hook and completely forgot about this issue, but `activate` hook looks more reasonable.
