### ISSUE TITLE
vue_router__WEBPACK_IMPORTED_MODULE_5__.VueRouter is not a constructor

### ISSUE THREAD

**Issue by smelike** [vuejs/vue-router#3599]
### Version
3.5.2

### Reproduction link
[https://github.com/smelike/vue3-demo](https://github.com/smelike/vue3-demo)

### Steps to reproduce
import { VueRouter } from 'vue-router'

const Home = { template: '<div> Home </div>' }
const Contact = { template: '<div> Contact Us</div>' }
const routes = [
    { path: '/', component: Home },
    { path: '/contact', component: Contact }
]

console.log(VueRouter)
const router = new VueRouter({
    mode: 'history',
    base: __dirname,
    routes: routes
})

### What is expected?
no error

### What is actually happening?
error

**Comment by posva** [comment]
https://router.vuejs.org/installation.html#direct-download-cdn

---

Please, next time consider using the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js) for questions first. But feel free to come back and open an issue if it turns out to be a bug 🙂
