### ISSUE TITLE
Using Vue Router correctly with dynamic/parameterized routes is very difficult and could use improvement

### ISSUE THREAD

**Issue by julie777** [vuejs/vue-router#3609]
### What problem does this feature solve?
APIs, frameworks, and apps should be easy to use correctly and hard to use incorrectly. This is absolutely not the case with Vue 3 and Vue-Router 4 when handling dynamic routes. Routes such as /task/:id interact with component reload optimization in a very non-obvious way. I have spent an entire day testing scenarios, reading everything I can find, and experimenting with lifecycle hooks. I have been limiting myself to the composition API. I still don't have a workable solution for two cases.
1. I navigate from /task/1 to /task/2 either by following a link or changing the URL manually. I will go into more detail following number 2.
2. I navigate to /task/3 where there is no task 3 and I want to redirect to a not found page. 

Concerning number 2, which is simpler, I need to verify that task 3 exists before routing to the page, and instead route to an error page. Separations of concerns would imply that I do this in the task component and not in the routing definitions. Everything I have tried results in the component trying to render before the router.push is executed.

Concerning 1, which I thing will provide the best understanding and help guide us to a solution, I believe that the real problem is how re-using components is being handled.

The issues as I see them:
- there is no action when the URL path changes if it refers to the current page/view
- setup is only called when the view is initially loaded and therefore everything in setup must be computed and reactive to have a chance to work even if the view is triggered to render
- the props or params from the path don't update because they are non-reactive and therefore an onBeforeRouteUpdate must be triggered to manually update the URL parameter.

### What does the proposed API look like?
Being relatively new to Vue (but a software engineer for many years) I am not sure if I can propose the proper solution, although I will gladly participate in discussions and even the coding if desired.

My first thought is that setup could be run again without reloading the component, but I don't know how the implementation works so that may not be an option.

What seems to me like a simple and obvious solution is  to make props reactive (and use props instead of route.params) then the framework would only need to change the dynamic part of the path, set the new value for the related prop and cause the component to render. Of course, it would still be required for the user to understand that setup for a component might only be called once regardless of how many pages/views are navigated to, which is still a potential pitfall for new users.

**Comment by posva** [comment]
Vue Router aims to allow many different patterns when it comes to reactive to route changes, mainly:

- Navigation guards (that's what's triggered when the URL is changed with a push or back/forward buttons)
- Watching the route params (because the route is reactive)

In your scenario, you could use a router navigation guard (not in the component) to avoid navigating if the api returns a not found.

I still need to wait for some changes in Suspense in order to provide an API similar to beforeResolve at component level but I have plans for it 🙂 

Please, next time consider using the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js) for questions first. But feel free to come back and open an issue if it turns out to be a bug 🙂
