### ISSUE TITLE
Why is ‘+’ replaced by ‘ ’？

### ISSUE THREAD

**Issue by silverbulletlee** [vuejs/vue-router#3649]
Why is ‘+’ replaced by ‘’ in 'vue-router-dev/src/util/query.js' line 62?
![image](https://user-images.githubusercontent.com/49614968/138470565-bdda8bd2-0371-4821-9137-14e7df5781b8.png)
Is it because of protocol? for example：http protocol？

**Comment by darrylnoakes** [comment]
From the [W3C document addressing URLs](https://www.w3.org/Addressing/URL/uri-spec.html):

> Within the query string, the plus sign is reserved as shorthand notation for a space. Therefore, real plus signs must be encoded. This method was used to make query URIs easier to pass in systems which did not allow spaces.

Taken from a comment on the accepted answer in [this Stack Overflow thread](https://stackoverflow.com/questions/5450190/how-to-encode-the-plus-symbol-in-a-url).

So yes, it is because of a "protocol" (the URL spec/standard, actually).

**Comment by silverbulletlee** [comment]
> From the [W3C document addressing URLs](https://www.w3.org/Addressing/URL/uri-spec.html):
> 
> > Within the query string, the plus sign is reserved as shorthand notation for a space. Therefore, real plus signs must be encoded. This method was used to make query URIs easier to pass in systems which did not allow spaces.
> 
> Taken from a comment on the accepted answer in [this Stack Overflow thread](https://stackoverflow.com/questions/5450190/how-to-encode-the-plus-symbol-in-a-url).
> 
> So yes, it is because of a "protocol" (the URL spec/standard, actually).

I got it，thank you～
