### ISSUE TITLE
why not support path + params?

### ISSUE THREAD

**Issue by Soumns777** [vuejs/vue-router#3753]
### What problem does this feature solve?
I wonder why params will be ignored if  is added with path, because it will be confused with dynamic routing.

### What does the proposed API look like?
path+params

**Comment by posva** [comment]
Hi, thanks for your interest but Github issues are for bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js).

---

Because the path already contains the params.
