### ISSUE TITLE
[feature or defect]: no `\(` when opening a new group in group path

### ISSUE THREAD

**Issue by tachib-akiko** [vuejs/vue-router#3806]
It sounds a little confusing, so I'm going to interpret it with a valid and invalid path:
| type | path |
| --- | ----- |
| Valid: | `/phim/:season/:chapName(?:(.+\)-)?:chap(\d+)?` |
| Notvalid: | `/phim/:season/:chapName(?:\(.+\)-)?:chap(\d+)?` |

as soon as I add `\` first `(` to mark this as a group, vue-router error message cannot identify the group

Demo: https://paths.esm.dev/?p=AAMeJRyAwQIWLALcM-BMgWII2IPZDhsDpEHIARpvUADEDwGVDdAOQJSA0QJRt1IlE8DcJkEBAAA.&t=/phim/sfweferg/tap-432#

I don't know if this is a feature or a bug, but if it's a feature, please add it as noted in the document. This is kind of confusing for people who use regexp like me.

**Comment by posva** [comment]
This is expected: it's part of the escaping characters, it's a confusing topic on itself but to make it short: `\)` allows to escape the closing parenthesis while `\(` is going to pass that `\` to the regexp because the `(` doesn't need to be escaped.
This is an advanced feature that deals with some internals so it's intentionally not documented to not confuse users further.
