### ISSUE TITLE
[typescript] onReady callback should accept params

### ISSUE THREAD

**Issue by phymo** [vuejs/vue-router#3821]
### Version
3.6.5

### Reproduction link
[codesandbox.io](https://codesandbox.io/s/angry-mcclintock-r9o4t9?file=/src/main.ts)

### Steps to reproduce
``` ts
router.onReady((to) => {
// something
})
```
type defination:
``` ts
onReady(cb: () => void, errorCb?: ErrorHandler): void
```

### What is expected?
onReady hook callback should be able to accept params

### What is actually happening?
ts error:
Argument of type '(to: any) => void' is not assignable to parameter of type '() => void'.ts(2345)

**Comment by posva** [comment]
This definition is intended. You can read the current location from `router.currentLocation`. Note in Vue Router 4, isReady returns a promise (https://router.vuejs.org/api/interfaces/router.html#isready)

---

Please, next time consider using the [forum](http://forum.vuejs.org/), the [Discord server](https://chat.vuejs.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js) for questions first. But feel free to come back and open an issue if it turns out to be a bug 🙂
