### ISSUE TITLE
Terminal directive + v-link at one element

### ISSUE THREAD

**Issue by AStaroverov** [vuejs/vue-router#443]
### Vue.js & vue-router.js version
1.0.20, 0.7.11

### Reproduction Link
https://jsfiddle.net/2so6kua0/6/

### Steps to reproduce
click "Start"

### What is Expected?
Both links work.

### What is actually happening?
First link don't work

and in the DOM we can see
```html
<a class="link" v-link="{path: '/foo'}">v-link + terminal directive</a> <br>
<a class="link v-link-active" href="#!/bar">only v-link</a>
```

**Comment by tejitak** [comment]
When compiler encounters terminal directive, the rest of the directive on the element and its children are not compiled. Please refer the doc.
http://vuejs.org/guide/custom-directive.html#terminal

In the jsfiddle code, the first `a` tag with `v-link` is not applied due to terminal directive, and it produces `a` tag with no `href` link.  It looks work as expected.

**Comment by yyx990803** [comment]
Yes, I think this is working as intended.

**Comment by AStaroverov** [comment]
thanks for the explanation
