### ISSUE TITLE
How to use templates with AJAX?

### ISSUE THREAD

**Issue by Qlipoth** [vuejs/vue-router#458]
Hello How to use templates with AJAX?

I have part of navigation 
https://plnkr.co/edit/sepCINGxSIEcsenPz1th
When I click home I send POST request and get some object with data. After receiving the data, I want to fill in the table specified in the template. But when i reload page i get errors:

`vue.js:991 [Vue warn]: Failed to resolve directive: repeat
vue.js:991 [Vue warn]: Error when evaluating expression "test.id": TypeError: Cannot read property 'id' of undefined
vue.js:991 [Vue warn]: Error when evaluating expression "test.name": TypeError: Cannot read property 'name' of undefined`
How to render this data ?

**Comment by sagaio** [comment]
I think your facing this problem because it's evaluating `v-repeat` before your AJAX data is present. Your solution would be to initialize your array like this in your component:
```
data {
  tests: []
}
```

I don't think the following is the proper or best way to do it but this is one of my route-statements:
```
route: {
  activate: function (transition) {
    this.fetchClients()
    transition.next()
  }
}
```
where `fetchClients()` is a method in the component that contains the AJAX call which sets the corresponding variable to its response like `$set('clients', response.entity.data)`, note that I'm using [rest.js](https://github.com/cujojs/rest). Hope it helps.

**Comment by simplesmiler** [comment]
@Qlipoth if you are using Vue 1.x (not 0.x), then `v-repeat` is no longer there, it was replaced with more robust `v-for`.

---

К слову, у Vue есть небольшой [русскоязычный чятик](https://gitter.im/vuejs-ru/Discussion), где всегда можно спросить помощи, а иногда даже ее получить.

**Comment by Qlipoth** [comment]
@simplesmiler , Денис, спасибо за совет! =)
@sagaio thanks for the answer
