### ISSUE TITLE
why set the initial value for $loadingRouteData to false

### ISSUE THREAD

**Issue by gimm** [vuejs/vue-router#465]
with waitForData: true, $loadingRouteData is set to false, shouldn't it be true instead?

**Comment by agonbina** [comment]
I agree with @gimm, it seems like it makes more sense to set it to true when you are waitForData-ing 😱

**Comment by LinusBorg** [comment]
Not nessessarily. 

When using `waitForData: true`, the component will not be transitioned into until data is loaded. 

When that has happened, and the component is being transitioned into, there is no way that `$loadingRouteData` could be still be `true`, because by definition, all data has been loaded.

And before transitioning into the component, setting `$loadingRouteData` would have no effect since the component is not yet visible anyway.

So it *could* be set to true, but that would not change anything.

**Comment by agonbina** [comment]
I sort of agree with @LinusBorg after using vue-router for some time now. I belive we can _close_ this issue. //cc @gimm
