### ISSUE TITLE
how to get notfound path at redirect?

### ISSUE THREAD

**Issue by atian25** [vuejs/vue-router#540]
visit  `/some_not_found` , then redirect to `/404`

how can I get `/some_not_found`  at 404 component ?

```
router.redirect({
  '*': '/404'
});

Vue.component('404', {
   template: 'the url {{ ??? }} is missing'
});
```

**Comment by LinusBorg** [comment]
Hello ..

Thank your for your interest in this project.

However, your issue is a usage/support question, and the issue tracker is reserved exclusively for bug reports and feature requests.

We encourage you to ask it on the [forum ](http://forum.vuejs.org) or on [gitter](http://gitter.im/vuejs/vue).

**Comment by stevebauman** [comment]
Looking for this and can't find any documentation or any examples anywhere online... Is this still possible somehow? I've searched the forum and I've asked on gitter.

**Comment by LinusBorg** [comment]
Please use the forum.
