### ISSUE TITLE
<router-view></router-view>  transition="bounce"

### ISSUE THREAD

**Issue by ruanzy** [vuejs/vue-router#548]
Attribute v-transition is ignored on component router-view because the component is a fragment instance

 `<template><div class="ibox animated" transition="bounce">...</div></template>` 

We have to write this in each component template. It's so bad.

**Comment by simplesmiler** [comment]
Hello!

This is a usage question, and we encourage you to ask it on [forum](https://forum.vuejs.org/) or [gitter](https://gitter.im/vuejs/vue). We try to use the issue tracker for bug reports and feature requests.

As for the question, transitions can not be applied to fragment instances, because they don't have a root element for the transition classes to live on. You can read more on fragment instances and how to make your instance into non-fragment ones in docs: [Fragment Instance](https://vuejs.org/guide/components.html#Fragment-Instance).
