### ISSUE TITLE
[Feature Request] Componentless named routes

### ISSUE THREAD

**Issue by johannes-z** [vuejs/vue-router#573]
As per the [docs](http://router.vuejs.org/en/basic.html) 

> Each route should map to a component.

Use case: I have an `a` link tag which has a `v-on:click` event handler. I don't want to omit the `href` attribute though, so I have to add the `v-link` attribute as well. But I think it's good practice to not hardcode URLs into links. So what I did was to create a named route. Since named routes are all defined in one place it's very easy to refactor if the URLs might change in the future. The names of the routes should be permanent anyway.

As a quick workaround I did this:

```
'/auth/register': {
  name: 'auth.register',
  component: {}
}
```

If I were to omit the `component: {}` property, it would throw warnings. Is it intended to have named routes without components, and is there a better way of doing this than I did? If not, is this a feature that's going to be added?

**Comment by yyx990803** [comment]
Not sure if that's a proper use case - technically this is not what `vue-router` is for. Component-less routes will make your router-view empty, is that what you want? If not, then you should not be using `v-link` for this purpose. You can treat this path as global state if you want to avoid hard coding URLs.

**Comment by johannes-z** [comment]
> ... technically this is not what vue-router is for ...

Oh, ok? Can I elaborate on the use case? Lets assume you would create this example with static pages (or php or whatever)... for example:
I have a list of tasks (task: `id, name, date, 'done by'`). This list is reachable under `/tasks`. A task defines a link to a GET method on the server `/task/:taskId/select`, that updates the `'done by'` field to the current user, and then sends a redirect to show the task on `/task/:taskId`. 

Using vue-router, the `router-view` would contain my list. When I click on the link an ajax request is sent to the method, and on success I redirect the client to the task itself. In this particular use case it wouldn't matter if the `router-view` is empty or not. I could of course hardcode the link into the `href` attribute of the `a` tag but that just feels wrong.

Also, I don't quite understand what you mean by:

> You can treat this path as global state if you want to avoid hard coding URLs.

**Comment by fnlctrl** [comment]
Are you using redirects to send GET requests?

My understanding of your steps:
1. Open /tasks, it maps to a component that lists tasks
2. Click one `task`, you need the router to redirect to `/task/:taskId/select` (which doesn't map to a component), and then redirect to `/task/:taskId`

The problem is you shouldn't be sending GET requests by manipulating url. We would normally use an http client (fetch, vue-resource, etc.)
It shouldn't work in the first place because when you use front-end routing, it doesn't send a GET request to the server when the url changes.

If you actually use an http client, that would be a non-issue:
1. Open /tasks, it maps to a component that lists tasks
2. Click one `task`, send a GET request (/task/:taskId/select) to the API, redirect to `/task/:taskId` on the callback (or promise.then()).
