### ISSUE TITLE
Lazyload a Template

### ISSUE THREAD

**Issue by OpsRJ** [vuejs/vue-router#574]
Is possible to lazyload a template file? Would be nice if we could lazyload a template file based on some conditions. For example: the data coming from ajax for a field that needs to be populated before the html is rendered.

I´m asking this because we use a lot of web services and if one of them takes a little more time to give me back the response, the html rendered may not be rendered right as some of the fields depends on some data from web service.

**Comment by LinusBorg** [comment]
Hello @OpsRJ 

Thank your for your interest in this project.

However, your issue is a usage/support question (and not about vue-router, but Vue) and the issue tracker is reserved exclusively for bug reports and feature requests.

We encourage you to ask it on the [forum ](http://forum.vuejs.org) or on [gitter](http://gitter.im/vuejs/vue).
