### ISSUE TITLE
v-link-active in a scope of parent component

### ISSUE THREAD

**Issue by cybertino** [vuejs/vue-router#596]
### Vue.js & vue-router.js version

1.0.26, 0.7.13
### Expected

https://jsfiddle.net/93v8pffd/

This example does not work correctly due to #583 
### What is actually happening?

**v-link-active** will not be activated if **v-link** is in child component.
### Reproduction Link

https://jsfiddle.net/90Lpnbgj/1/
### Bug?

This might not be a bug but it would be a good feature which possibly covers a common case.

**Comment by LinusBorg** [comment]
This seems to be a problem of your CSS rather than `v-active-class`.

 The `active` class is properly applied:
![image](https://cloud.githubusercontent.com/assets/1444526/17742537/a76db2d2-64a0-11e6-8225-cc6336ec199d.png)

But your CSS is not correct.

you try to apply a grey background to `.menu-item > .menu-item.active a`, but that will not match beceause there is an element with `.submenu` between the two nested `.menu-item` elements.

Removing `>` makes it work: `.menu-item .menu-item.active a`

https://jsfiddle.net/Linusborg/90Lpnbgj/2/

**Comment by cybertino** [comment]
Sorry, I probably did not explain the issue very well.

Grey background should only be applied to the first-level items. Nested items are highlighted by black font only. Active class is not applied to a parent component - that's what I am looking for. Basically, I want to have active class on the first-level item (as well as nested one) if the nested item was selected. If I have plain HTML (without components) then it works fine - have a look at **Expected** link.

Please re-open this issue. I will try to provide you workaround to present better what I expect.

**Comment by cybertino** [comment]
Here is the workaround: https://jsfiddle.net/east1987/90Lpnbgj/4/
