### ISSUE TITLE
"beforeRouteEnter" causes transition taking effect on initial render without 'appear' attribute

### ISSUE THREAD

**Issue by Centaur** [vuejs/vue-router#657]
### Vue.js & vue-router.js version

2.0.0-rc.5 & 2.0.0-rc.4
### Reproduction Link

https://jsfiddle.net/oldpig/qos7px6j/4/
### Steps to reproduce

run 
### What is Expected?

According to [this](http://rc.vuejs.org/guide/transitions.html#Transitions-on-Initial-Render), transitions should not take effect on initial render if there is no "appear" attribute. So the content of `Page1` component should show up immediately. 
### What is actually happening?

The `fade` transition takes effect and `Page1` component fades in in 3s.

If comment out the empty `beforeRouteEnter` hook, it works as expected.

**Comment by yyx990803** [comment]
Not technically a bug, because "on appear" means the router-view is rendered synchronously with its parent component. An async `beforeRouteEnter` hook means the `router-view` will be rendered async after the parent component is mounted, so it's no longer considered "on appear".

A workaround is using a flag to disable to transition until the router-view is rendered for the first time.
