### ISSUE TITLE
bug when click 'back button' with canDeactivate & canActivate hook

### ISSUE THREAD

**Issue by funkyLover** [vuejs/vue-router#666]
### Vue.js & vue-router.js version

1.x, 0.7.13
### Reproduction Link

the example you run `npm run serve-example` can reproduce this bug.
### Steps to reproduce
1. clone this repo, and run `npm install & npm run serve-example`
2. visit `http://0.0.0.0:8080` and click `inbox` and get into `/inbox` route
3. click `about` and click `yes` when confirm alert, and get into the `/about` route
4. click `back button` of the browser. will receive the alert `cannot navigate from /about to /inbox`
5. click the `back button` again, and you will get into the `/` route
### What is Expected?

it should always alert the `cannot navigate from /about to /inbox` when I click `back button` to navigate from /about to /inbox
### What is actually happening?

it only alert in the first time. the second time it navigate to `/` directly

I test with my own project and the example of this repo. i thought it will be easy to fix this bug, just add a `handler` to `popstate` event inside the [canDeactivate](https://github.com/vuejs/vue-router/blob/dev/src/pipeline.js#L43) and [canActivate](https://github.com/vuejs/vue-router/blob/dev/src/pipeline.js#L63), and remove the `handler` when the transition is aborted in [callHook](https://github.com/vuejs/vue-router/blob/dev/src/transition.js#L209), it work for when use `canDeactivate`, but the `popstate` event was triggered before the `canActivate` hook. I could not find a way completely solve this problem.

**Comment by LinusBorg** [comment]
Hi @funkyLover,

thanks for filing this issue.

When aborting a transition, the router resets the URL to the route we started the transition attempt from, but it uses history.replace() in order to not create a new history entry.

This behaviour is indeed a bit odd when navigating backwards via the back button - but makes sense when traveling forwards through a link: 

Imagine that we try to navigate from `/about` to `/inbox` by a link, so `transition.abort()` is called. If we used `history.push()`, we would now have two history entries for `/about` -> `/inbox` -> `/about` and could never navigate backwards beyond `/inbox`. Therefore, we use `history.replace()` to reset the URL (which is also not perfect).

Unfortunately, there's no nice way to tell weither the history's `pushState` event was triggered by a link or the back/forwards buttons. We would have to count the navigations somehow I guess.

We will look into it.
