### ISSUE TITLE
Please don't deprecate canReuse

### ISSUE THREAD

**Issue by thatandyrose** [vuejs/vue-router#667]
Hey guys,

I've heard `canReuse` is being deprecated and I wanted to plea that this didn't happen!

`canReuse` is extremely helpful. I've seen many issue raised around reloading components and you guys always provide great workarounds. But that is all they are, workarounds. Sometimes I think you need to force reload a component, it's a great tool to have.

if you DO have to remove it... then I think the `router` hooks need some re-thinking. At the moment the `data` hook is extremely confusing. The examples in the doc show an object being passed via the `next` method, but what if you need to download new data, what if it's async.

I guess you could do that in the `data` hook... but the why call it `data`.. it's a strange name.

I think either you let us force reload a component, or there needs to be  dead simple 'routeOnLoad' type event, which says, hey, new route loaded here, do something.

Does that make sense? I tried understanding the `route` hooks documentation and found it quite confusing...

thanks for all the hardwork and if you need a hand with any of this let me know!

**Comment by LinusBorg** [comment]
Hi @thatandyrose,

Thanks for your issue and your input.

Maybe you can start with reading the release notes for vue-router `v2.0.0-beta.1` onwards, in order to familiarize yourself with the new way of doing things.

The exmaples in the `next` branch are also quite helpul: https://github.com/vuejs/vue-router/tree/next/examples

For example:
- The data hook (as most other hooks in components) is also deprecated: https://github.com/vuejs/vue-router/blob/next/examples/data-fetching/Post.vue#L31-L36
- `canReuse`  can be replaced with setting the [`key` attribute](url) on the `<router-view>` element which remove the responsibility from the component (better reusability)

**Comment by thatandyrose** [comment]
@LinusBorg hey there! I thought I might have missed something. I was actually looking to see where `canReuse` was deprecated but i just "heard" it in different forums. Now I know where to go, thank you!

Also, where do I go to see when new stable version of vue things are... stable... :-)

thanks, will check out all that documentation :-)

**Comment by LinusBorg** [comment]
You will see the the official stable releases are out via vuejs.org or just follow us on Twitter: @vuejs
