### ISSUE TITLE
[2.0] Issue when using named view inside keep-alive component

### ISSUE THREAD

**Issue by robinvdvleuten** [vuejs/vue-router#669]
### Vue.js & vue-router.js version

2.0.0-rc.6, 2.0.0-rc.5
### Reproduction Link

http://jsfiddle.net/robinvdvleuten/5sH6A/667/
### Steps to reproduce

Create a default and a named view for a route. Wrap both `router-view` components inside a `keep-alive` component. Then visit the url.
### What is Expected?

I except to see both views and they are both keeped alive when navigating away.
### What is actually happening?

When you visit the url, only the default view is created and shown.

**Comment by fnlctrl** [comment]
Hi, thanks for filling this issue. 
`<keep-alive>` can only manage one dynamic instance, in your case, it's the default `<router-view>`, and the named one isn't managed.
You can read more about `<keep-alive>` here: http://rc.vuejs.org/api/#keep-alive.

As a workaround, you can wrap each `<router-views>` with a `<keep-alive>`:
http://jsfiddle.net/gz3a9bh3/

**Comment by Tech-Nomad** [comment]
You have to use the :key directive to update a component using keep-alive and router-view together with params in the route path like /blog/:slug

<keep-alive>
        <router-view :key="$route.fullPath"></router-view>
</keep-alive>
With this Vue finally updates any new blog posts but caches the previously loaded. Otherwise only the first loaded blog post will be served even the blog/:slug changes all the time.

See also:
https://vuejs.org/v2/api/#key
https://stackoverflow.com/questions/52847979/what-is-router-view-key-route-fullpath
