### ISSUE TITLE
how can i add `class` and `target` to the router link ?

### ISSUE THREAD

**Issue by ccqgithub** [vuejs/vue-router#696]
in vue-router@1, i can do this `<a class="xxx" target="_blank">dfdfds</a>`,

but in docs, i find `<router-link>` has not props about this.

**Comment by LinusBorg** [comment]
Hello @ccqgithub,

Thank your for your interest in this project.

However, your issue is a usage/support question, and the issue tracker is reserved exclusively for bug reports and feature requests. We encourage you to ask it on the [forum ](http://forum.vuejs.org) or on [gitter](http://gitter.im/vuejs/vue).

---

As with all components, all attributes you set on `<router-link>` that aren't props will be added to the root element (the geenrated `<a>` element).

``` js
<router-link to="/path" class="button">
```

The target property won't work though, because the generated `<a>` does not navigate via href="", it navigates with vue-router's Javascript.

to open a new window, use a regular link.
