### ISSUE TITLE
Navigating to the root of root does not work without forward slash

### ISSUE THREAD

**Issue by judocode** [vuejs/vue-router#697]
I would expect that the following code would allow me to navigate to `/online` and load the App component, but it does not load anything. I have to explicitly add the trailing forward slash (`/online/`) in order to get there.

```
var router = new VueRouter({
    history: true,
    root:  '/online'
});

router.map({
    '/': {
      component: App,
      name: 'app'
    },
});
```

**Comment by posva** [comment]
Questions should be posted to the [Gitter chat room](https://gitter.im/vuejs/vue),  [forum](http://forum.vuejs.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js). Thanks.

---

That's working as expected because you're asking the router to match '/' with `/online` as the root --> `/online/`. You can use an empty string to match that path too. Look at https://github.com/vuejs/vue-router/blob/1.0/docs/en/api/redirect.md
Also if you're learning vue-router, you may be interested in using the new version of it, which works for Vue 2. Docs are live at http://router.vuejs.org/

**Comment by judocode** [comment]
@posva Yes I tried an empty string as well. Neither works.

**Comment by LinusBorg** [comment]
Hi jrenton,

Please provide a working reproduction on jsfiddle or a similar service and I will re-open the issue and look into it.
