### ISSUE TITLE
Component tries to access data before beforeRouteEnter() is resolved

### ISSUE THREAD

**Issue by jeroennoten** [vuejs/vue-router#714]
I tried to use 'Fetching Before Navigation', as explained in the docs. However, when data or computed properties are used in a template of a compontent that is registered with a route, they are accessed before `beforeRouteEnter` is resolved. This generates errors in the console when that data is set in the callback of the `next()` call. So the data is not really fetched before navigation, I think?

Example:

``` js
const Post = {
  beforeRouteEnter(to, from, next) {
    next(vm => {
      vm.post = {
        title: 'Hello World'
      };
    })
  },
  data() {
    return {
        post: null
    };
  },
  template: '<div>{{ post.title }}</div>'
};
```

Live: https://jsfiddle.net/4tpzm3e1/264/

This generates an error: `Cannot read property 'title' of null`, which means that `post.title` was accessed, before `next()` was called.

Is this expected behavior? It is not really convenient, this 'pre-navigation data fetching' was better in vue-router 1.

**Comment by fnlctrl** [comment]
Hi, thanks for filling this issue.

> So the data is not really fetched before navigation, I think?
> If you add a setTimeout for simulation, you will see that the component really is created after the next hook is called. https://jsfiddle.net/7ahu614m/

So what really was happening:
1. `next` called
2. Component instantiated, throws error because it tried to access `post.title` while it was `null`
3. Component is passed as `vm` to `next`'s callback, vm.post is set correctly.

Therefore, you need to define the `post`'s default value as an empty object, instead of null.

Also, here is a helpful guide about this: http://vuejs.org/guide/reactivity.html#Declaring-Reactive-Properties

**Comment by jeroennoten** [comment]
Allright, thank you!

**Comment by namelesstwice** [comment]
Hi! I am pretty new to Vue and now i am facing the same problem. Ok, i get that i can fix it by defining default vaues, but can you clear the following thing: can Vue possibly render any intermediate state of the component when the callback passed to `next` is not executed yet?
