### ISSUE TITLE
router view is not rendering.

### ISSUE THREAD

**Issue by muhammadfaizan** [vuejs/vue-router#730]
I tried using route in my app, 
I am loading my app via vue-loader.
before migration the app was working fine, now app is rendering but router-view is not rendering, i have done the changes needed, that is to make route an array and work that way

`<div>
    <c-header></c-header>
    router should come here
    <router-view></router-view>
    <c-footer></c-footer>
</div>`

but my app rendered HTML has <router-view> shown as HTML comment.
   These are the version I am using...
   "vue": "^2.0.1",
    "vue-router": "^2.0.0",
    "vue-timeago": "^2.1.3"

**Comment by LinusBorg** [comment]
Hello @muhammadfaizan

Thank your for your interest in this project.

However, your issue is a usage/support question, and the issue tracker is reserved exclusively for bug reports and feature requests.

We encourage you to ask it on the [forum ](http://forum.vuejs.org) , [Stack Overflow](http://stackoverflow.com/questions/tagged/vue.js) or on [gitter](http://gitter.im/vuejs/vue) and are happy to help you out there.

When posting there, consider providing more infromation, like the actual router config.

Thank you.
