### ISSUE TITLE
<router-link> cannot appear in a <table>

### ISSUE THREAD

**Issue by Pandazaur** [vuejs/vue-router#734]
Hello,

Since Vue 2.0 we must use `<router-link>` tag to redirect in the HTML templates, but how can we do now in `<table>` tags ?

When I'm building with webpack it tells me:

``` bash
✘ 1 problem (1 error, 0 warnings)

Errors:
 1  http://eslint.org/docs/rules/no-undef

 ERROR in ./src/pages/offer/CampaignsPage.vue
                     </router-link>
                        <router-link :to="{ name: 'offer-edit', params: { id: offer.id }}">
                        ^
                             <td class="clicable">{{offer.name}}</td>

  Tag <router-link> cannot appear inside <table> due to HTML content restrictions. It will be hoisted out of <table> by the browser.
```

Is there a solution ? Or should i pass through a `@click` event ?

**Comment by LinusBorg** [comment]
Where does this error come from? It's not a Vue or Vue-router error as far as I can tell. I have not encountered it so far.

Are you having some custom HTML linting going on?

This statement is also wrong: since Vue converts the template into a render function long before the browser could ever see it and complain about it, this is a non-issue with .vue files.

Please provide a reproduction repo or something if you think this error is from Vue/vue-router.

**Comment by yyx990803** [comment]
You are using an outdated version of `vue-loader`. Upgrade to 9.x.
