### ISSUE TITLE
 bug: vue-router2.0 integrate with vue2.0 and vuex2.0 ,router.push(path) twice can not call watch $route function

### ISSUE THREAD

**Issue by lenvonsam** [vuejs/vue-router#736]
first part router config:
![1](https://cloud.githubusercontent.com/assets/10168476/19196548/97790cda-8ce8-11e6-8983-baa09b0ed6f0.png)
second part App.vue watch $route code
![2](https://cloud.githubusercontent.com/assets/10168476/19196634/e2c25822-8ce8-11e6-91e2-19bc0d2f3d4b.png)
third part sidebar component router-link to each view:
![3](https://cloud.githubusercontent.com/assets/10168476/19197028/6a28302e-8cea-11e6-97a7-15559067f764.png)

![4](https://cloud.githubusercontent.com/assets/10168476/19197019/5fdabc18-8cea-11e6-9861-93bc5216dc78.png)

when i refresh page or click the router-link the first time ,everything is ok ,and watch $route can call its bind function,but when click A -> B, B->A ，in this case , the app.vue watch $route can not call its bind function , how to resolve this problem , i am grateful for you very much.

**Comment by posva** [comment]
Please, ask questions on the [forum](http://forum.vuejs.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js).

Also, include real code instead of screenshots, even better create a little demo. You can use this as a starting point (https://jsfiddle.net/posva/wtpuevc6/). That way people is more likely to help you.

If it turns out you actually found a bug, come back here and open an issue with a repro (link to a jsfiddle)

**Comment by lenvonsam** [comment]
@posva Thank for your advice.I spent two days resolving this problem which raised by jquery datatable erorr , thanks  god&best wish
