### ISSUE TITLE
@click.prevent  don't work in router-link

### ISSUE THREAD

**Issue by lifetea** [vuejs/vue-router#743]
<router-link class="touchable" @click.prevent="toggle(item)" :to="{ name: item.link }"></router-link>

**Comment by posva** [comment]
Please ask questions on the [forum](http://forum.vuejs.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js).

---

router-link adds the prevent  for you. If you want to handle the  click yourself, you don't need a router-link component

**Comment by Emiya0306** [comment]
@posva Maybe I want to get the effect just like [this page](http://seantheme.com/color-admin-v2.1/admin/html/email_inbox_v2.html) sidebar. Main menu button, which has submenus, will get the active class when I click the submenu, but at the same time, I don't want to user click the main button to link another page. I think it is a little trouble to do this in the code. If vue-router has the feature just check the router match and add class. It will be more good.

**Comment by LinusBorg** [comment]
your issue is a usage/support question, and the issue tracker is reserved exclusively for bug reports and feature requests (as outlined in our [Contributing Guide](https://github.com/vuejs/vue/blob/dev/.github/CONTRIBUTING.md)).

We encourage you to ask it on the [forum ](http://forum.vuejs.org) , [Stack Overflow](http://stackoverflow.com/questions/tagged/vue.js) or on [gitter](http://gitter.im/vuejs/vue) and are happy to help you out there.
