### ISSUE TITLE
Watch callback not triggered for props of router-view

### ISSUE THREAD

**Issue by Darkside73** [vuejs/vue-router#765]
If a component prop passed through a nested route been changed, `watch` callback does not triggered: http://jsfiddle.net/jh9pk6jc/1/
Not sure if it is a vue-router issue

**Comment by LinusBorg** [comment]
Your demo does not demonstrate a situation where the prop is changed. 

And watches do not trigger on first render, only on after changes to the watched property. You can change that with the `immediate` option, see the Vue docs.

**Comment by Darkside73** [comment]
The prop is changed if `$route.params.id` changed and vue-router docs say, that the same instance of component  is used over navigation. So I've expected `watch` been triggered

**Comment by LinusBorg** [comment]
... but in your example the id never changes. It's always `foo` in all routes that your example contains.

**Comment by Darkside73** [comment]
No. You've probably taken a look at the links names, but path do change (see `to` prop):

``` vue
<router-link to="/user/foo">/user/foo</router-link>
<router-link to="/user/bar/profile">/user/foo/profile</router-link>
<router-link to="/user/baz/posts">/user/foo/posts</router-link>
```

**Comment by LinusBorg** [comment]
Oh.

I didn't express myself correctly, but the point is the same:

The `UserHome` components only gets rendered when you visits `/user/:id`, not when you visit one of the other routes, `user/:id/profile`, for example. 

As you only have one `<router-link>` that renders the `UserHome` component (`/user/foo`), the id will not change _from the perspective of this component_. It will only ever receive the _intial value_ `foo` of that prop during render.  That the id is `bar` when you are in _another_ routehas no effect on `UserHome`, because the component will not be active in that moment.

So: The watch will only be triggered if you switch from one route like `/user/foo` to the _same_ route with a different id, e.g. `/user/bar` - not a _different_ route, e.g. `/user/bar/profile`

To demonstrate this, I have added a second route that will render `UserHome` as well,  `/user/bar`, here:

http://jsfiddle.net/Linusborg/jh9pk6jc/3/

If you switch between the first two links, you will see the watch being triggered in the console. 

And again: If it should trigger immediatly, use the [`immediate` option](https://vuejs.org/api/#vm-watch)

**Comment by Darkside73** [comment]
Got it. Thanks for explanations

**Comment by Darkside73** [comment]
This misunderstanding appeared from the vue-router docs https://router.vuejs.org/en/essentials/dynamic-matching.html:

> One thing to note when using routes with params is that when the user navigates from /user/foo to /user/bar, the same component instance will be reused. Since both routes render the same component, this is more efficient than destroying the old instance and then creating a new one. However, this also means that the lifecycle hooks of the component will not be called.

"_Since both routes render the same component..._" does not sound right, since we speaking about **same route** with **different params**

**Comment by LinusBorg** [comment]
The functionality also works across different routes:

http://jsfiddle.net/Linusborg/jh9pk6jc/5/

as long as it renderes the **same** component - that was your problem, not routes / route-params.
