### ISSUE TITLE
[2.0] How can I use router with vuex (in action file)

### ISSUE THREAD

**Issue by noomerzx** [vuejs/vue-router#778]
I completed migrate from vue 1.0 to 2.0 and have some problem
- I can't use router in my action anymore in vue 2.0 I don't know why because in 1.0 I can do that. I dont have to import router in action to use it in 1.0 but 2.0 I can't use router no matter which way.
- I seperate vue resource to api.js file and import router for change page when hooked error 401 on http.interceptors but... I can't use vue router here to.

**Comment by LinusBorg** [comment]
Hello @noomerzx 

Thank your for your interest in this project.

However, your issue is a usage/support question, and the issue tracker is reserved exclusively for bug reports and feature requests.

We encourage you to ask it on the [forum ](http://forum.vuejs.org) , [Stack Overflow](http://stackoverflow.com/questions/tagged/vue.js) or on [gitter](http://gitter.im/vuejs/vue) and are happy to help you out there.
