### ISSUE TITLE
Vue Router (router-link) does not update properly if using tag

### ISSUE THREAD

**Issue by lukepolo** [vuejs/vue-router#810]
### Vue.js version

vue@^2.0.1:
  version "2.0.3"

vuex@^2.0.0:
  version "2.0.0"

vue-router@^2.0.0:
  version "2.0.1"
### Reproduction Link

https://jsfiddle.net/Linusborg/b40xckws/2/
### Steps to reproduce

Hover over link : you should see 

https://fiddle.jshell.net/site/1

click on button

you will see the that the site id has changed but the link does not
### What is Expected?

You should click the button and see 

https://fiddle.jshell.net/site/4
### What is actually happening?

You see https://fiddle.jshell.net/site/1
## how to fix

Remove tag on`router-link`

**Comment by LinusBorg** [comment]
Seems to be a bug. 

And maybe we even have to move this back to the Vue repo, sorry ^^

Because the link-component itself works as it should, the new href _is_ being added to the vnode of the anchro tag. It's just that the DOM doesn't get updated as it should (whcih would be Vue's job again).

But we will have to take a closer look to tell exactly.

**Comment by lukepolo** [comment]
feel free to re-open the other one ,ill edit so it reeds the same as before~
