### ISSUE TITLE
QuotaExceededError on scroll , Safari private mode

### ISSUE THREAD

**Issue by tripper54** [vuejs/vue-router#813]
Safari private mode throws a QuotaExceededError whenever you try to push something into localstorage.

With vue-router this appears to be happening on scroll in saveScrollPosition.

**Comment by LinusBorg** [comment]
Hm yeah, In private mode, websites can't save anything to localstorage.

Will check out if we can prevent the error from appearing.

**Comment by MatteoGabriele** [comment]
I've seen this error recently and I had to disable this nice feature.
I wrote this little [module](https://www.npmjs.com/package/storage-helper) which handles browser storage: it tries to save in the localStorage in first place, then it tries cookies, which are better supported in private windows. If can't support cookies either, maybe because the user is blocking them, a plain object will kick in to save data. 

Don't know if can help to fix the issue quickly :)
