### ISSUE TITLE
beforeRouteLeave guard didn't prevent the change of the browser's history.

### ISSUE THREAD

**Issue by luxp** [vuejs/vue-router#814]
``` js
this.$router.go(-1)
```

``` js
beforeRouteLeave (to, from, next) {
      next(false)
}
```

When I using the beforeRouteLeave guard in this way, vueRouter prevent the route navigation, but I found that the browser's history has been changed to the previous one.

**Comment by LinusBorg** [comment]
Hello @luxp 

thank you for your filing this issue.

Please follow the [guidelines](https://github.com/vuejs/vue/blob/dev/CONTRIBUTING.md) on how to report an issue. In particular, provide an example on www.jsfiddle.net (or a similar service) that reproduces the problem.

Thank you.

**Comment by luxp** [comment]
I made a simple demo
https://jsfiddle.net/luxp/xcz0oh08/
This is issue can be reproduced in this demo.

**Comment by fnlctrl** [comment]
This is working as intended. Browser history is changed before vue-router reacts to the change, so that it works consistently for in-app redirection and direct url visits. And since browser history API only provided `push` and `replace`, without the `delete`(or `pop`) method the browser history stack cannot be properly reflect the router state.
