### ISSUE TITLE
is there any way to observe the router.back() method to do page transition

### ISSUE THREAD

**Issue by yixiaohuan** [vuejs/vue-router#882]
I have encounter a problem these days.

There are two action here . 
First is '/work/detail', the second is '/personal/detail'

At the first page. a button link to the '/personal/detail, i open the  page with a slideInRight transition.

At the second page, when I click the back button(invoke router.back()), i go back to the first page. 
I want to render a slideInLeft transition(Opposite from the enter transition).

there is no method to ensure the router behavior is invoked by the back() or push().
the router.beforeEach is not enough for me. Is there any solutions? THX

**Comment by LinusBorg** [comment]
Hello @yixiaohuan 

Thank your for your interest in this project.

However, your issue is a usage/support question, and the issue tracker is reserved exclusively for bug reports and feature requests.

We encourage you to ask it on the [forum ](http://forum.vuejs.org) , [Stack Overflow](http://stackoverflow.com/questions/tagged/vue.js) or on [gitter](http://gitter.im/vuejs/vue) and are happy to help you out there.
