### ISSUE TITLE
`beforeRouteLeave` NOT called in a second time of `history.back()`

### ISSUE THREAD

**Issue by vvenv** [vuejs/vue-router#887]
when i call `history.back()` twice, the `beforeRouteLeave` hook will NOT be called in the 2nd time

Reproduction:
http://plato.crossjs.com/test.html#/

**Comment by fnlctrl** [comment]
Hi, thanks for filling this issue. 
The behavior of clicking the browser back button is just as expected, because `beforeRouteLeave` doesn't stop the browser from changing the history record, but rather tries to fix it after the changes are made. This is to ensure consistent behavior for in-app redirections and direct url visits.

So, if you directly opened the link and click '/foo', there will be two history records: `/` and `/foo`(current). When the back button is clicked, browser changes the history to `/`, and `beforeRouteLeave` tries to fix it, so the browser history becomes `/foo`(current) and `/foo`. At this point the back button is disabled.

If you opened a blank page, then visit the link and click '/foo', you have 3 history records: `blank page`, `/` and `/foo`(current), so after the first click the history becomes `blank page`, `/foo`(current), `/foo`. This time the back button can be clicked again, and `beforeRouteLeave` isn't called since you're not leaving `foo`, but actually leaving of the app to `blank page`.

**Comment by vvenv** [comment]
Should guards keep the history records the same as current?

Like:
- Current history records is: `blank page`, `/` and `/foo`(current).
- Then click the back button.
- Current history records is: `blank page`, `/` and `/foo`(current).

**Comment by vvenv** [comment]
@fnlctrl 
Use `location.assign` instead of `location.replace` in `replaceHash()` will resolve this issue.
https://github.com/vuejs/vue-router/blob/dev/src/history/hash.js#L90

Should we do it?

**Comment by fnlctrl** [comment]
@crossjs Sorry but `location.assign` cannot be used to replace `location.replace` because it will create a new record, instead of changing the current one in-place.
