### ISSUE TITLE
Dynamically add routes

### ISSUE THREAD

**Issue by nkostadinov** [vuejs/vue-router#888]
Could someone give me an example how to add routes(in browser) after the object is initialized. I'm trying to use createMatcher but there is not such function.

**Comment by LinusBorg** [comment]
There's no public API for that.

**Comment by LinusBorg** [comment]
There is no publi API to do this.

**Comment by nkostadinov** [comment]
The migration guide states that this is the way to add routes to already created router - https://vuejs.org/v2/guide/migration-vue-router.html#router-on-removed. Since this function seems private is there a way to achieve this ?

**Comment by LinusBorg** [comment]
Hm, that section is new to me personally. and createMatcher is definitely not an export of the VueRouter instance. You _can_ import it, though: `import { createMatcher } from 'vue-router/create-matcher'`, but that it suboptimal because you will essentially duplicate this code, as it is already compiled in `vue-router.js`.

/ping @fnlctrl

**Comment by nkostadinov** [comment]
Yes, I saw it is compiled but it is not in the prototype. I think it will be good if this function is available so we can add new routes because I cannot find another way to do it.

**Comment by fnlctrl** [comment]
@LinusBorg Haven't read that section either.. Maybe we can add `createMatcher` to the exports? 
Though I don't really think dynamically adding routes would be a good practice, since it would make the route map dependent on app state, and make the availability of urls unpredictable. e.g. one may want to share a link `/foo`, and be surprised that it can't be accessed by others (since `/foo` is dynamically registered later in app). I think it's better to stick with the `static route map` + `route authentication` approach, instead of dynamically registering routes.

**Comment by nkostadinov** [comment]
I agree that this may lead to inconsistencies but in my case I want to load entire vue module(s) with ajax call from a PHP backend and I don't know all routes that shall be available so I thought of registering them later.

**Comment by fnlctrl** [comment]
@nkostadinov Have you tried starting the app after the ajax call?

**Comment by nkostadinov** [comment]
By the time the dashboard loads I am not aware of the modules in order to add their routes. My idea was when the user clicks on a link to load the template, routes and script from ajax call and then navigate to the new module - this way the module becomes standalone and self registering. Currently I'm stack at adding routes.

**Comment by yyx990803** [comment]
closed via 0e0fac9
