### ISSUE TITLE
How could next(path) act like a replace rather than push

### ISSUE THREAD

**Issue by hiyuki** [vuejs/vue-router#897]
Now I achieve it by next(false),router.replace(path).

But I hope I can add some option to indicate next() to make a replace jump.

Thank you.

**Comment by fnlctrl** [comment]
Hmm.. could be useful. Maybe a second parameter for next? `next(path, useReplace)`
/ping @posva @LinusBorg

**Comment by posva** [comment]
@hiyuki Why do you need a replace rather than a push? Can you tell us a bit about your use case, please?

**Comment by hiyuki** [comment]
I use it as a conditional redirect and doesn't allow user to go back

**Comment by x531tanxl** [comment]
I use this in beforeEach. When I click the back button at the first time, it won't do anything. I need to click twice. I had to replace next with router.replace after [#795](https://github.com/vuejs/vue-router/issues/795) fixed.

**Comment by jazoom** [comment]
This is exactly the same problem I'm having. I'm glad this issue is here because I was hunting around for an option to pass to `next()` since the option's fields (such as `query`) are not documented (`path` is the only one documented).

And yes, $router.go(-1) needs to be called twice (or back button pressed twice) after a redirect. Replace seems to be necessary in this case.

**Comment by posva** [comment]
@fnlctrl Aborting the navigation doesn't remove it from history?

**Comment by fnlctrl** [comment]
No.. there's no browser API to remove anything from history. Therefore,
every navigation is made directly, and aborting a transition will make
vue-router replace the current history with the previous one.
