### ISSUE TITLE
Using Dynamic Route Matching can not Multiple calle beforeRouteEnter  

### ISSUE THREAD

**Issue by ediaos** [vuejs/vue-router#903]
then I using dynamic route matching , the beforeRouteEnter and activated can not call .
- vue : "2.0.5"
- vue-router: "2.0.1"

Demo1
[fiddle demo1](https://jsfiddle.net/EDiaos/hmu845w5/6/)
my router :
```
const router = new VueRouter({
  routes: [
    { path: '/hello/:id', component: Hello },
    { path: '/newtestpage', component: NewTestPage }
  ]
})
```
//Test 1
1. current page is  '/hello/0'
2. navigation to '/hello/1'
3. the beforeRouteEnter can not be call

//Test 2
1. current page is '/hello/0'
2. navigation to '/newtestpage'
3. navigation to '/hello/1'
4. the beforeRouteEnter will calling

--------------------------------------------
Demo2:
[github demo2](https://github.com/EDiaos/vuerouteractivatedbugdemo)
then i using` import hello compontent`
  I run Test1 , Test2 ,the beforeRouteEnter never be call.

-------------------------------
Demo1 and Demo2 run Test1 and Test2 can not call activated too.
I feel that these state is not normal, dynamic routing, it should also have the characteristics of the new page, navigation events and activated  can be called

**Comment by decademoon** [comment]
`beforeRouteEnter` won't be called when navigating from `/hello/0` to `/hello/1` because it is the same component. Route components are reused whenever possible. If you want to detect when the `id` param changes, then you'll need to watch `$route`.

Here's an updated fiddle: https://jsfiddle.net/hmu845w5/8/
Documentation: [Data Fetching](https://router.vuejs.org/en/advanced/data-fetching.html)

**Comment by fnlctrl** [comment]
^ As above. @decademoon Thanks for the explanation, though more accurately, it is because `/hello/0` and `/hello/1` are the same route. Same components used on different routes will still trigger route guards.

**Comment by ediaos** [comment]
Thank you very much, this can solve most problems.
But I have a problem here because the cache lead.
1.  `hello.vue` is a built-in iframe page control, in fact my project using the `WebView.vue` 
2.  From the `/hello/0` navigation to `/hello/1` will have its own iframe url
3.  When the network is not good, from the `/hello/0` navigation to `/hello/1`, iframe will keep the `/hello/0` iframe history page for a while
4. I try to detect `$route` with a `watch` and trigger `update`
5. At this point, I try to reset the url, but the result remains the same
6. I execute this. `$ Refs.iframe.contentWindow.document.body.innerText=""`
7. Error is thrown as follows:
   - [Vue warn]: Error in watcher "$route" 
   - DOMException: Blocked a frame with origin "http://localhost:8080" from accessing a cross-origin frame
8. In this case, looks like `$watch` is not very useful

I think, if we can give the router-view to provide a property to control the dynamic routing of the same page is better reuse, so that users may be more flexible control of some page reuse and state recovery.

@fnlctrl @decademoon

**Comment by decademoon** [comment]
@EDiaos 

> When the network is not good, from the /hello/0 navigation to /hello/1, iframe will keep the /hello/0 iframe history page for a while

That's typical for any web browser. The contents of the iframe isn't cleared immediately as soon as the url changes; is that what you want to do? Maybe you could try setting the iframe's src to `about:blank` to clear it.

> Error is thrown: DOMException: Blocked a frame with origin "http://localhost:8080" from accessing a cross-origin frame

That exception has nothing to do with Vue, the iframe is sandboxed and you are not allowed to access its document due to cross-origin restrictions (the origin of the document hosting the iframe doesn't match the origin of the document inside the iframe).

**Comment by ediaos** [comment]
@decademoon 
YE, I try set the iframe's src to `about:blank` , but next step i need to set the src to new url., or vue binding auto will chuanging the src to new url.  The result remains the same. 

I will continue to find an immediate way to clean up the iframe page. I think some of the complex pages sometimes need to maintain or remove some complex state, if our vue-router future users can control whether the reuse of the page, I think the solution will become very simple problem.
