### ISSUE TITLE
<router-link> with "li" tag property doesn't work

### ISSUE THREAD

**Issue by nigore** [vuejs/vue-router#912]
Versions:
vue.js: 2.0.1
vue-router: 2.0.1

Demo without tag="li" property - works as expected
http://jsfiddle.net/igore21/2jwpm1tt/

Demo with tag="li" property - does not work as expected
http://jsfiddle.net/igore21/95crnjsg/

Expected behaviour:
1. Click "Go to AAA"
It shows: "Foo" (url: /aaa/foo) and "Bar" (url: /aaa/bar)
2. Click "Go to BBB"
it shows: "Foo" (url: /bbb/foo) and "Bar" (url: /bbb/bar)

Bug:
In 2nd step, when you click on "Go to BBB", it shows "Foo" which url is "/aaa/foo" instead of "/bbb/foo". Similar for "Bar" - "/aaa/bar" instead of "/bbb/bar"

**Comment by LinusBorg** [comment]
Removed the bug label again as i'm not sure right now weither this would be "expected" behaviour:

If you put a `:key="$route.params.prefix"` on the router-link (or the nested <a> element, it works as expected: http://jsfiddle.net/Linusborg/95crnjsg/1/

So it's Vue re-using the "wrong" element without the key. now we have to check weither it can be done without the key.

**Comment by LinusBorg** [comment]
...and the label is back. 

The issue is that, since the parent component of the `<router-link>` was not re-rendered, the content of `$slot.default`is still the same, and the diffing doesn't realize that it should replace listeners on the `<a>` element

I think we should be able to solve this, e.g. by adding a key to the vdom element of the `<a>` (if there is'nt one already) somewhere around here:

https://github.com/vuejs/vue-router/blob/dev/src/components/link.js#L74-L91

Will look into this on the weekend hopefully.

**Comment by LinusBorg** [comment]
Update: You used old versions in your fiddle (RC versions from the pre-release stage).

With latest versions this works fine: http://jsfiddle.net/Linusborg/95crnjsg/3/

**Comment by nigore** [comment]
Updated the version, now it works!

Thanks!
