### ISSUE TITLE
Can't get the router to route.

### ISSUE THREAD

**Issue by JZ-at-TP** [vuejs/vue-router#913]
This is my router:

```
import App from './components/app.vue';
import Home from './components/home.vue';
import Key from './components/key.vue';
import Show from './components/show.vue';

var router = new VueRouter({
  mode: 'history',
  base: __dirname,
  routes:[
    { path: '/home', name: 'Home', component: Home },
    { path: '/key',  name: 'Key',  component: Key  },
    { path: '/show', name: 'Show', component: Show },

     // catch all redirect
    { path: '*', redirect: '/home' }
  ]
});
```

Unfortunately it doesn't work. I have the ' router-view ' in my app.vue but the redirect isn't working and if I go directly to a route, it's not showing the component.

My app is initialized like so.

```
var app = new Vue({
  router,
  render: (h) => h(App)
}).$mount('#app');

```

I'm at a loss at this point. The app.vue component is displayed but no component in the router is.

Versions:

```
    "vue": "2.0.7",
    "vue-resource": "1.0.3",
    "vue-router": "2.0.2"
```

**Comment by yyx990803** [comment]
Try removing the `base: __dirname`?

**Comment by LinusBorg** [comment]
Hello @JZ-at-TP 

Thank your for your interest in this project.

However, your issue is a usage/support question, and the issue tracker is reserved exclusively for bug reports and feature requests (as outlined in our [Contributing Guide](https://github.com/vuejs/vue/blob/dev/.github/CONTRIBUTING.md)).

We encourage you to ask it on the [forum ](http://forum.vuejs.org) , [Stack Overflow](http://stackoverflow.com/questions/tagged/vue.js) or on [gitter](http://gitter.im/vuejs/vue) and are happy to help you out there.

**Comment by JZ-at-TP** [comment]
Hi @yyx990803 I removed it but no change. I don't think I need it either I've been copy & pasting code trying to get a simple app working. But still, nothing shows up in the `router-view`
