### ISSUE TITLE
[question] Two way binding between controller in routerview and parent

### ISSUE THREAD

**Issue by vondiplo** [vuejs/vue-router#919]
Hello,

I have a single page application which consists of a:

1. A navigation component which contains a title and a menu
2. A router-view 

I'd like each component being presented in the router view which correspond to a state in the router, to update the title of the navigation component. How to go about passing the parameters from the components in the router-view to the outer navigation component.

I'm using vue 2.0

**Comment by LinusBorg** [comment]
Hello @vondiplo

Thank your for your interest in this project.

However, your issue is a usage/support question, and the issue tracker is reserved exclusively for bug reports and feature requests (as outlined in our [Contributing Guide](https://github.com/vuejs/vue/blob/dev/.github/CONTRIBUTING.md)).

We encourage you to ask it on the [forum ](http://forum.vuejs.org) , [Stack Overflow](http://stackoverflow.com/questions/tagged/vue.js) or on [gitter](http://gitter.im/vuejs/vue) and are happy to help you out there.
