### ISSUE TITLE
Error when rendering component after npm update

### ISSUE THREAD

**Issue by franckysolo** [vuejs/vue-router#930]
Hello,
i'm developing a vuejs large scale api
i made a npm update of vue-loader, then i run my vue api dev and an error raise in console 
```js
[Vue warn]  Error when rendering component <router-link> :
(unknown) TypeError: Cannot read property 'path' of undefined
```
package.json
```
"dependencies": {
    ...some dependencies...,
    "vee-validate": "^2.0.0-beta.13",
    "vue": "^2.0.7",
    "vue-resource": "^1.0.3",
    "vue-router": "^2.0.2",
    "vuex": "^2.0.0",
    "vuex-persistedstate": "^0.3.0",
    "vuex-router-sync": "^3.0.0"
  },
"devDependencies": {
 ...some devDependencies...,
    "url-loader": "^0.5.7",
    "vue-loader": "^9.9.5",  // old version was "vue-loader": "^9.4.0"
    "vue-style-loader": "^1.0.0",
    "webpack": "^1.13.2",
    "webpack-dev-middleware": "^1.8.3",
    "webpack-hot-middleware": "^2.12.2",
    "webpack-merge": "^0.14.1"
}
```
I've got a jquery fullcalendar in my home page it's not displaying anymore since i've made the update!
I don't know if there is a relation between them, but i do nothing more than an update!
Any idea?
Thanks for your help

**Comment by fnlctrl** [comment]
Hi, thanks for filling this issue. Please provide more information, including a snippet of the code that caused the problem, and full stack traces, thanks!

**Comment by p4m** [comment]
I have the same problem. Downgraded to 2.0.1 solved the problem for me.

It's no problem to place the component on a page. The error occurs when I click the link provided by the router-link. When using a normal object (instead of a component) the link works fine.

`Vue.component('my-foo', {
  template: '<div>This component won't load</p>'});`

`const routes = [
  { path: '/card', component: 'my-foo' }
]`

`
<router-link to="/card">Go to Card</router-link>
<router-view></router-view>
`

**Comment by varbrad** [comment]
I too ran into this issue somewhere after upgrading Vue/VueRouter. Where before you could refer to components by their name directly as a string, now it seems you have to refer to them using Vue.component(...).

before;
`path: '/example', component: 'foo'`

after;
`path: '/example', component: Vue.component('foo')`

**Comment by franckysolo** [comment]
hello,
the issue was due to bad writing 
the bad :
```js
const getters = {
  bills:  state.items
}
```
the good
```js
const getters = {
  bills: state => state.items
}
```
The issue appear too when the main getters.js file is empty and others getters are defined in modules
Another thing for the calendar, the issue was due to double tag template in my vue component
So sorry i made a mistake on writing code

i isolate the bug in vuex function 
```js
function wrapGetters (store, moduleGetters, modulePath) {
  Object.keys(moduleGetters).forEach(function (getterKey) {
    var rawGetter = moduleGetters[getterKey]
    if (typeof rawGetter !== 'function') { // Maybe add a warn  
      console.info(getterKey) 
    }
    if (store._wrappedGetters[getterKey]) {
      console.error(("[vuex] duplicate getter key: " + getterKey))
      return
    }
    store._wrappedGetters[getterKey] = function wrappedGetter (store) {
      return rawGetter(
        getNestedState(store.state, modulePath), // local state
        store.getters, // getters
        store.state // root state
      )
    }
  })
}
```

**Comment by yyx990803** [comment]
FYI using string ID for `component` was never intended to be supported - it worked in some cases by accident. The documentation also had a misleading comment. In the future it will be explicitly warned against.

**Comment by ktquez** [comment]
I am with the same error, I integrated the version 2.1.1 in the project of vue-hackernews 2. With a version 2.0.3 works ok, but above this version gives this error.

Has anyone had a solution?

**Comment by p4m** [comment]
Instead of

const routes = [
  { path: '/products/', component: 'my-products' },
  { path: '/product/:id', component: 'my-product' }
]

use

const routes = [
  { path: '/products/', component: Vue.component('my-products') },
  { path: '/product/:id', component: Vue.component('my-product') }
]


Kind Regards,

Frank Welten

: publishfor.me

Wildenborchallee 43
6921 JZ  Duiven
The Netherlands

+31 6 54970030
www.linkedin.com/in/frankwelten

2016-12-03 7:22 GMT+01:00 Alan Albuquerque <notifications@github.com>:
