### ISSUE TITLE
Redirected routes not updating view

### ISSUE THREAD

**Issue by Zumbala** [vuejs/vue-router#989]
{ path : '/login', component : loader(VIEWS,'Login.vue')}
    ,{ path : '/logout', component : loader(VIEWS,'Logout.vue'), meta : { auth : true} }
    ,{ path : '/overview', component : loader(VIEWS,'Overview.vue'), meta : { auth : true} }
    ,{ path : '/home', redirect : '/overview'},
    ,{ path : '*', redirect: '/home'}

When current view is overview and eg the session has expired, this will call $router.push("/home")
which wil redirect again to overview. (why? i want this optional to goto to users choice)

the BeforeEach hook will than check if the session is OK and if not call $router.push("/login")

But because the isSameRoute does not take into account the redirectedFrom it will not generate a change but an abort

Is this a bug or intentional?
Can I resolve this another way, maybe missing a feature or not knowing.

**Comment by LinusBorg** [comment]
> When current view is overview and eg the session has expired, this will call $router.push("/home")
which wil redirect again to overview. (why? i want this optional to goto to users choice)

It's your code, and you don't show it to me, so how should I know?

This seems like a usage question, so this should be continued somehwere else, because  the issue tracker is reserved exclusively for bug reports and feature requests (as outlined in our [Contributing Guide](https://github.com/vuejs/vue/blob/dev/.github/CONTRIBUTING.md)).

We encourage you to ask it again on the [forum ](http://forum.vuejs.org) , [Stack Overflow](http://stackoverflow.com/questions/tagged/vue.js) or on [gitter](http://gitter.im/vuejs/vue) and are happy to help you out there.

If this ends up as a bug, we open another issue.

**Comment by Zumbala** [comment]
function isSameRoute (a, b) {
	  if (b === START) {
	    return a === b
	  } else if (!b) {
	    return false
	  } else if (a.path && b.path) {
	    return (
	      a.path.replace(trailingSlashRE, '') === b.path.replace(trailingSlashRE, '') &&
	      a.hash === b.hash &&
	      isObjectEqual(a.query, b.query)
	    )
	  } else if (a.name && b.name) {
	    return (
	      a.name === b.name &&
	      a.hash === b.hash &&
	      isObjectEqual(a.query, b.query) &&
	      isObjectEqual(a.params, b.params)
	    )
	  } else {
	    return false
	  }
	}

Seems to me that this is your code and this does not take into account the redirectedFrom, to see if it is changed.

**Comment by LinusBorg** [comment]
Sorry if I may have missunderstood what your issue is. Your original post is a bit confusing (maybe the language?) and does not contain a demo of the issue you seem to have so its hard to exactly see what you think is wrong.

* If you think this is a bug or are sure you want to request a feature, please follow the [Contributing Guidelines](https://github.com/vuejs/vue/blob/dev/.github/CONTRIBUTING.md) and provide a real report with a interactive demonstration about what the issue is, 
* or: you go to the forum, post there, and we can try and see weither your problem (which i still don't really get) can be solved with the existing features.
